### ISSUE TITLE
warble needs better error messages for new users

### ISSUE THREAD

**Issue by curtcox** [jruby/warbler#119]
I'm trying to get going with warbler.   I'm beating my head against the error message below.  As a newbie, it doesn't give me any next step.  Please provide a better error message, or perhaps a FAQ entry.

```
$ gem install warbler
Successfully installed warbler-1.3.6
1 gem installed
Installing ri documentation for warbler-1.3.6...
Installing RDoc documentation for warbler-1.3.6...

$ warble
warble aborted!
cannot load such file -- java

(See full trace by running task with --trace)
```
##

**Comment by BugDiver** [comment]
I'm getting the same issue with latest version of warble.

ruby version : ruby 2.3.1p112 (2016-04-26 revision 54768) [x86_64-darwin15]

stack-trace:- 
```
/usr/local/lib/ruby/gems/2.3.0/gems/newrelic_rpm-3.18.1.330/lib/new_relic/agent/transaction.rb:23: warning: already initialized constant NewRelic::Agent::Transaction::SUBTRANSACTION_PREFIX
/usr/local/lib/ruby/gems/2.3.0/gems/newrelic_rpm-3.18.1.330/lib/new_relic/agent/transaction.rb:23: warning: previous definition of SUBTRANSACTION_PREFIX was here
/usr/local/lib/ruby/gems/2.3.0/gems/newrelic_rpm-3.18.1.330/lib/new_relic/agent/transaction.rb:24: warning: already initialized constant NewRelic::Agent::Transaction::CONTROLLER_PREFIX
/usr/local/lib/ruby/gems/2.3.0/gems/newrelic_rpm-3.18.1.330/lib/new_relic/agent/transaction.rb:24: warning: previous definition of CONTROLLER_PREFIX was here
/usr/local/lib/ruby/gems/2.3.0/gems/newrelic_rpm-3.18.1.330/lib/new_relic/agent/transaction.rb:25: warning: already initialized constant NewRelic::Agent::Transaction::MIDDLEWARE_PREFIX
/usr/local/lib/ruby/gems/2.3.0/gems/newrelic_rpm-3.18.1.330/lib/new_relic/agent/transaction.rb:25: warning: previous definition of MIDDLEWARE_PREFIX was here
/usr/local/lib/ruby/gems/2.3.0/gems/newrelic_rpm-3.18.1.330/lib/new_relic/agent/transaction.rb:26: warning: already initialized constant NewRelic::Agent::Transaction::TASK_PREFIX
/usr/local/lib/ruby/gems/2.3.0/gems/newrelic_rpm-3.18.1.330/lib/new_relic/agent/transaction.rb:26: warning: previous definition of TASK_PREFIX was here
/usr/local/lib/ruby/gems/2.3.0/gems/newrelic_rpm-3.18.1.330/lib/new_relic/agent/transaction.rb:27: warning: already initialized constant NewRelic::Agent::Transaction::RAKE_PREFIX
/usr/local/lib/ruby/gems/2.3.0/gems/newrelic_rpm-3.18.1.330/lib/new_relic/agent/transaction.rb:27: warning: previous definition of RAKE_PREFIX was here
/usr/local/lib/ruby/gems/2.3.0/gems/newrelic_rpm-3.18.1.330/lib/new_relic/agent/transaction.rb:28: warning: already initialized constant NewRelic::Agent::Transaction::RACK_PREFIX
/usr/local/lib/ruby/gems/2.3.0/gems/newrelic_rpm-3.18.1.330/lib/new_relic/agent/transaction.rb:28: warning: previous definition of RACK_PREFIX was here
/usr/local/lib/ruby/gems/2.3.0/gems/newrelic_rpm-3.18.1.330/lib/new_relic/agent/transaction.rb:29: warning: already initialized constant NewRelic::Agent::Transaction::SINATRA_PREFIX
/usr/local/lib/ruby/gems/2.3.0/gems/newrelic_rpm-3.18.1.330/lib/new_relic/agent/transaction.rb:29: warning: previous definition of SINATRA_PREFIX was here
/usr/local/lib/ruby/gems/2.3.0/gems/newrelic_rpm-3.18.1.330/lib/new_relic/agent/transaction.rb:30: warning: already initialized constant NewRelic::Agent::Transaction::GRAPE_PREFIX
/usr/local/lib/ruby/gems/2.3.0/gems/newrelic_rpm-3.18.1.330/lib/new_relic/agent/transaction.rb:30: warning: previous definition of GRAPE_PREFIX was here
/usr/local/lib/ruby/gems/2.3.0/gems/newrelic_rpm-3.18.1.330/lib/new_relic/agent/transaction.rb:31: warning: already initialized constant NewRelic::Agent::Transaction::ACTION_CABLE_PREFIX
/usr/local/lib/ruby/gems/2.3.0/gems/newrelic_rpm-3.18.1.330/lib/new_relic/agent/transaction.rb:31: warning: previous definition of ACTION_CABLE_PREFIX was here
/usr/local/lib/ruby/gems/2.3.0/gems/newrelic_rpm-3.18.1.330/lib/new_relic/agent/transaction.rb:32: warning: already initialized constant NewRelic::Agent::Transaction::OTHER_TRANSACTION_PREFIX
/usr/local/lib/ruby/gems/2.3.0/gems/newrelic_rpm-3.18.1.330/lib/new_relic/agent/transaction.rb:32: warning: previous definition of OTHER_TRANSACTION_PREFIX was here
/usr/local/lib/ruby/gems/2.3.0/gems/newrelic_rpm-3.18.1.330/lib/new_relic/agent/transaction.rb:34: warning: already initialized constant NewRelic::Agent::Transaction::CONTROLLER_MIDDLEWARE_PREFIX
/usr/local/lib/ruby/gems/2.3.0/gems/newrelic_rpm-3.18.1.330/lib/new_relic/agent/transaction.rb:34: warning: previous definition of CONTROLLER_MIDDLEWARE_PREFIX was here
/usr/local/lib/ruby/gems/2.3.0/gems/newrelic_rpm-3.18.1.330/lib/new_relic/agent/transaction.rb:36: warning: already initialized constant NewRelic::Agent::Transaction::NESTED_TRACE_STOP_OPTIONS
/usr/local/lib/ruby/gems/2.3.0/gems/newrelic_rpm-3.18.1.330/lib/new_relic/agent/transaction.rb:36: warning: previous definition of NESTED_TRACE_STOP_OPTIONS was here
/usr/local/lib/ruby/gems/2.3.0/gems/newrelic_rpm-3.18.1.330/lib/new_relic/agent/transaction.rb:37: warning: already initialized constant NewRelic::Agent::Transaction::WEB_TRANSACTION_CATEGORIES
/usr/local/lib/ruby/gems/2.3.0/gems/newrelic_rpm-3.18.1.330/lib/new_relic/agent/transaction.rb:37: warning: previous definition of WEB_TRANSACTION_CATEGORIES was here
/usr/local/lib/ruby/gems/2.3.0/gems/newrelic_rpm-3.18.1.330/lib/new_relic/agent/transaction.rb:38: warning: already initialized constant NewRelic::Agent::Transaction::TRANSACTION_NAMING_SOURCES
/usr/local/lib/ruby/gems/2.3.0/gems/newrelic_rpm-3.18.1.330/lib/new_relic/agent/transaction.rb:38: warning: previous definition of TRANSACTION_NAMING_SOURCES was here
/usr/local/lib/ruby/gems/2.3.0/gems/newrelic_rpm-3.18.1.330/lib/new_relic/agent/transaction.rb:40: warning: already initialized constant NewRelic::Agent::Transaction::MIDDLEWARE_SUMMARY_METRICS
/usr/local/lib/ruby/gems/2.3.0/gems/newrelic_rpm-3.18.1.330/lib/new_relic/agent/transaction.rb:40: warning: previous definition of MIDDLEWARE_SUMMARY_METRICS was here
/usr/local/lib/ruby/gems/2.3.0/gems/newrelic_rpm-3.18.1.330/lib/new_relic/agent/transaction.rb:41: warning: already initialized constant NewRelic::Agent::Transaction::EMPTY_SUMMARY_METRICS
/usr/local/lib/ruby/gems/2.3.0/gems/newrelic_rpm-3.18.1.330/lib/new_relic/agent/transaction.rb:41: warning: previous definition of EMPTY_SUMMARY_METRICS was here
/usr/local/lib/ruby/gems/2.3.0/gems/newrelic_rpm-3.18.1.330/lib/new_relic/agent/transaction.rb:43: warning: already initialized constant NewRelic::Agent::Transaction::TRACE_OPTIONS_SCOPED
/usr/local/lib/ruby/gems/2.3.0/gems/newrelic_rpm-3.18.1.330/lib/new_relic/agent/transaction.rb:43: warning: previous definition of TRACE_OPTIONS_SCOPED was here
/usr/local/lib/ruby/gems/2.3.0/gems/newrelic_rpm-3.18.1.330/lib/new_relic/agent/transaction.rb:44: warning: already initialized constant NewRelic::Agent::Transaction::TRACE_OPTIONS_UNSCOPED
/usr/local/lib/ruby/gems/2.3.0/gems/newrelic_rpm-3.18.1.330/lib/new_relic/agent/transaction.rb:44: warning: previous definition of TRACE_OPTIONS_UNSCOPED was here
/usr/local/lib/ruby/gems/2.3.0/gems/newrelic_rpm-3.18.1.330/lib/new_relic/agent/transaction.rb:141: warning: already initialized constant NewRelic::Agent::Transaction::FAILED_TO_STOP_MESSAGE
/usr/local/lib/ruby/gems/2.3.0/gems/newrelic_rpm-3.18.1.330/lib/new_relic/agent/transaction.rb:141: warning: previous definition of FAILED_TO_STOP_MESSAGE was here
warble aborted!
LoadError: cannot load such file -- java
/usr/local/lib/ruby/gems/2.3.0/gems/activesupport-4.2.7.1/lib/active_support/dependencies.rb:274:in `require'
/usr/local/lib/ruby/gems/2.3.0/gems/activesupport-4.2.7.1/lib/active_support/dependencies.rb:274:in `block in require'
/usr/local/lib/ruby/gems/2.3.0/gems/activesupport-4.2.7.1/lib/active_support/dependencies.rb:240:in `load_dependency'
/usr/local/lib/ruby/gems/2.3.0/gems/activesupport-4.2.7.1/lib/active_support/dependencies.rb:274:in `require'
/usr/local/lib/ruby/gems/2.3.0/gems/newrelic_rpm-3.18.1.330/lib/new_relic/agent/transaction.rb:260:in `<class:Transaction>'
/usr/local/lib/ruby/gems/2.3.0/gems/newrelic_rpm-3.18.1.330/lib/new_relic/agent/transaction.rb:19:in `<module:Agent>'
/usr/local/lib/ruby/gems/2.3.0/gems/newrelic_rpm-3.18.1.330/lib/new_relic/agent/transaction.rb:14:in `<module:NewRelic>'
/usr/local/lib/ruby/gems/2.3.0/gems/newrelic_rpm-3.18.1.330/lib/new_relic/agent/transaction.rb:13:in `<top (required)>'
/usr/local/lib/ruby/gems/2.3.0/gems/activesupport-4.2.7.1/lib/active_support/dependencies.rb:274:in `require'
/usr/local/lib/ruby/gems/2.3.0/gems/activesupport-4.2.7.1/lib/active_support/dependencies.rb:274:in `block in require'
/usr/local/lib/ruby/gems/2.3.0/gems/activesupport-4.2.7.1/lib/active_support/dependencies.rb:240:in `load_dependency'
/usr/local/lib/ruby/gems/2.3.0/gems/activesupport-4.2.7.1/lib/active_support/dependencies.rb:274:in `require'
/usr/local/lib/ruby/gems/2.3.0/gems/newrelic_rpm-3.18.1.330/lib/new_relic/agent/transaction_sample_builder.rb:6:in `<top (required)>'
/usr/local/lib/ruby/gems/2.3.0/gems/activesupport-4.2.7.1/lib/active_support/dependencies.rb:274:in `require'
/usr/local/lib/ruby/gems/2.3.0/gems/activesupport-4.2.7.1/lib/active_support/dependencies.rb:274:in `block in require'
/usr/local/lib/ruby/gems/2.3.0/gems/activesupport-4.2.7.1/lib/active_support/dependencies.rb:240:in `load_dependency'
/usr/local/lib/ruby/gems/2.3.0/gems/activesupport-4.2.7.1/lib/active_support/dependencies.rb:274:in `require'
/usr/local/lib/ruby/gems/2.3.0/gems/newrelic_rpm-3.18.1.330/lib/new_relic/agent/transaction_sampler.rb:5:in `<top (required)>'
/usr/local/lib/ruby/gems/2.3.0/gems/activesupport-4.2.7.1/lib/active_support/dependencies.rb:274:in `require'
/usr/local/lib/ruby/gems/2.3.0/gems/activesupport-4.2.7.1/lib/active_support/dependencies.rb:274:in `block in require'
/usr/local/lib/ruby/gems/2.3.0/gems/activesupport-4.2.7.1/lib/active_support/dependencies.rb:240:in `load_dependency'
/usr/local/lib/ruby/gems/2.3.0/gems/activesupport-4.2.7.1/lib/active_support/dependencies.rb:274:in `require'
/usr/local/lib/ruby/gems/2.3.0/gems/newrelic_rpm-3.18.1.330/lib/new_relic/agent.rb:44:in `<module:Agent>'
/usr/local/lib/ruby/gems/2.3.0/gems/newrelic_rpm-3.18.1.330/lib/new_relic/agent.rb:23:in `<module:NewRelic>'
/usr/local/lib/ruby/gems/2.3.0/gems/newrelic_rpm-3.18.1.330/lib/new_relic/agent.rb:8:in `<top (required)>'
/usr/local/lib/ruby/gems/2.3.0/gems/activesupport-4.2.7.1/lib/active_support/dependencies.rb:274:in `require'
/usr/local/lib/ruby/gems/2.3.0/gems/activesupport-4.2.7.1/lib/active_support/dependencies.rb:274:in `block in require'
/usr/local/lib/ruby/gems/2.3.0/gems/activesupport-4.2.7.1/lib/active_support/dependencies.rb:240:in `load_dependency'
/usr/local/lib/ruby/gems/2.3.0/gems/activesupport-4.2.7.1/lib/active_support/dependencies.rb:274:in `require'
/usr/local/lib/ruby/gems/2.3.0/gems/newrelic_rpm-3.18.1.330/lib/new_relic/control.rb:23:in `<top (required)>'
/usr/local/lib/ruby/gems/2.3.0/gems/activesupport-4.2.7.1/lib/active_support/dependencies.rb:274:in `require'
/usr/local/lib/ruby/gems/2.3.0/gems/activesupport-4.2.7.1/lib/active_support/dependencies.rb:274:in `block in require'
/usr/local/lib/ruby/gems/2.3.0/gems/activesupport-4.2.7.1/lib/active_support/dependencies.rb:240:in `load_dependency'
/usr/local/lib/ruby/gems/2.3.0/gems/activesupport-4.2.7.1/lib/active_support/dependencies.rb:274:in `require'
/usr/local/lib/ruby/gems/2.3.0/gems/newrelic_rpm-3.18.1.330/lib/newrelic_rpm.rb:25:in `<top (required)>'
/usr/local/lib/ruby/gems/2.3.0/gems/bundler-1.14.3/lib/bundler/runtime.rb:91:in `require'
/usr/local/lib/ruby/gems/2.3.0/gems/bundler-1.14.3/lib/bundler/runtime.rb:91:in `block (2 levels) in require'
/usr/local/lib/ruby/gems/2.3.0/gems/bundler-1.14.3/lib/bundler/runtime.rb:86:in `each'
/usr/local/lib/ruby/gems/2.3.0/gems/bundler-1.14.3/lib/bundler/runtime.rb:86:in `block in require'
/usr/local/lib/ruby/gems/2.3.0/gems/bundler-1.14.3/lib/bundler/runtime.rb:75:in `each'
/usr/local/lib/ruby/gems/2.3.0/gems/bundler-1.14.3/lib/bundler/runtime.rb:75:in `require'
/usr/local/lib/ruby/gems/2.3.0/gems/bundler-1.14.3/lib/bundler.rb:107:in `require'
/Users/vinaysh/work/src/github.com/getgauge/demo.activeadmin.info/config/application.rb:7:in `<top (required)>'
/usr/local/lib/ruby/gems/2.3.0/gems/activesupport-4.2.7.1/lib/active_support/dependencies.rb:274:in `require'
/usr/local/lib/ruby/gems/2.3.0/gems/activesupport-4.2.7.1/lib/active_support/dependencies.rb:274:in `block in require'
/usr/local/lib/ruby/gems/2.3.0/gems/activesupport-4.2.7.1/lib/active_support/dependencies.rb:240:in `load_dependency'
/usr/local/lib/ruby/gems/2.3.0/gems/activesupport-4.2.7.1/lib/active_support/dependencies.rb:274:in `require'
/Users/vinaysh/work/src/github.com/getgauge/demo.activeadmin.info/rakefile:4:in `<top (required)>'
/usr/local/lib/ruby/gems/2.3.0/gems/activesupport-4.2.7.1/lib/active_support/dependencies.rb:268:in `load'
/usr/local/lib/ruby/gems/2.3.0/gems/activesupport-4.2.7.1/lib/active_support/dependencies.rb:268:in `block in load'
/usr/local/lib/ruby/gems/2.3.0/gems/activesupport-4.2.7.1/lib/active_support/dependencies.rb:240:in `load_dependency'
/usr/local/lib/ruby/gems/2.3.0/gems/activesupport-4.2.7.1/lib/active_support/dependencies.rb:268:in `load'
/usr/local/lib/ruby/gems/2.3.0/gems/warbler-2.0.4/lib/warbler/application.rb:63:in `rescue in block in load_project_rakefile'
/usr/local/lib/ruby/gems/2.3.0/gems/warbler-2.0.4/lib/warbler/application.rb:60:in `block in load_project_rakefile'
/usr/local/lib/ruby/gems/2.3.0/gems/warbler-2.0.4/lib/warbler/application.rb:58:in `each'
/usr/local/lib/ruby/gems/2.3.0/gems/warbler-2.0.4/lib/warbler/application.rb:58:in `load_project_rakefile'
/usr/local/lib/ruby/gems/2.3.0/gems/warbler-2.0.4/lib/warbler.rb:26:in `project_application'
/usr/local/lib/ruby/gems/2.3.0/gems/warbler-2.0.4/lib/warbler/traits/rails.rb:27:in `before_configure'
/usr/local/lib/ruby/gems/2.3.0/gems/warbler-2.0.4/lib/warbler/traits.rb:29:in `block in before_configure'
/usr/local/lib/ruby/gems/2.3.0/gems/warbler-2.0.4/lib/warbler/traits.rb:29:in `each'
/usr/local/lib/ruby/gems/2.3.0/gems/warbler-2.0.4/lib/warbler/traits.rb:29:in `before_configure'
/usr/local/lib/ruby/gems/2.3.0/gems/warbler-2.0.4/lib/warbler/config.rb:215:in `initialize'
/usr/local/lib/ruby/gems/2.3.0/gems/warbler-2.0.4/lib/warbler/task.rb:48:in `new'
/usr/local/lib/ruby/gems/2.3.0/gems/warbler-2.0.4/lib/warbler/task.rb:48:in `initialize'
/usr/local/lib/ruby/gems/2.3.0/gems/warbler-2.0.4/lib/warbler/application.rb:27:in `new'
/usr/local/lib/ruby/gems/2.3.0/gems/warbler-2.0.4/lib/warbler/application.rb:27:in `load_rakefile'
/usr/local/lib/ruby/gems/2.3.0/gems/rake-12.0.0/lib/rake/application.rb:79:in `block in run'
/usr/local/lib/ruby/gems/2.3.0/gems/rake-12.0.0/lib/rake/application.rb:178:in `standard_exception_handling'
/usr/local/lib/ruby/gems/2.3.0/gems/rake-12.0.0/lib/rake/application.rb:77:in `run'
/usr/local/lib/ruby/gems/2.3.0/gems/warbler-2.0.4/lib/warbler/application.rb:79:in `run'
/usr/local/lib/ruby/gems/2.3.0/gems/warbler-2.0.4/lib/warbler/application.rb:74:in `run'
/usr/local/lib/ruby/gems/2.3.0/gems/warbler-2.0.4/bin/warble:11:in `<top (required)>'
/usr/local/bin/warble:23:in `load'
/usr/local/bin/warble:23:in `<main>'
LoadError: cannot load such file -- java
/usr/local/lib/ruby/gems/2.3.0/gems/activesupport-4.2.7.1/lib/active_support/dependencies.rb:274:in `require'
/usr/local/lib/ruby/gems/2.3.0/gems/activesupport-4.2.7.1/lib/active_support/dependencies.rb:274:in `block in require'
/usr/local/lib/ruby/gems/2.3.0/gems/activesupport-4.2.7.1/lib/active_support/dependencies.rb:240:in `load_dependency'
/usr/local/lib/ruby/gems/2.3.0/gems/activesupport-4.2.7.1/lib/active_support/dependencies.rb:274:in `require'
/usr/local/lib/ruby/gems/2.3.0/gems/newrelic_rpm-3.18.1.330/lib/new_relic/agent/transaction.rb:260:in `<class:Transaction>'
/usr/local/lib/ruby/gems/2.3.0/gems/newrelic_rpm-3.18.1.330/lib/new_relic/agent/transaction.rb:19:in `<module:Agent>'
/usr/local/lib/ruby/gems/2.3.0/gems/newrelic_rpm-3.18.1.330/lib/new_relic/agent/transaction.rb:14:in `<module:NewRelic>'
/usr/local/lib/ruby/gems/2.3.0/gems/newrelic_rpm-3.18.1.330/lib/new_relic/agent/transaction.rb:13:in `<top (required)>'
/usr/local/lib/ruby/gems/2.3.0/gems/activesupport-4.2.7.1/lib/active_support/dependencies.rb:274:in `require'
/usr/local/lib/ruby/gems/2.3.0/gems/activesupport-4.2.7.1/lib/active_support/dependencies.rb:274:in `block in require'
/usr/local/lib/ruby/gems/2.3.0/gems/activesupport-4.2.7.1/lib/active_support/dependencies.rb:240:in `load_dependency'
/usr/local/lib/ruby/gems/2.3.0/gems/activesupport-4.2.7.1/lib/active_support/dependencies.rb:274:in `require'
/usr/local/lib/ruby/gems/2.3.0/gems/newrelic_rpm-3.18.1.330/lib/new_relic/agent/transaction_sample_builder.rb:6:in `<top (required)>'
/usr/local/lib/ruby/gems/2.3.0/gems/activesupport-4.2.7.1/lib/active_support/dependencies.rb:274:in `require'
/usr/local/lib/ruby/gems/2.3.0/gems/activesupport-4.2.7.1/lib/active_support/dependencies.rb:274:in `block in require'
/usr/local/lib/ruby/gems/2.3.0/gems/activesupport-4.2.7.1/lib/active_support/dependencies.rb:240:in `load_dependency'
/usr/local/lib/ruby/gems/2.3.0/gems/activesupport-4.2.7.1/lib/active_support/dependencies.rb:274:in `require'
/usr/local/lib/ruby/gems/2.3.0/gems/newrelic_rpm-3.18.1.330/lib/new_relic/agent/transaction_sampler.rb:5:in `<top (required)>'
/usr/local/lib/ruby/gems/2.3.0/gems/activesupport-4.2.7.1/lib/active_support/dependencies.rb:274:in `require'
/usr/local/lib/ruby/gems/2.3.0/gems/activesupport-4.2.7.1/lib/active_support/dependencies.rb:274:in `block in require'
/usr/local/lib/ruby/gems/2.3.0/gems/activesupport-4.2.7.1/lib/active_support/dependencies.rb:240:in `load_dependency'
/usr/local/lib/ruby/gems/2.3.0/gems/activesupport-4.2.7.1/lib/active_support/dependencies.rb:274:in `require'
/usr/local/lib/ruby/gems/2.3.0/gems/newrelic_rpm-3.18.1.330/lib/new_relic/agent.rb:44:in `<module:Agent>'
/usr/local/lib/ruby/gems/2.3.0/gems/newrelic_rpm-3.18.1.330/lib/new_relic/agent.rb:23:in `<module:NewRelic>'
/usr/local/lib/ruby/gems/2.3.0/gems/newrelic_rpm-3.18.1.330/lib/new_relic/agent.rb:8:in `<top (required)>'
/usr/local/lib/ruby/gems/2.3.0/gems/activesupport-4.2.7.1/lib/active_support/dependencies.rb:274:in `require'
/usr/local/lib/ruby/gems/2.3.0/gems/activesupport-4.2.7.1/lib/active_support/dependencies.rb:274:in `block in require'
/usr/local/lib/ruby/gems/2.3.0/gems/activesupport-4.2.7.1/lib/active_support/dependencies.rb:240:in `load_dependency'
/usr/local/lib/ruby/gems/2.3.0/gems/activesupport-4.2.7.1/lib/active_support/dependencies.rb:274:in `require'
/usr/local/lib/ruby/gems/2.3.0/gems/newrelic_rpm-3.18.1.330/lib/new_relic/control.rb:23:in `<top (required)>'
/usr/local/lib/ruby/gems/2.3.0/gems/activesupport-4.2.7.1/lib/active_support/dependencies.rb:274:in `require'
/usr/local/lib/ruby/gems/2.3.0/gems/activesupport-4.2.7.1/lib/active_support/dependencies.rb:274:in `block in require'
/usr/local/lib/ruby/gems/2.3.0/gems/activesupport-4.2.7.1/lib/active_support/dependencies.rb:240:in `load_dependency'
/usr/local/lib/ruby/gems/2.3.0/gems/activesupport-4.2.7.1/lib/active_support/dependencies.rb:274:in `require'
/usr/local/lib/ruby/gems/2.3.0/gems/newrelic_rpm-3.18.1.330/lib/newrelic_rpm.rb:25:in `<top (required)>'
/usr/local/lib/ruby/gems/2.3.0/gems/bundler-1.14.3/lib/bundler/runtime.rb:91:in `require'
/usr/local/lib/ruby/gems/2.3.0/gems/bundler-1.14.3/lib/bundler/runtime.rb:91:in `block (2 levels) in require'
/usr/local/lib/ruby/gems/2.3.0/gems/bundler-1.14.3/lib/bundler/runtime.rb:86:in `each'
/usr/local/lib/ruby/gems/2.3.0/gems/bundler-1.14.3/lib/bundler/runtime.rb:86:in `block in require'
/usr/local/lib/ruby/gems/2.3.0/gems/bundler-1.14.3/lib/bundler/runtime.rb:75:in `each'
/usr/local/lib/ruby/gems/2.3.0/gems/bundler-1.14.3/lib/bundler/runtime.rb:75:in `require'
/usr/local/lib/ruby/gems/2.3.0/gems/bundler-1.14.3/lib/bundler.rb:107:in `require'
/Users/vinaysh/work/src/github.com/getgauge/demo.activeadmin.info/config/application.rb:7:in `<top (required)>'
/usr/local/Cellar/ruby/2.3.1/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/usr/local/Cellar/ruby/2.3.1/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
rakefile:4:in `<top (required)>'
/usr/local/lib/ruby/gems/2.3.0/gems/warbler-2.0.4/lib/warbler/application.rb:61:in `load'
/usr/local/lib/ruby/gems/2.3.0/gems/warbler-2.0.4/lib/warbler/application.rb:61:in `block in load_project_rakefile'
/usr/local/lib/ruby/gems/2.3.0/gems/warbler-2.0.4/lib/warbler/application.rb:58:in `each'
/usr/local/lib/ruby/gems/2.3.0/gems/warbler-2.0.4/lib/warbler/application.rb:58:in `load_project_rakefile'
/usr/local/lib/ruby/gems/2.3.0/gems/warbler-2.0.4/lib/warbler.rb:26:in `project_application'
/usr/local/lib/ruby/gems/2.3.0/gems/warbler-2.0.4/lib/warbler/traits/rails.rb:27:in `before_configure'
/usr/local/lib/ruby/gems/2.3.0/gems/warbler-2.0.4/lib/warbler/traits.rb:29:in `block in before_configure'
/usr/local/lib/ruby/gems/2.3.0/gems/warbler-2.0.4/lib/warbler/traits.rb:29:in `each'
/usr/local/lib/ruby/gems/2.3.0/gems/warbler-2.0.4/lib/warbler/traits.rb:29:in `before_configure'
/usr/local/lib/ruby/gems/2.3.0/gems/warbler-2.0.4/lib/warbler/config.rb:215:in `initialize'
/usr/local/lib/ruby/gems/2.3.0/gems/warbler-2.0.4/lib/warbler/task.rb:48:in `new'
/usr/local/lib/ruby/gems/2.3.0/gems/warbler-2.0.4/lib/warbler/task.rb:48:in `initialize'
/usr/local/lib/ruby/gems/2.3.0/gems/warbler-2.0.4/lib/warbler/application.rb:27:in `new'
/usr/local/lib/ruby/gems/2.3.0/gems/warbler-2.0.4/lib/warbler/application.rb:27:in `load_rakefile'
/usr/local/lib/ruby/gems/2.3.0/gems/rake-12.0.0/lib/rake/application.rb:79:in `block in run'
/usr/local/lib/ruby/gems/2.3.0/gems/rake-12.0.0/lib/rake/application.rb:178:in `standard_exception_handling'
/usr/local/lib/ruby/gems/2.3.0/gems/rake-12.0.0/lib/rake/application.rb:77:in `run'
/usr/local/lib/ruby/gems/2.3.0/gems/warbler-2.0.4/lib/warbler/application.rb:79:in `run'
/usr/local/lib/ruby/gems/2.3.0/gems/warbler-2.0.4/lib/warbler/application.rb:74:in `run'
/usr/local/lib/ruby/gems/2.3.0/gems/warbler-2.0.4/bin/warble:11:in `<top (required)>'
/usr/local/bin/warble:23:in `load'
/usr/local/bin/warble:23:in `<main>'

```
