### ISSUE TITLE
Several runnable war errors

### ISSUE THREAD

**Issue by arturadib** [jruby/warbler#155]
After the fix in #153, now I'm getting different errors depending on what command I run after `-S`. All the snippets below use `rbenv` + `jruby 1.7.3` on a fresh new Rails 3 app, after creating a runnable war file via `warble runnable war`:

```
$ java -jar blog.war -S rake test
/bin/sh: file:/var/folders/zz/9q_gx64j305dgv873hmnf8rm0000gn/T/jruby6621459696014880043extract/lib/jruby-stdlib-1.7.3.jar!/META-INF/jruby.home/bin/jruby: No such file or directory
/bin/sh: file:/var/folders/zz/9q_gx64j305dgv873hmnf8rm0000gn/T/jruby6621459696014880043extract/lib/jruby-stdlib-1.7.3.jar!/META-INF/jruby.home/bin/jruby: No such file or directory
/bin/sh: file:/var/folders/zz/9q_gx64j305dgv873hmnf8rm0000gn/T/jruby6621459696014880043extract/lib/jruby-stdlib-1.7.3.jar!/META-INF/jruby.home/bin/jruby: No such file or directory
```

```
$ java -jar blog.war -S bundle exec rake test
rake aborted!
missing class or uppercase package name (`org.jruby.ext.openssl.OSSLLibrary')
org/jruby/javasupport/JavaUtilities.java:54:in `get_proxy_or_package_under_package'
/var/folders/zz/9q_gx64j305dgv873hmnf8rm0000gn/T/jruby5360857597955030692extract/gems/gems/jruby-openssl-0.8.7/lib/shared/jruby-openssl.rb:15:in `(root)'
org/jruby/RubyKernel.java:1027:in `require'
/var/folders/zz/9q_gx64j305dgv873hmnf8rm0000gn/T/jruby5360857597955030692extract/gems/gems/bundler-1.3.5/lib/bundler/runtime.rb:1:in `(root)'
org/jruby/RubyArray.java:1613:in `each'
/var/folders/zz/9q_gx64j305dgv873hmnf8rm0000gn/T/jruby5360857597955030692extract/gems/gems/bundler-1.3.5/lib/bundler/runtime.rb:72:in `require'
org/jruby/RubyArray.java:1613:in `each'
/var/folders/zz/9q_gx64j305dgv873hmnf8rm0000gn/T/jruby5360857597955030692extract/gems/gems/bundler-1.3.5/lib/bundler/runtime.rb:70:in `require'
/var/folders/zz/9q_gx64j305dgv873hmnf8rm0000gn/T/jruby5360857597955030692extract/gems/gems/bundler-1.3.5/lib/bundler/runtime.rb:59:in `require'
/var/folders/zz/9q_gx64j305dgv873hmnf8rm0000gn/T/jruby5360857597955030692extract/gems/gems/bundler-1.3.5/lib/bundler.rb:132:in `require'
org/jruby/RubyKernel.java:1027:in `require'
/Users/aadib/temp/blog/config/application.rb:7:in `(root)'
org/jruby/RubyKernel.java:1046:in `load'
/Users/aadib/temp/blog/Rakefile:1:in `(root)'
/Users/aadib/temp/blog/Rakefile:5:in `(root)'
/var/folders/zz/9q_gx64j305dgv873hmnf8rm0000gn/T/jruby5360857597955030692extract/gems/gems/rake-10.0.4/lib/rake/rake_module.rb:1:in `(root)'
/var/folders/zz/9q_gx64j305dgv873hmnf8rm0000gn/T/jruby5360857597955030692extract/gems/gems/rake-10.0.4/lib/rake/rake_module.rb:25:in `load_rakefile'
/var/folders/zz/9q_gx64j305dgv873hmnf8rm0000gn/T/jruby5360857597955030692extract/gems/gems/rake-10.0.4/lib/rake/application.rb:589:in `raw_load_rakefile'
/var/folders/zz/9q_gx64j305dgv873hmnf8rm0000gn/T/jruby5360857597955030692extract/gems/gems/rake-10.0.4/lib/rake/application.rb:89:in `load_rakefile'
/var/folders/zz/9q_gx64j305dgv873hmnf8rm0000gn/T/jruby5360857597955030692extract/gems/gems/rake-10.0.4/lib/rake/application.rb:160:in `standard_exception_handling'
/var/folders/zz/9q_gx64j305dgv873hmnf8rm0000gn/T/jruby5360857597955030692extract/gems/gems/rake-10.0.4/lib/rake/application.rb:88:in `load_rakefile'
/var/folders/zz/9q_gx64j305dgv873hmnf8rm0000gn/T/jruby5360857597955030692extract/gems/gems/rake-10.0.4/lib/rake/application.rb:72:in `run'
org/jruby/RubyKernel.java:1046:in `load'
(See full trace by running task with --trace)
```

If I remove the gem `'jruby-openssl'`, then I get another error with the json gem:

```
$ java -jar blog.war -S bundle exec rake test
rake aborted!
uninitialized constant JSON::Ext::Parser
/var/folders/zz/9q_gx64j305dgv873hmnf8rm0000gn/T/jruby5654414330347064144extract/gems/gems/json-1.7.7-java/lib/json/ext.rb:16:in `Ext'
/var/folders/zz/9q_gx64j305dgv873hmnf8rm0000gn/T/jruby5654414330347064144extract/gems/gems/json-1.7.7-java/lib/json/ext.rb:12:in `JSON'
/var/folders/zz/9q_gx64j305dgv873hmnf8rm0000gn/T/jruby5654414330347064144extract/gems/gems/json-1.7.7-java/lib/json/ext.rb:9:in `(root)'
/var/folders/zz/9q_gx64j305dgv873hmnf8rm0000gn/T/jruby5654414330347064144extract/gems/gems/json-1.7.7-java/lib/json.rb:1:in `(root)'
/var/folders/zz/9q_gx64j305dgv873hmnf8rm0000gn/T/jruby5654414330347064144extract/gems/gems/json-1.7.7-java/lib/json.rb:58:in `JSON'
/var/folders/zz/9q_gx64j305dgv873hmnf8rm0000gn/T/jruby5654414330347064144extract/gems/gems/json-1.7.7-java/lib/json.rb:54:in `(root)'
/var/folders/zz/9q_gx64j305dgv873hmnf8rm0000gn/T/jruby5654414330347064144extract/gems/gems/activesupport-3.2.1/lib/active_support/core_ext/object/to_json.rb:1:in `(root)'
/var/folders/zz/9q_gx64j305dgv873hmnf8rm0000gn/T/jruby5654414330347064144extract/gems/gems/activesupport-3.2.1/lib/active_support/core_ext/object/to_json.rb:3:in `(root)'
/var/folders/zz/9q_gx64j305dgv873hmnf8rm0000gn/T/jruby5654414330347064144extract/gems/gems/activesupport-3.2.1/lib/active_support/core_ext/object.rb:1:in `each'
/var/folders/zz/9q_gx64j305dgv873hmnf8rm0000gn/T/jruby5654414330347064144extract/gems/gems/activesupport-3.2.1/lib/active_support/core_ext/object.rb:1:in `(root)'
/var/folders/zz/9q_gx64j305dgv873hmnf8rm0000gn/T/jruby5654414330347064144extract/gems/gems/activesupport-3.2.1/lib/active_support/core_ext/object.rb:10:in `(root)'
/var/folders/zz/9q_gx64j305dgv873hmnf8rm0000gn/T/jruby5654414330347064144extract/gems/gems/activesupport-3.2.1/lib/active_support/core_ext.rb:1:in `(root)'
/var/folders/zz/9q_gx64j305dgv873hmnf8rm0000gn/T/jruby5654414330347064144extract/gems/gems/activesupport-3.2.1/lib/active_support/core_ext.rb:2:in `instance_exec'
/var/folders/zz/9q_gx64j305dgv873hmnf8rm0000gn/T/jruby5654414330347064144extract/gems/gems/activesupport-3.2.1/lib/active_support/core_ext.rb:2:in `(root)'
/var/folders/zz/9q_gx64j305dgv873hmnf8rm0000gn/T/jruby5654414330347064144extract/gems/gems/activesupport-3.2.1/lib/active_support/core_ext.rb:1:in `(root)'
/var/folders/zz/9q_gx64j305dgv873hmnf8rm0000gn/T/jruby5654414330347064144extract/gems/gems/activesupport-3.2.1/lib/active_support/all.rb:1:in `each'
/var/folders/zz/9q_gx64j305dgv873hmnf8rm0000gn/T/jruby5654414330347064144extract/gems/gems/activesupport-3.2.1/lib/active_support/all.rb:1:in `(root)'
/var/folders/zz/9q_gx64j305dgv873hmnf8rm0000gn/T/jruby5654414330347064144extract/gems/gems/activesupport-3.2.1/lib/active_support/all.rb:3:in `(root)'
/var/folders/zz/9q_gx64j305dgv873hmnf8rm0000gn/T/jruby5654414330347064144extract/gems/gems/railties-3.2.1/lib/rails/application/bootstrap.rb:1:in `send'
/var/folders/zz/9q_gx64j305dgv873hmnf8rm0000gn/T/jruby5654414330347064144extract/gems/gems/railties-3.2.1/lib/rails/application/bootstrap.rb:1:in `(root)'
/var/folders/zz/9q_gx64j305dgv873hmnf8rm0000gn/T/jruby5654414330347064144extract/gems/gems/railties-3.2.1/lib/rails/application/bootstrap.rb:13:in `Bootstrap'
/var/folders/zz/9q_gx64j305dgv873hmnf8rm0000gn/T/jruby5654414330347064144extract/gems/gems/railties-3.2.1/lib/rails/initializable.rb:30:in `require'
/var/folders/zz/9q_gx64j305dgv873hmnf8rm0000gn/T/jruby5654414330347064144extract/gems/gems/railties-3.2.1/lib/rails/initializable.rb:30:in `run'
/var/folders/zz/9q_gx64j305dgv873hmnf8rm0000gn/T/jruby5654414330347064144extract/gems/gems/railties-3.2.1/lib/rails/initializable.rb:55:in `run_initializers'
/var/folders/zz/9q_gx64j305dgv873hmnf8rm0000gn/T/jruby5654414330347064144extract/gems/gems/railties-3.2.1/lib/rails/initializable.rb:54:in `call'
/var/folders/zz/9q_gx64j305dgv873hmnf8rm0000gn/T/jruby5654414330347064144extract/gems/gems/railties-3.2.1/lib/rails/initializable.rb:54:in `run_initializers'
/var/folders/zz/9q_gx64j305dgv873hmnf8rm0000gn/T/jruby5654414330347064144extract/gems/gems/railties-3.2.1/lib/rails/application.rb:136:in `each'
/var/folders/zz/9q_gx64j305dgv873hmnf8rm0000gn/T/jruby5654414330347064144extract/gems/gems/railties-3.2.1/lib/rails/application.rb:136:in `initialize!'
/var/folders/zz/9q_gx64j305dgv873hmnf8rm0000gn/T/jruby5654414330347064144extract/gems/gems/railties-3.2.1/lib/rails/railtie/configurable.rb:30:in `method_missing'
/Users/aadib/temp/blog/config/environment.rb:5:in `(root)'
/var/folders/zz/9q_gx64j305dgv873hmnf8rm0000gn/T/jruby5654414330347064144extract/gems/gems/railties-3.2.1/lib/rails/application.rb:1:in `(root)'
/var/folders/zz/9q_gx64j305dgv873hmnf8rm0000gn/T/jruby5654414330347064144extract/gems/gems/railties-3.2.1/lib/rails/application.rb:103:in `require_environment!'
/var/folders/zz/9q_gx64j305dgv873hmnf8rm0000gn/T/jruby5654414330347064144extract/gems/gems/railties-3.2.1/lib/rails/application.rb:292:in `each'
/var/folders/zz/9q_gx64j305dgv873hmnf8rm0000gn/T/jruby5654414330347064144extract/gems/gems/railties-3.2.1/lib/rails/application.rb:292:in `initialize_tasks'
/var/folders/zz/9q_gx64j305dgv873hmnf8rm0000gn/T/jruby5654414330347064144extract/gems/gems/rake-10.0.4/lib/rake/task.rb:246:in `execute'
/var/folders/zz/9q_gx64j305dgv873hmnf8rm0000gn/T/jruby5654414330347064144extract/gems/gems/rake-10.0.4/lib/rake/task.rb:241:in `execute'
/var/folders/zz/9q_gx64j305dgv873hmnf8rm0000gn/T/jruby5654414330347064144extract/gems/gems/rake-10.0.4/lib/rake/task.rb:184:in `invoke_with_call_chain'
/var/folders/zz/9q_gx64j305dgv873hmnf8rm0000gn/T/jruby5654414330347064144extract/gems/gems/rake-10.0.4/lib/rake/task.rb:177:in `each'
/var/folders/zz/9q_gx64j305dgv873hmnf8rm0000gn/T/jruby5654414330347064144extract/gems/gems/rake-10.0.4/lib/rake/task.rb:177:in `invoke_with_call_chain'
/var/folders/zz/9q_gx64j305dgv873hmnf8rm0000gn/T/jruby5654414330347064144extract/gems/gems/rake-10.0.4/lib/rake/task.rb:205:in `invoke_prerequisites'
/var/folders/zz/9q_gx64j305dgv873hmnf8rm0000gn/T/jruby5654414330347064144extract/gems/gems/rake-10.0.4/lib/rake/task.rb:203:in `invoke_prerequisites'
/var/folders/zz/9q_gx64j305dgv873hmnf8rm0000gn/T/jruby5654414330347064144extract/gems/gems/rake-10.0.4/lib/rake/task.rb:183:in `invoke_with_call_chain'
/var/folders/zz/9q_gx64j305dgv873hmnf8rm0000gn/T/jruby5654414330347064144extract/gems/gems/rake-10.0.4/lib/rake/task.rb:177:in `each'
/var/folders/zz/9q_gx64j305dgv873hmnf8rm0000gn/T/jruby5654414330347064144extract/gems/gems/rake-10.0.4/lib/rake/task.rb:177:in `invoke_with_call_chain'
/var/folders/zz/9q_gx64j305dgv873hmnf8rm0000gn/T/jruby5654414330347064144extract/gems/gems/rake-10.0.4/lib/rake/task.rb:205:in `invoke_prerequisites'
/var/folders/zz/9q_gx64j305dgv873hmnf8rm0000gn/T/jruby5654414330347064144extract/gems/gems/rake-10.0.4/lib/rake/task.rb:203:in `invoke_prerequisites'
/var/folders/zz/9q_gx64j305dgv873hmnf8rm0000gn/T/jruby5654414330347064144extract/gems/gems/rake-10.0.4/lib/rake/task.rb:183:in `invoke_with_call_chain'
/var/folders/zz/9q_gx64j305dgv873hmnf8rm0000gn/T/jruby5654414330347064144extract/gems/gems/rake-10.0.4/lib/rake/task.rb:177:in `each'
/var/folders/zz/9q_gx64j305dgv873hmnf8rm0000gn/T/jruby5654414330347064144extract/gems/gems/rake-10.0.4/lib/rake/task.rb:177:in `invoke_with_call_chain'
/var/folders/zz/9q_gx64j305dgv873hmnf8rm0000gn/T/jruby5654414330347064144extract/gems/gems/rake-10.0.4/lib/rake/task.rb:205:in `invoke_prerequisites'
/var/folders/zz/9q_gx64j305dgv873hmnf8rm0000gn/T/jruby5654414330347064144extract/gems/gems/rake-10.0.4/lib/rake/task.rb:203:in `invoke_prerequisites'
/var/folders/zz/9q_gx64j305dgv873hmnf8rm0000gn/T/jruby5654414330347064144extract/gems/gems/rake-10.0.4/lib/rake/task.rb:183:in `invoke_with_call_chain'
/var/folders/zz/9q_gx64j305dgv873hmnf8rm0000gn/T/jruby5654414330347064144extract/gems/gems/rake-10.0.4/lib/rake/task.rb:177:in `each'
/var/folders/zz/9q_gx64j305dgv873hmnf8rm0000gn/T/jruby5654414330347064144extract/gems/gems/rake-10.0.4/lib/rake/task.rb:177:in `invoke_with_call_chain'
/var/folders/zz/9q_gx64j305dgv873hmnf8rm0000gn/T/jruby5654414330347064144extract/gems/gems/rake-10.0.4/lib/rake/task.rb:205:in `invoke_prerequisites'
/var/folders/zz/9q_gx64j305dgv873hmnf8rm0000gn/T/jruby5654414330347064144extract/gems/gems/rake-10.0.4/lib/rake/task.rb:203:in `invoke_prerequisites'
/var/folders/zz/9q_gx64j305dgv873hmnf8rm0000gn/T/jruby5654414330347064144extract/gems/gems/rake-10.0.4/lib/rake/task.rb:183:in `invoke_with_call_chain'
/var/folders/zz/9q_gx64j305dgv873hmnf8rm0000gn/T/jruby5654414330347064144extract/gems/gems/rake-10.0.4/lib/rake/task.rb:177:in `invoke_with_call_chain'
/var/folders/zz/9q_gx64j305dgv873hmnf8rm0000gn/T/jruby5654414330347064144extract/gems/gems/rake-10.0.4/lib/rake/task.rb:205:in `call'
/var/folders/zz/9q_gx64j305dgv873hmnf8rm0000gn/T/jruby5654414330347064144extract/gems/gems/rake-10.0.4/lib/rake/task.rb:205:in `invoke_prerequisites'
/var/folders/zz/9q_gx64j305dgv873hmnf8rm0000gn/T/jruby5654414330347064144extract/gems/gems/rake-10.0.4/lib/rake/task.rb:203:in `each'
/var/folders/zz/9q_gx64j305dgv873hmnf8rm0000gn/T/jruby5654414330347064144extract/gems/gems/rake-10.0.4/lib/rake/task.rb:203:in `invoke_prerequisites'
/var/folders/zz/9q_gx64j305dgv873hmnf8rm0000gn/T/jruby5654414330347064144extract/gems/gems/rake-10.0.4/lib/rake/task.rb:183:in `invoke_with_call_chain'
/var/folders/zz/9q_gx64j305dgv873hmnf8rm0000gn/T/jruby5654414330347064144extract/gems/gems/rake-10.0.4/lib/rake/task.rb:177:in `invoke_with_call_chain'
/var/folders/zz/9q_gx64j305dgv873hmnf8rm0000gn/T/jruby5654414330347064144extract/gems/gems/rake-10.0.4/lib/rake/task.rb:170:in `invoke'
/var/folders/zz/9q_gx64j305dgv873hmnf8rm0000gn/T/jruby5654414330347064144extract/gems/gems/railties-3.2.1/lib/rails/test_unit/testing.rake:50:in `(root)'
/var/folders/zz/9q_gx64j305dgv873hmnf8rm0000gn/T/jruby5654414330347064144extract/gems/gems/rake-10.0.4/lib/rake/task.rb:246:in `execute'
/var/folders/zz/9q_gx64j305dgv873hmnf8rm0000gn/T/jruby5654414330347064144extract/gems/gems/rake-10.0.4/lib/rake/task.rb:241:in `each'
/var/folders/zz/9q_gx64j305dgv873hmnf8rm0000gn/T/jruby5654414330347064144extract/gems/gems/rake-10.0.4/lib/rake/task.rb:241:in `execute'
/var/folders/zz/9q_gx64j305dgv873hmnf8rm0000gn/T/jruby5654414330347064144extract/gems/gems/rake-10.0.4/lib/rake/task.rb:184:in `invoke_with_call_chain'
/var/folders/zz/9q_gx64j305dgv873hmnf8rm0000gn/T/jruby5654414330347064144extract/gems/gems/rake-10.0.4/lib/rake/task.rb:177:in `invoke_with_call_chain'
/var/folders/zz/9q_gx64j305dgv873hmnf8rm0000gn/T/jruby5654414330347064144extract/gems/gems/rake-10.0.4/lib/rake/task.rb:170:in `invoke'
/var/folders/zz/9q_gx64j305dgv873hmnf8rm0000gn/T/jruby5654414330347064144extract/gems/gems/rake-10.0.4/lib/rake/application.rb:143:in `invoke_task'
/var/folders/zz/9q_gx64j305dgv873hmnf8rm0000gn/T/jruby5654414330347064144extract/gems/gems/rake-10.0.4/lib/rake/application.rb:101:in `top_level'
Tasks: TOP => test:run => test:units => test:prepare => db:test:prepare => db:abort_if_pending_migrations => environment
(See full trace by running task with --trace)
```

**Comment by jkutner** [comment]
I think this issue has been fixed. let us know if we need to reopen.
