### ISSUE TITLE
Deploying war with tomcat7 according Parallel deployment doc

### ISSUE THREAD

**Issue by GabKlein** [jruby/warbler#163]
Hi,

Maybe you can help me to figure out the problem here.
I have a rails4-rc1 app with jruby-1.7.4.
When I'm deploying my war as "ROOT.war" everything is running fine.
When I deploying the war according "Parallel deployment doc" [link](http://tomcat.apache.org/tomcat-7.0-doc/config/context.html#Parallel_deployment) like "ROOT##01.war" instead I get this error.

It seems to be a Path Class issue but I can't figured this out.

```
org.jruby.rack.RackInitializationException: missing class or uppercase package name (`org.jruby.ext.openssl.OSSLLibrary')
    from org/jruby/javasupport/JavaUtilities.java:54:in `get_proxy_or_package_under_package'
    from file:/var/lib/tomcat7/webapps/ROOT##01/WEB-INF/lib/gems-gems-jruby-jars-1.7.4-lib-jruby-core-1.7.4.jar!/jruby/java/java_package_module_template.rb:14:in `method_missing'
    from jar:file:/var/lib/tomcat7/webapps/ROOT%23%2301/WEB-INF/lib/gems-gems-jruby-jars-1.7.4-lib-jruby-stdlib-1.7.4.jar!/META-INF/jruby.home/lib/ruby/shared/openssl.rb:24:in `(root)'
    from org/jruby/RubyKernel.java:1054:in `require'
    from /var/lib/tomcat7/webapps/ROOT##01/WEB-INF/gems/gems/activesupport-4.0.0.rc1/lib/active_support/key_generator.rb:1:in `(root)'
    from org/jruby/RubyKernel.java:1054:in `require'
    from /var/lib/tomcat7/webapps/ROOT##01/WEB-INF/gems/gems/activesupport-4.0.0.rc1/lib/active_support/key_generator.rb:2:in `(root)'
    from org/jruby/RubyKernel.java:1054:in `require'
    from /var/lib/tomcat7/webapps/ROOT##01/WEB-INF/gems/gems/railties-4.0.0.rc1/lib/rails/application.rb:1:in `(root)'
    from org/jruby/RubyKernel.java:1054:in `require'
    from /var/lib/tomcat7/webapps/ROOT##01/WEB-INF/gems/gems/railties-4.0.0.rc1/lib/rails/application.rb:3:in `(root)'
    from org/jruby/RubyKernel.java:1054:in `require'
    from /var/lib/tomcat7/webapps/ROOT##01/WEB-INF/gems/gems/railties-4.0.0.rc1/lib/rails.rb:1:in `(root)'
    from org/jruby/RubyKernel.java:1054:in `require'
    from /var/lib/tomcat7/webapps/ROOT##01/WEB-INF/gems/gems/railties-4.0.0.rc1/lib/rails.rb:9:in `(root)'
    from org/jruby/RubyKernel.java:1054:in `require'
    from /var/lib/tomcat7/webapps/ROOT##01/WEB-INF/gems/gems/railties-4.0.0.rc1/lib/rails/all.rb:1:in `(root)'
    from /var/lib/tomcat7/webapps/ROOT##01/WEB-INF/gems/gems/railties-4.0.0.rc1/lib/rails/all.rb:1:in `(root)'
    from /var/lib/tomcat7/webapps/ROOT##01/WEB-INF/config/application.rb:1:in `(root)'

    at org.jruby.rack.RackInitializationException.wrap(RackInitializationException.java:29)
    at org.jruby.rack.RackApplicationFactoryDecorator.init(RackApplicationFactoryDecorator.java:98)
    at org.jruby.rack.RackServletContextListener.contextInitialized(RackServletContextListener.java:50)
    at org.apache.catalina.core.StandardContext.listenerStart(StandardContext.java:4779)
    at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5273)
    at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:150)
    at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:895)
    at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:871)
    at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:615)
    at org.apache.catalina.startup.HostConfig.deployWAR(HostConfig.java:958)
    at org.apache.catalina.startup.HostConfig$DeployWar.run(HostConfig.java:1599)
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
    at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:334)
    at java.util.concurrent.FutureTask.run(FutureTask.java:166)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1146)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
    at java.lang.Thread.run(Thread.java:679)
Caused by: org.jruby.exceptions.RaiseException: (NameError) missing class or uppercase package name (`org.jruby.ext.openssl.OSSLLibrary')
    at org.jruby.javasupport.JavaUtilities.get_proxy_or_package_under_package(org/jruby/javasupport/JavaUtilities.java:54)
    at RUBY.method_missing(file:/var/lib/tomcat7/webapps/ROOT##01/WEB-INF/lib/gems-gems-jruby-jars-1.7.4-lib-jruby-core-1.7.4.jar!/jruby/java/java_package_module_template.rb:14)
    at RUBY.(root)(jar:file:/var/lib/tomcat7/webapps/ROOT%23%2301/WEB-INF/lib/gems-gems-jruby-jars-1.7.4-lib-jruby-stdlib-1.7.4.jar!/META-INF/jruby.home/lib/ruby/shared/openssl.rb:24)
    at org.jruby.RubyKernel.require(org/jruby/RubyKernel.java:1054)
    at RUBY.(root)(/var/lib/tomcat7/webapps/ROOT##01/WEB-INF/gems/gems/activesupport-4.0.0.rc1/lib/active_support/key_generator.rb:1)
    at org.jruby.RubyKernel.require(org/jruby/RubyKernel.java:1054)
    at RUBY.(root)(/var/lib/tomcat7/webapps/ROOT##01/WEB-INF/gems/gems/activesupport-4.0.0.rc1/lib/active_support/key_generator.rb:2)
    at org.jruby.RubyKernel.require(org/jruby/RubyKernel.java:1054)
    at RUBY.(root)(/var/lib/tomcat7/webapps/ROOT##01/WEB-INF/gems/gems/railties-4.0.0.rc1/lib/rails/application.rb:1)
    at org.jruby.RubyKernel.require(org/jruby/RubyKernel.java:1054)
    at RUBY.(root)(/var/lib/tomcat7/webapps/ROOT##01/WEB-INF/gems/gems/railties-4.0.0.rc1/lib/rails/application.rb:3)
    at org.jruby.RubyKernel.require(org/jruby/RubyKernel.java:1054)
    at RUBY.(root)(/var/lib/tomcat7/webapps/ROOT##01/WEB-INF/gems/gems/railties-4.0.0.rc1/lib/rails.rb:1)
    at org.jruby.RubyKernel.require(org/jruby/RubyKernel.java:1054)
    at RUBY.(root)(/var/lib/tomcat7/webapps/ROOT##01/WEB-INF/gems/gems/railties-4.0.0.rc1/lib/rails.rb:9)
    at org.jruby.RubyKernel.require(org/jruby/RubyKernel.java:1054)
    at RUBY.(root)(/var/lib/tomcat7/webapps/ROOT##01/WEB-INF/gems/gems/railties-4.0.0.rc1/lib/rails/all.rb:1)
    at RUBY.(root)(/var/lib/tomcat7/webapps/ROOT##01/WEB-INF/gems/gems/railties-4.0.0.rc1/lib/rails/all.rb:1)
    at RUBY.(root)(/var/lib/tomcat7/webapps/ROOT##01/WEB-INF/config/application.rb:1)
```
##

**Comment by otzy007** [comment]
Did anyone find a solution for this?
I'm still getting 
```
(NameError) missing class or uppercase package name (`org.jruby.ext.openssl.OSSLLibrary'), caused by (NameError) cannot load Java class org.jruby.ext.openssl.OSSLLibrary
```

**Comment by mkristian** [comment]
@otzy007 which jruby version are you using ? did you try jruby-9.0.0.0.pre2 ?

**Comment by otzy007** [comment]
I can confirm that with jruby 9000 pre2 it's working.
But not with 1.7.19.

Is 9000 production ready?

**Comment by mkristian** [comment]
well 9k definitely has more bugs then 1.7.x :)

you can  try the workaround from here: https://github.com/jruby/warbler/issues/266#issuecomment-71375233

which basically uses the same loading semantics as jruby-9k

**Comment by otzy007** [comment]
@jkutner tried with 1.7.20 but I have the same problem.
With 9k pre2 the input fields in forms get doubled :laughing: I'll figure it out later (Rails 3.2 + HAML).

@mkristian thank you for the workaround. Adding those lines to init.rb brings back the app.
For now I have a WEB-INF/init.rb file in my project that I'm adding to config.public_html list in warble.rb

**Comment by jkutner** [comment]
Can you try this on jruby 9.0.1.0?
