### ISSUE TITLE
Strange Java:: JavaLang::UnsatisfiedLinkError: on Windows, with old JDBC adapter

### ISSUE THREAD

**Issue by stefanpenner** [jruby/warbler#183]
Hey guys, sorry to drop a massive stack trace.

I have a small warbled jRuby Sinatra app, utilizing an older pervasive JDBC adapter.
It seems to work fine in all these environments unwarbled, but warbled it tends to throw the following stack trace on a subset of windows systems. I haven't quite found a pattern yet.

It is entirely possible I am merely trolling myself.

details:
jruby version: `jruby 1.7.4 (1.9.3p392) 2013-05-16 2390d3b`
warbler version: `1.3.8`

likely the relevant exurb:
``` 
Caused by: org.jruby.exceptions.RaiseException: (DatabaseConnectionError) Java::
JavaLang::UnsatisfiedLinkError: com.pervasive.jdbc.common.Utils.getTerminalSessionId()I
```

the trace: (partially truncated)
```
        from org.jruby.runtime.callsite.CachingCallSite.callIter(CachingCallSite.java:222)
        from config.test_database_connections.__file__(config/test_database_connections.rb:3)
        from config.test_database_connections.load(config/test_database_connections.rb)
        from org.jruby.Ruby.loadScript(Ruby.java:2757)
        from org.jruby.runtime.load.JavaCompiledScript.load(JavaCompiledScript.java:50)
        from org.jruby.runtime.load.LoadService.load(LoadService.java:359)
        from org.jruby.RubyKernel.loadCommon(RubyKernel.java:1081)
        from org.jruby.RubyKernel.load19(RubyKernel.java:1073)
        from org.jruby.RubyKernel$INVOKER$s$0$1$load19.call(RubyKernel$INVOKER$s$0$1$load19.gen)
        from org.jruby.internal.runtime.methods.DynamicMethod.call(DynamicMethod.java:209)
        from org.jruby.internal.runtime.methods.DynamicMethod.call(DynamicMethod.java:205)
        from org.jruby.runtime.callsite.CachingCallSite.cacheAndCall(CachingCallSite.java:326)
        from org.jruby.runtime.callsite.CachingCallSite.call(CachingCallSite.java:170)
        from org.jruby.ast.FCallOneArgNode.interpret(FCallOneArgNode.java:36)
        from org.jruby.ast.NewlineNode.interpret(NewlineNode.java:105)
        from org.jruby.ast.RootNode.interpret(RootNode.java:129)
        from org.jruby.evaluator.ASTInterpreter.INTERPRET_ROOT(ASTInterpreter.java:121)
        from org.jruby.Ruby.runInterpreter(Ruby.java:834)
        from org.jruby.Ruby.loadFile(Ruby.java:2674)
        from org.jruby.runtime.load.ExternalScript.load(ExternalScript.java:66)
        from org.jruby.runtime.load.LoadService.tryLoadingLibraryOrScript(LoadService.java:958)
        from org.jruby.runtime.load.LoadService.smartLoadInternal(LoadService.java:573)
        from org.jruby.runtime.load.LoadService.requireCommon(LoadService.java:457)
        from org.jruby.runtime.load.LoadService.require(LoadService.java:421)
        from org.jruby.RubyKernel.requireCommon(RubyKernel.java:1060)
        from org.jruby.RubyKernel.require19(RubyKernel.java:1054)
        from org.jruby.RubyKernel$INVOKER$s$1$0$require19.call(RubyKernel$INVOKER$s$1$0$require19.gen)
        from org.jruby.internal.runtime.methods.JavaMethod$JavaMethodOneOrNBlock.call(JavaMethod.java:347)
        from org.jruby.internal.runtime.methods.AliasMethod.call(AliasMethod.java:61)
        from org.jruby.internal.runtime.methods.AliasMethod.call(AliasMethod.java:61)
        from org.jruby.runtime.callsite.CachingCallSite.cacheAndCall(CachingCallSite.java:326)
        from org.jruby.runtime.callsite.CachingCallSite.call(CachingCallSite.java:170)
        from config.boot.__file__(config/boot.rb:54)
        from config.boot.load(config/boot.rb)
        from org.jruby.Ruby.loadScript(Ruby.java:2757)
        from org.jruby.runtime.load.JavaCompiledScript.load(JavaCompiledScript.java:50)
        from org.jruby.runtime.load.LoadService.load(LoadService.java:359)
        from org.jruby.RubyKernel.loadCommon(RubyKernel.java:1081)
        from org.jruby.RubyKernel.load19(RubyKernel.java:1073)
        from org.jruby.RubyKernel$INVOKER$s$0$1$load19.call(RubyKernel$INVOKER$s$0$1$load19.gen)
        from org.jruby.internal.runtime.methods.DynamicMethod.call(DynamicMethod.java:209)
        from org.jruby.internal.runtime.methods.DynamicMethod.call(DynamicMethod.java:205)
        from org.jruby.runtime.callsite.CachingCallSite.cacheAndCall(CachingCallSite.java:326)
        from org.jruby.runtime.callsite.CachingCallSite.call(CachingCallSite.java:170)
        from org.jruby.ast.FCallOneArgNode.interpret(FCallOneArgNode.java:36)
        from org.jruby.ast.NewlineNode.interpret(NewlineNode.java:105)
        from org.jruby.ast.RootNode.interpret(RootNode.java:129)
        from org.jruby.evaluator.ASTInterpreter.INTERPRET_ROOT(ASTInterpreter.java:121)
        from org.jruby.Ruby.runInterpreter(Ruby.java:834)
        from org.jruby.Ruby.loadFile(Ruby.java:2674)
        from org.jruby.runtime.load.ExternalScript.load(ExternalScript.java:66)
        from org.jruby.runtime.load.LoadService.tryLoadingLibraryOrScript(LoadService.java:958)
        from org.jruby.runtime.load.LoadService.smartLoadInternal(LoadService.java:573)
        from org.jruby.runtime.load.LoadService.requireCommon(LoadService.java:457)
        from org.jruby.runtime.load.LoadService.require(LoadService.java:421)
        from org.jruby.RubyKernel.requireCommon(RubyKernel.java:1060)
        from org.jruby.RubyKernel.require19(RubyKernel.java:1054)
        from org.jruby.RubyKernel$INVOKER$s$1$0$require19.call(RubyKernel$INVOKER$s$1$0$require19.gen)
        from org.jruby.internal.runtime.methods.JavaMethod$JavaMethodOneOrNBlock.call(JavaMethod.java:347)
        from org.jruby.internal.runtime.methods.AliasMethod.call(AliasMethod.java:61)
        from org.jruby.runtime.callsite.CachingCallSite.cacheAndCall(CachingCallSite.java:326)
        from org.jruby.runtime.callsite.CachingCallSite.call(CachingCallSite.java:170)
        from org.jruby.ast.FCallOneArgNode.interpret(FCallOneArgNode.java:36)
        from org.jruby.ast.NewlineNode.interpret(NewlineNode.java:105)
        from org.jruby.ast.IfNode.interpret(IfNode.java:116)
        from org.jruby.ast.NewlineNode.interpret(NewlineNode.java:105)
        from org.jruby.ast.RescueNode.executeBody(RescueNode.java:222)
        from org.jruby.ast.RescueNode.interpret(RescueNode.java:117)
        from org.jruby.evaluator.ASTInterpreter.INTERPRET_METHOD(ASTInterpreter.java:74)
        from org.jruby.internal.runtime.methods.InterpretedMethod.call(InterpretedMethod.java:182)
        from org.jruby.internal.runtime.methods.DefaultMethod.call(DefaultMethod.java:186)
        from org.jruby.runtime.callsite.CachingCallSite.cacheAndCall(CachingCallSite.java:326)
        from org.jruby.runtime.callsite.CachingCallSite.call(CachingCallSite.java:170)
        from org.jruby.ast.FCallOneArgNode.interpret(FCallOneArgNode.java:36)
        from org.jruby.ast.NewlineNode.interpret(NewlineNode.java:105)
        from org.jruby.ast.BlockNode.interpret(BlockNode.java:71)
        from org.jruby.ast.NewlineNode.interpret(NewlineNode.java:105)
        from org.jruby.evaluator.ASTInterpreter.INTERPRET_BLOCK(ASTInterpreter.java:112)
        from org.jruby.runtime.Interpreted19Block.evalBlockBody(Interpreted19Block.java:206)
        from org.jruby.runtime.Interpreted19Block.yield(Interpreted19Block.java:194)
        from org.jruby.runtime.Interpreted19Block.yield(Interpreted19Block.java:177)
        from org.jruby.runtime.Block.yieldNonArray(Block.java:153)
        from org.jruby.RubyBasicObject.yieldUnder(RubyBasicObject.java:1825)
        from org.jruby.RubyBasicObject.specificEval(RubyBasicObject.java:1849)
        from org.jruby.RubyBasicObject.instance_eval19(RubyBasicObject.java:1735
)
        from org.jruby.RubyBasicObject$INVOKER$i$instance_eval19.call(RubyBasicObject$INVOKER$i$instance_eval19.gen)
        from org.jruby.runtime.callsite.CachingCallSite.cacheAndCall(CachingCallSite.java:316)
        from org.jruby.runtime.callsite.CachingCallSite.callBlock(CachingCallSite.java:145)
        from org.jruby.runtime.callsite.CachingCallSite.call(CachingCallSite.java:149)
        from org.jruby.ast.FCallNoArgBlockPassNode.interpret(FCallNoArgBlockPassNode.java:27)
        from org.jruby.ast.IfNode.interpret(IfNode.java:116)
        from org.jruby.ast.NewlineNode.interpret(NewlineNode.java:105)
        from org.jruby.ast.BlockNode.interpret(BlockNode.java:71)
        from org.jruby.evaluator.ASTInterpreter.INTERPRET_METHOD(ASTInterpreter.java:74)
        from org.jruby.internal.runtime.methods.InterpretedMethod.call(InterpretedMethod.java:161)
        from org.jruby.internal.runtime.methods.DefaultMethod.call(DefaultMethod.java:178)
        from org.jruby.runtime.callsite.CachingCallSite.cacheAndCall(CachingCallSite.java:316)
        from org.jruby.runtime.callsite.CachingCallSite.callBlock(CachingCallSite.java:145)
        from org.jruby.runtime.callsite.CachingCallSite.call(CachingCallSite.java:149)
        from org.jruby.RubyClass.newInstance(RubyClass.java:848)
        from org.jruby.RubyClass$INVOKER$i$newInstance.call(RubyClass$INVOKER$i$newInstance.gen)
        from org.jruby.runtime.callsite.CachingCallSite.cacheAndCall(CachingCallSite.java:316)
        from org.jruby.runtime.callsite.CachingCallSite.callBlock(CachingCallSite.java:145)
        from org.jruby.runtime.callsite.CachingCallSite.callIter(CachingCallSite.java:154)
        from org.jruby.ast.CallNoArgBlockNode.interpret(CallNoArgBlockNode.java:64)
        from org.jruby.ast.CallNoArgNode.interpret(CallNoArgNode.java:60)
        from org.jruby.ast.CallOneArgNode.interpret(CallOneArgNode.java:57)
        from org.jruby.ast.NewlineNode.interpret(NewlineNode.java:105)
        from org.jruby.ast.RootNode.interpret(RootNode.java:129)
        from org.jruby.evaluator.ASTInterpreter.INTERPRET_ROOT(ASTInterpreter.java:121)
        from org.jruby.Ruby.runInterpreter(Ruby.java:834)
        from org.jruby.Ruby.runInterpreter(Ruby.java:842)
        from org.jruby.Ruby.executeScript(Ruby.java:449)
        from org.jruby.rack.DefaultRackApplicationFactory.createRackServletWrapper(DefaultRackApplicationFactory.java:236)
        from org.jruby.rack.DefaultRackApplicationFactory.createApplicationObject(DefaultRackApplicationFactory.java:165)
        from org.jruby.rack.DefaultRackApplicationFactory$1.create(DefaultRackApplicationFactory.java:98)
        from org.jruby.rack.DefaultRackApplicationFactory$RackApplicationImpl.init(DefaultRackApplicationFactory.java:420)
        from org.jruby.rack.DefaultRackApplicationFactory.getApplication(DefaultRackApplicationFactory.java:111)
        from org.jruby.rack.SharedRackApplicationFactory.doInit(SharedRackApplicationFactory.java:31)
        from org.jruby.rack.RackApplicationFactoryDecorator.init(RackApplicationFactoryDecorator.java:94)
        from org.jruby.rack.RackServletContextListener.contextInitialized(RackServletContextListener.java:50)
        from winstone.WebAppConfiguration.<init>(WebAppConfiguration.java:876)
        from winstone.HostConfiguration.initWebApp(HostConfiguration.java:129)
        from winstone.HostConfiguration.<init>(HostConfiguration.java:71)
        from winstone.HostGroup.initHost(HostGroup.java:87)
        from winstone.HostGroup.<init>(HostGroup.java:47)
        from winstone.Launcher.<init>(Launcher.java:177)
        from winstone.Launcher.main(Launcher.java:384)
        from sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        from sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
        from sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
        from java.lang.reflect.Method.invoke(Unknown Source)
        from WarMain.launchWebServer(WarMain.java:166)
        from WarMain.start(WarMain.java:318)
        from JarMain.doStart(JarMain.java:221)
        from WarMain.main(WarMain.java:341)

        at org.jruby.rack.RackInitializationException.wrap(RackInitializationException.java:29)
        at org.jruby.rack.RackApplicationFactoryDecorator.init(RackApplicationFactoryDecorator.java:98)
        at org.jruby.rack.RackServletContextListener.contextInitialized(RackServletContextListener.java:50)
        at winstone.WebAppConfiguration.<init>(WebAppConfiguration.java:876)
        at winstone.HostConfiguration.initWebApp(HostConfiguration.java:129)
        at winstone.HostConfiguration.<init>(HostConfiguration.java:71)
        at winstone.HostGroup.initHost(HostGroup.java:87)
        at winstone.HostGroup.<init>(HostGroup.java:47)
        at winstone.Launcher.<init>(Launcher.java:177)
        at winstone.Launcher.main(Launcher.java:384)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
        at java.lang.reflect.Method.invoke(Unknown Source)
        at WarMain.launchWebServer(WarMain.java:166)
        at WarMain.start(WarMain.java:318)
        at JarMain.doStart(JarMain.java:221)
        at WarMain.main(WarMain.java:341)
Caused by: org.jruby.exceptions.RaiseException: (DatabaseConnectionError) Java::
JavaLang::UnsatisfiedLinkError: com.pervasive.jdbc.common.Utils.getTerminalSessionId()I
        at RUBY.make_new(C:/Documents and Settings/pervasive/Local Settings/Temp/warbler4219435393400198183webroot/THEAPP.war/WEB-INF/gems/gems/sequel-4.2.0/lib/sequel/connection_pool.rb:99)
        at RUBY.make_new(C:/Documents and Settings/pervasive/Local Settings/Temp/warbler4219435393400198183webroot/THEAPP.war/WEB-INF/gems/gems/sequel-4.2.0/lib/sequel/connection_pool/threaded.rb:158)
        at RUBY.available(C:/Documents and Settings/pervasive/Local Settings/Temp/warbler4219435393400198183webroot/THEAPP.war/WEB-INF/gems/gems/sequel-4.2.0/lib/sequel/connection_pool/threaded.rb:137)
        at RUBY.acquire(C:/Documents and Settings/pervasive/Local Settings/Temp/warbler4219435393400198183webroot/THEAPP.war/WEB-INF/gems/gems/sequel-4.2.0/lib/sequel/connection_pool/threaded.rb:127)
        at RUBY.sync(C:/Documents and Settings/pervasive/Local Settings/Temp/warbler4219435393400198183webroot/THEAPP.war/WEB-INF/gems/gems/sequel-4.2.0/lib/sequel/connection_pool/threaded.rb:194)
        at org.jruby.ext.thread.Mutex.synchronize(org/jruby/ext/thread/Mutex.java:149)
        at RUBY.sync(C:/Documents and Settings/pervasive/Local Settings/Temp/warbler4219435393400198183webroot/THEAPP.war/WEB-INF/gems/gems/sequel-4.2.0/lib/sequel/connection_pool/threaded.rb:194)
        at RUBY.acquire(C:/Documents and Settings/pervasive/Local Settings/Temp/warbler4219435393400198183webroot/THEAPP.war/WEB-INF/gems/gems/sequel-4.2.0/lib/sequel/connection_pool/threaded.rb:126)
        at RUBY.hold(C:/Documents and Settings/pervasive/Local Settings/Temp/warbler4219435393400198183webroot/THEAPP.war/WEB-INF/gems/gems/sequel-4.2.0/lib/sequel/connection_pool/threaded.rb:94)
        at RUBY.synchronize(C:/Documents and Settings/pervasive/Local Settings/Temp/warbler4219435393400198183webroot/THEAPP.war/WEB-INF/gems/gems/sequel-4.2.0/lib/sequel/database/connecting.rb:234)
        at RUBY.metadata(C:/Documents and Settings/pervasive/Local Settings/Temp/warbler4219435393400198183webroot/THEAPP.war/WEB-INF/gems/gems/sequel-4.2.0/lib/sequel/adapters/jdbc.rb:504)
        at RUBY.tables(C:/Documents and Settings/pervasive/Local Settings/Temp/warbler4219435393400198183webroot/THEAPP.war/WEB-INF/gems/gems/sequel-jdbc-pervasive-adapter-0.1.0.rc1/lib/sequel/adapters/jdbc/pervasive.rb:33)
        at config.test_database_connections.(root)(config/test_database_connections.rb:6)
        at org.jruby.ext.timeout.Timeout.timeout(org/jruby/ext/timeout/Timeout.java:169)
        at config.test_database_connections.(root)(config/test_database_connections.rb:3)
        at org.jruby.RubyKernel.load(org/jruby/RubyKernel.java:1073)
        at RUBY.(root)(C:/Documents and Settings/pervasive/Local Settings/Temp/warbler4219435393400198183webroot/THEAPP.war/WEB-INF/config/test_database_connections.rb:1)
        at org.jruby.RubyKernel.require(org/jruby/RubyKernel.java:1054)
        at config.boot.(root)(config/boot.rb:54)
        at org.jruby.RubyKernel.load(org/jruby/RubyKernel.java:1073)
        at RUBY.(root)(C:/Documents and Settings/pervasive/Local Settings/Temp/warbler4219435393400198183webroot/THEAPP.war/WEB-INF/config/boot.rb:1)
        at org.jruby.RubyKernel.require(org/jruby/RubyKernel.java:1054)
        at RUBY.(root)(C:/Documents and Settings/pervasive/Local Settings/Temp/warbler4219435393400198183webroot/THEAPP.war/WEB-INF/config/boot.rb:1)
        at RUBY.(root)(jar:file:/C:/Documents%20and%20Settings/pervasive/Local%20Settings/Temp/warbler4219435393400198183webroot/THEAPP.war/WEB-INF/lib/gems-gems-jruby-jars-1.7.4-lib-jruby-stdlib-1.7.4.jar!/META-INF/jruby.home/lib/ruby/shared/rubygems/custom_require.rb:1)
        at org.jruby.RubyBasicObject.instance_eval(org/jruby/RubyBasicObject.java:1735)
        at RUBY.require(jar:file:/C:/Documents%20and%20Settings/pervasive/Local%20Settings/Temp/warbler4219435393400198183webroot/THEAPP.war/WEB-INF/lib/gems-gems-jruby-jars-1.7.4-lib-jruby-stdlib-1.7.4.jar!/META-INF/jruby.home/lib/ruby/shared/rubygems/custom_require.rb:36)
        at RUBY.(root)(C:\Documents and Settings\pervasive\Local Settings\Temp\warbler4219435393400198183webroot\THEAPP.war\WEB-INF\config.ru:1)
Sep 3, 2013 10:26:00 PM winstone.Logger logInternal
INFO: HTTP Listener started: port=8080
Sep 3, 2013 10:26:00 PM winstone.Logger logInternal
INFO: Winstone Servlet Engine v0.9.10 running: controlPort=disabled

```

**Comment by kares** [comment]
really an application specific issue ... something todo with class-loading in a Java web-app.
would maybe try putting all .jar files under WEB-INF/lib instead of requiring the driver from JRuby.
