### ISSUE TITLE
App fails to deploy on JDK 1.6.0_65 and 1.7.0_40-b43 using 

### ISSUE THREAD

**Issue by johntdyer** [jruby/warbler#237]
###### Startup logs

```log
014-02-06 22:32:59.097 DEBUG [Timer-4] #CONTAINER#: ApplicationImpl[_symbolicName=testing-0, _state=STARTED, ] will be reloaded due to watched file changed
2014-02-06 22:32:59.097 INFO  [Timer-4] #CONTAINER#: Unloading Application[testing]
2014-02-06 22:32:59.739 INFO  [Timer-4] #CONTAINER#: Unloaded Application[testing]
2014-02-06 22:32:59.740 INFO  [Timer-4] #CONTAINER#: Finalizing Application[testing]
2014-02-06 22:32:59.740 INFO  [Timer-4] #CONTAINER#: Finalized Application[testing]
2014-02-06 22:32:59.740 INFO  [Timer-4] #CONTAINER#: Detecting [/Users/jdyer/opt/voxeo/prism/apps/testing]...
2014-02-06 22:33:04.838 DEBUG [Timer-4] #CONTAINER#: Parsing application web.xml file at file:/Users/jdyer/opt/voxeo/prism/conf/web.xml
2014-02-06 22:33:04.855 DEBUG [Timer-4] #CONTAINER#: Parsing application sip.xml file at file:/Users/jdyer/opt/voxeo/prism/conf/sip.xml
2014-02-06 22:33:04.855 DEBUG [Timer-4] #CONTAINER#: Parsing application web.xml file at file:/Users/jdyer/opt/voxeo/prism/apps/testing/WEB-INF/web.xml
2014-02-06 22:33:04.858 INFO  [Timer-4] #CONTAINER#: No sip.xml: /Users/jdyer/opt/voxeo/prism/apps/testing/WEB-INF/sip.xml
2014-02-06 22:33:04.858 INFO  [Timer-4] #CONTAINER#: No xmpp.xml: /Users/jdyer/opt/voxeo/prism/conf/xmpp.xml
2014-02-06 22:33:04.859 INFO  [Timer-4] #CONTAINER#: No xmpp.xml: /Users/jdyer/opt/voxeo/prism/apps/testing/WEB-INF/xmpp.xml
2014-02-06 22:33:10.296 INFO  [Timer-4] #CONTAINER#: Detected Application[testing]
2014-02-06 22:33:10.296 INFO  [Timer-4] #CONTAINER#: Loading Application[testing]
2014-02-06 22:33:10.298 INFO  [Timer-4] #MRCP#: MrcpFactory loads initialization parameters[enable.rtsp.nio=true, mrcp.max.selector=1]
2014-02-06 22:33:10.299 DEBUG [Timer-4] #MRCP#: init thread pool [mrcp, 25, 2147483647]
2014-02-06 22:33:11.749 DEBUG [Timer-4] INFO: jruby 1.7.10 (1.9.3p392) 2014-01-09 c4ecd6b on Java HotSpot(TM) Server VM 1.6.0_65-b14-462-11M4609 [darwin-i386]
2014-02-06 22:33:11.751 DEBUG [Timer-4] INFO: using a shared (threadsafe!) runtime
2014-02-06 22:33:18.072 DEBUG [Timer-4] An exception happened during JRuby-Rack startup
no such file to load -- app/controllers/index
--- System
jruby 1.7.10 (1.9.3p392) 2014-01-09 c4ecd6b on Java HotSpot(TM) Server VM 1.6.0_65-b14-462-11M4609 [darwin-i386]
Time: 2014-02-06 22:33:18 -0500
Server: Voxeo Prism Application Server
jruby.home: file:/Users/jdyer/opt/voxeo/prism/apps/testing/WEB-INF/lib/gems-gems-jruby-jars-1.7.10-lib-jruby-stdlib-complete-1.7.10.jar!/META-INF/jruby.home

--- Context Init Parameters:
public.root = /
rack.env = production

--- Backtrace
LoadError: no such file to load -- app/controllers/index
                     require at org/jruby/RubyKernel.java:1083
                     require at jar:file:/Users/jdyer/opt/voxeo/prism/apps/testing/WEB-INF/lib/gems-gems-jruby-jars-1.7.10-lib-jruby-stdlib-complete-1.7.10.jar!/META-INF/jruby.home/lib/ruby/shared/rubygems/core_ext/kernel_require.rb:55
                     require at jar:file:/Users/jdyer/opt/voxeo/prism/apps/testing/WEB-INF/lib/gems-gems-jruby-jars-1.7.10-lib-jruby-stdlib-complete-1.7.10.jar!/META-INF/jruby.home/lib/ruby/shared/rubygems/core_ext/kernel_require.rb:53
  load_settings_from_init_rb at jndi:/container/testing/WEB-INF/init.rb:18
                        each at org/jruby/RubyArray.java:1613
  load_settings_from_init_rb at jndi:/container/testing/WEB-INF/init.rb:18
                        eval at org/jruby/RubyKernel.java:1119
  load_settings_from_init_rb at file:/Users/jdyer/opt/voxeo/prism/apps/testing/WEB-INF/lib/gems-gems-jruby-rack-1.1.13.3-lib-jruby-rack-1.1.13.3.jar!/jruby/rack/booter.rb:201
                        each at org/jruby/RubyArray.java:1613
  load_settings_from_init_rb at file:/Users/jdyer/opt/voxeo/prism/apps/testing/WEB-INF/lib/gems-gems-jruby-rack-1.1.13.3-lib-jruby-rack-1.1.13.3.jar!/jruby/rack/booter.rb:188
                       boot! at file:/Users/jdyer/opt/voxeo/prism/apps/testing/WEB-INF/lib/gems-gems-jruby-rack-1.1.13.3-lib-jruby-rack-1.1.13.3.jar!/jruby/rack/booter.rb:106
                      (root) at file:/Users/jdyer/opt/voxeo/prism/apps/testing/WEB-INF/lib/gems-gems-jruby-rack-1.1.13.3-lib-jruby-rack-1.1.13.3.jar!/jruby/rack/boot/rack.rb:10
                        load at org/jruby/RubyKernel.java:1099
                      (root) at <script>:1

--- RubyGems
Gem.dir: /Users/jdyer/opt/voxeo/prism/apps/testing/WEB-INF/gems
Gem.path:
/Users/jdyer/opt/voxeo/prism/apps/testing/WEB-INF/gems
Activated gems:
  rack-1.5.2
  tilt-1.4.1
  rack-protection-1.5.2
  sinatra-1.4.4

--- Bundler
undefined method `bundle_path' for Bundler:Module

--- JRuby-Rack Config
compat_version =
default_logger = org.jruby.rack.logging.StandardOutLogger@1ed232c
equals = <error: >
err = org.eclipse.virgo.medic.log.impl.LoggingPrintStreamWrapper@39305b
filter_adds_html = true
filter_verifies_resource = false
ignore_environment = false
initial_memory_buffer_size =
initial_runtimes =
jms_connection_factory =
jms_jndi_properties =
logger = org.jruby.rack.logging.ServletContextLogger@f1a69c
logger_class_name = servlet_context
logger_name = jruby.rack
maximum_memory_buffer_size =
maximum_runtimes =
num_initializer_threads =
out = org.eclipse.virgo.medic.log.impl.LoggingPrintStreamWrapper@a6f10f
rackup =
rackup_path =
rewindable = true
runtime_arguments =
runtime_environment =
runtime_timeout_seconds =
serial_initialization = false
servlet_context = com.micromethod.sipmethod.server.container.impl.ServletContextImpl@1c415b
throw_init_exception = false

--- $LOAD_PATH:
/Users/jdyer/opt/voxeo/prism/apps/testing/WEB-INF/gems/gems/rack-1.5.2/lib
/Users/jdyer/opt/voxeo/prism/apps/testing/WEB-INF/gems/gems/tilt-1.4.1/lib
/Users/jdyer/opt/voxeo/prism/apps/testing/WEB-INF/gems/gems/rack-protection-1.5.2/lib
/Users/jdyer/opt/voxeo/prism/apps/testing/WEB-INF/gems/gems/sinatra-1.4.4/lib
file:/Users/jdyer/opt/voxeo/prism/apps/testing/WEB-INF/lib/gems-gems-jruby-jars-1.7.10-lib-jruby-stdlib-complete-1.7.10.jar!/META-INF/jruby.home/lib/ruby/1.9/site_ruby
file:/Users/jdyer/opt/voxeo/prism/apps/testing/WEB-INF/lib/gems-gems-jruby-jars-1.7.10-lib-jruby-stdlib-complete-1.7.10.jar!/META-INF/jruby.home/lib/ruby/shared
file:/Users/jdyer/opt/voxeo/prism/apps/testing/WEB-INF/lib/gems-gems-jruby-jars-1.7.10-lib-jruby-stdlib-complete-1.7.10.jar!/META-INF/jruby.home/lib/ruby/1.9

2014-02-06 22:33:18.073 DEBUG [Timer-4] ERROR: initialization failed
org.jruby.rack.RackInitializationException: no such file to load -- app/controllers/index
	from org/jruby/RubyKernel.java:1083:in `require'
	from jar:file:/Users/jdyer/opt/voxeo/prism/apps/testing/WEB-INF/lib/gems-gems-jruby-jars-1.7.10-lib-jruby-stdlib-complete-1.7.10.jar!/META-INF/jruby.home/lib/ruby/shared/rubygems/core_ext/kernel_require.rb:55:in `require'
	from jar:file:/Users/jdyer/opt/voxeo/prism/apps/testing/WEB-INF/lib/gems-gems-jruby-jars-1.7.10-lib-jruby-stdlib-complete-1.7.10.jar!/META-INF/jruby.home/lib/ruby/shared/rubygems/core_ext/kernel_require.rb:53:in `require'
	from jndi:/container/testing/WEB-INF/init.rb:18:in `load_settings_from_init_rb'
	from org/jruby/RubyArray.java:1613:in `each'
	from jndi:/container/testing/WEB-INF/init.rb:18:in `load_settings_from_init_rb'
	from org/jruby/RubyKernel.java:1119:in `eval'
	from file:/Users/jdyer/opt/voxeo/prism/apps/testing/WEB-INF/lib/gems-gems-jruby-rack-1.1.13.3-lib-jruby-rack-1.1.13.3.jar!/jruby/rack/booter.rb:201:in `load_settings_from_init_rb'
	from org/jruby/RubyArray.java:1613:in `each'
	from file:/Users/jdyer/opt/voxeo/prism/apps/testing/WEB-INF/lib/gems-gems-jruby-rack-1.1.13.3-lib-jruby-rack-1.1.13.3.jar!/jruby/rack/booter.rb:188:in `load_settings_from_init_rb'
	from file:/Users/jdyer/opt/voxeo/prism/apps/testing/WEB-INF/lib/gems-gems-jruby-rack-1.1.13.3-lib-jruby-rack-1.1.13.3.jar!/jruby/rack/booter.rb:106:in `boot!'
	from file:/Users/jdyer/opt/voxeo/prism/apps/testing/WEB-INF/lib/gems-gems-jruby-rack-1.1.13.3-lib-jruby-rack-1.1.13.3.jar!/jruby/rack/boot/rack.rb:10:in `(root)'
	from org/jruby/RubyKernel.java:1099:in `load'
	from <script>:1:in `(root)'

	at org.jruby.rack.RackInitializationException.wrap(RackInitializationException.java:29)
	at org.jruby.rack.RackApplicationFactoryDecorator.init(RackApplicationFactoryDecorator.java:98)
	at org.jruby.rack.RackServletContextListener.contextInitialized(RackServletContextListener.java:50)
	at com.micromethod.sipmethod.server.container.impl.ApplicationSupport.handleEvent(ApplicationSupport.java:98)
	at com.micromethod.sipmethod.server.container.impl.ApplicationImpl.handleEvent(ApplicationImpl.java:645)
	at com.micromethod.sipmethod.server.container.impl.ApplicationDelegate.startListeners(ApplicationDelegate.java:247)
	at com.micromethod.sipmethod.server.container.impl.ApplicationImpl.start(ApplicationImpl.java:368)
	at com.micromethod.sipmethod.server.container.impl.ApplicationImpl.reload(ApplicationImpl.java:554)
	at com.micromethod.sipmethod.server.container.impl.ApplicationChangedListener.fileChanged(ApplicationChangedListener.java:41)
	at com.micromethod.common.util.scan.WatchRegexFileChangedScanner.fireEvent(WatchRegexFileChangedScanner.java:164)
	at com.micromethod.common.util.scan.WatchRegexFileChangedScanner.scan(WatchRegexFileChangedScanner.java:147)
	at com.micromethod.common.util.scan.WatchRegexFileChangedScanner$Scan.run(WatchRegexFileChangedScanner.java:204)
	at com.micromethod.common.util.TimerManager$TimerTaskWrapper.run(TimerManager.java:338)
	at java.util.TimerThread.mainLoop(Timer.java:512)
	at java.util.TimerThread.run(Timer.java:462)
Caused by: org.jruby.exceptions.RaiseException: (LoadError) no such file to load -- app/controllers/index
	at org.jruby.RubyKernel.require(org/jruby/RubyKernel.java:1083)
	at Kernel.require(jar:file:/Users/jdyer/opt/voxeo/prism/apps/testing/WEB-INF/lib/gems-gems-jruby-jars-1.7.10-lib-jruby-stdlib-complete-1.7.10.jar!/META-INF/jruby.home/lib/ruby/shared/rubygems/core_ext/kernel_require.rb:55)
	at Kernel.require(jar:file:/Users/jdyer/opt/voxeo/prism/apps/testing/WEB-INF/lib/gems-gems-jruby-jars-1.7.10-lib-jruby-stdlib-complete-1.7.10.jar!/META-INF/jruby.home/lib/ruby/shared/rubygems/core_ext/kernel_require.rb:53)
	at RUBY.load_settings_from_init_rb(jndi:/container/testing/WEB-INF/init.rb:18)
	at org.jruby.RubyArray.each(org/jruby/RubyArray.java:1613)
	at RUBY.load_settings_from_init_rb(jndi:/container/testing/WEB-INF/init.rb:18)
	at org.jruby.RubyKernel.eval(org/jruby/RubyKernel.java:1119)
	at RUBY.load_settings_from_init_rb(file:/Users/jdyer/opt/voxeo/prism/apps/testing/WEB-INF/lib/gems-gems-jruby-rack-1.1.13.3-lib-jruby-rack-1.1.13.3.jar!/jruby/rack/booter.rb:201)
	at org.jruby.RubyArray.each(org/jruby/RubyArray.java:1613)
	at RUBY.load_settings_from_init_rb(file:/Users/jdyer/opt/voxeo/prism/apps/testing/WEB-INF/lib/gems-gems-jruby-rack-1.1.13.3-lib-jruby-rack-1.1.13.3.jar!/jruby/rack/booter.rb:188)
	at RUBY.boot!(file:/Users/jdyer/opt/voxeo/prism/apps/testing/WEB-INF/lib/gems-gems-jruby-rack-1.1.13.3-lib-jruby-rack-1.1.13.3.jar!/jruby/rack/booter.rb:106)
	at RUBY.(root)(file:/Users/jdyer/opt/voxeo/prism/apps/testing/WEB-INF/lib/gems-gems-jruby-rack-1.1.13.3-lib-jruby-rack-1.1.13.3.jar!/jruby/rack/boot/rack.rb:10)
	at org.jruby.RubyKernel.load(org/jruby/RubyKernel.java:1099)
	at RUBY.(root)(<script>:1)
2014-02-06 22:33:18.369 INFO  [Timer-4] #CONTAINER#: Loaded Application[testing]

```

######  Config.ru

```ruby
# Require the necessary init.rb file
require 'init'

set :run, false
set :environment, :production

# deploy httpd server
run Sinatra::Application
```

######  init.rb
```ruby
# Require the necessary libraries.
require 'rubygems'
require 'sinatra'

# add controllers and views
configure do
  root = File.expand_path(File.dirname(__FILE__))
  set :views, File.join(root, 'app', 'views')
end

# Set the not found page for URIs that don't match to any specified route.
not_found do
  status 404
  erb :not_found
end

# Load the controllers.
Dir["app/controllers/*.rb"].each { |file| require file }
```

######  app/controllers/index.rb
```ruby
get '/' do
	erb :index
end
```

######  config/warble.rb

```ruby
Warbler::Config.new do |config|

  config.jar_name = "testing"

  config.dirs = %w(app config tmp)

  config.includes = FileList["init.rb"]
  config.gems += ["sinatra", "haml"]
  config.gems -= ["rails"]
  config.gem_dependencies = true
end
```

######  config/Gemfile.lock
```ruby 
GEM
  remote: https://rubygems.org/
  specs:
    haml (4.0.5)
      tilt
    jruby-jars (1.7.10)
    jruby-rack (1.1.13.3)
    rack (1.5.2)
    rack-protection (1.5.2)
      rack
    rake (10.1.1)
    rubyzip (1.0.0)
    sinatra (1.4.4)
      rack (~> 1.4)
      rack-protection (~> 1.4)
      tilt (~> 1.3, >= 1.3.4)
    tilt (1.4.1)
    warbler (1.4.0)
      jruby-jars (>= 1.5.6)
      jruby-rack (>= 1.0.0)
      rake (>= 0.9.6)
      rubyzip (>= 0.9, < 1.1)

PLATFORMS
  java

DEPENDENCIES
  haml
  rack
  sinatra
  warbler
```

**Comment by jkutner** [comment]
I couldn't reproduce this. If you still have the issue, please create a sample repo we can test against. Thanks.
