### ISSUE TITLE
JopensslService stream is null in Glassfish

### ISSUE THREAD

**Issue by btrepp** [jruby/warbler#266]
I'm trying to use a rails 4 application warified in glassfish, but it doesn't seem to work.

```
Exception loading extension `JopensslService`: java.lang.IllegalStateException: Stream handler unavailable due to: null from org/jruby/RubyKernel.java:1065:in `require' from classpath:/META-INF/jruby.home/lib/ruby/shared/jopenssl/load.rb:14:in `(root)' from org/jruby/RubyKernel.java:1065:in `require' from classpath:/META-INF/jruby.home/lib/ruby/shared/openssl.rb:1:in `(root)' from org/jruby/RubyKernel.java:1065:in `require' from classpath:/META-INF/jruby.home/lib/ruby/shared/openssl.rb:1:in `(root)' from org/jruby/RubyKernel.java:1065:in
```

Any ideas what's going on?. Operating system is windows, glassfish 4.0 and jdk7. It works fine in development (a different machine) running from a folder, but the war file doesn't work in glassfish.

I'm completely new to jruby, I usually hang out in the MRI world on linux with puma as a server, this was my attempt to get something 'windows' friendly.
##

**Comment by areman** [comment]
I have the same problem with glasfish 3.1 and jruby 1.7.18, 
but the "jruby-openssl", "~> 0.8.8" workaround didn't work for me. It seems open ssl included in jruby is used.
Has someone a solution ?

**Comment by mkristian** [comment]
@areman which OS ? windows ?

**Comment by areman** [comment]
No, I'm using ubuntu ( in an VMWare on Windows 7 )

**Comment by areman** [comment]
since jruby 1.7.x jopenssl is included in the jruby. why add a specific jopenssl version helps?

**Comment by mkristian** [comment]
if you provide me the log when you set the java system property
'jruby.debug.loadService' = 'true'
then I might be able help or even fix it on jruby side (or warbler side).

glassfish is one of the environments I never installed . . . .

to have such an old jruby-openssl gem not sure how well it works with
jruby-1.7.x

in past there were loads of issues with the jruby-openssl gem embedded into
jruby, there are still issue but less ;)

**Comment by areman** [comment]
I'm using jruby 1.7.18 without additional openssl jars. To force the problem I add a WEB-INF/init.rb file with an require 'jopenssl'

```
[#|2015-01-24T16:05:04.179+0100|SEVERE|glassfish3.1.2|javax.enterprise.system.std.com.sun.enterprise.server.logging|_ThreadID=97;_ThreadName=Thread-2;|2015-01-24T16:05:04.179+01:00: LoadService: trying builtinLib: jopenssl.rb|#]

[#|2015-01-24T16:05:04.180+0100|SEVERE|glassfish3.1.2|javax.enterprise.system.std.com.sun.enterprise.server.logging|_ThreadID=97;_ThreadName=Thread-2;|2015-01-24T16:05:04.180+01:00: LoadService: trying fileResource: /home/amos/sample/common/modules/platform/amos_qt/jopenssl.rb|#]

[#|2015-01-24T16:05:04.181+0100|SEVERE|glassfish3.1.2|javax.enterprise.system.std.com.sun.enterprise.server.logging|_ThreadID=97;_ThreadName=Thread-2;|2015-01-24T16:05:04.181+01:00: LoadService: trying fileResource: classpath:/META-INF/jruby.home/lib/ruby/1.9/site_ruby/jopenssl.rb|#]

[#|2015-01-24T16:05:04.183+0100|SEVERE|glassfish3.1.2|javax.enterprise.system.std.com.sun.enterprise.server.logging|_ThreadID=97;_ThreadName=Thread-2;|2015-01-24T16:05:04.183+01:00: LoadService: trying fileResource: classpath:/META-INF/jruby.home/lib/ruby/shared/jopenssl.rb|#]

[#|2015-01-24T16:05:04.185+0100|SEVERE|glassfish3.1.2|javax.enterprise.system.std.com.sun.enterprise.server.logging|_ThreadID=97;_ThreadName=Thread-2;|2015-01-24T16:05:04.185+01:00: LoadService: trying fileResource: classpath:/META-INF/jruby.home/lib/ruby/1.9/jopenssl.rb|#]

[#|2015-01-24T16:05:04.187+0100|SEVERE|glassfish3.1.2|javax.enterprise.system.std.com.sun.enterprise.server.logging|_ThreadID=97;_ThreadName=Thread-2;|2015-01-24T16:05:04.187+01:00: LoadService: trying jarExtension: jopenssl|#]

[#|2015-01-24T16:05:04.188+0100|SEVERE|glassfish3.1.2|javax.enterprise.system.std.com.sun.enterprise.server.logging|_ThreadID=97;_ThreadName=Thread-2;|2015-01-24T16:05:04.188+01:00: LoadService: trying builtinLib: jopenssl.class|#]

[#|2015-01-24T16:05:04.189+0100|SEVERE|glassfish3.1.2|javax.enterprise.system.std.com.sun.enterprise.server.logging|_ThreadID=97;_ThreadName=Thread-2;|2015-01-24T16:05:04.189+01:00: LoadService: trying fileResource: /home/amos/sample/common/modules/platform/amos_qt/jopenssl.class|#]

[#|2015-01-24T16:05:04.189+0100|SEVERE|glassfish3.1.2|javax.enterprise.system.std.com.sun.enterprise.server.logging|_ThreadID=97;_ThreadName=Thread-2;|2015-01-24T16:05:04.189+01:00: LoadService: trying fileResource: classpath:/META-INF/jruby.home/lib/ruby/1.9/site_ruby/jopenssl.class|#]

[#|2015-01-24T16:05:04.192+0100|SEVERE|glassfish3.1.2|javax.enterprise.system.std.com.sun.enterprise.server.logging|_ThreadID=97;_ThreadName=Thread-2;|2015-01-24T16:05:04.191+01:00: LoadService: trying fileResource: classpath:/META-INF/jruby.home/lib/ruby/shared/jopenssl.class|#]

[#|2015-01-24T16:05:04.193+0100|SEVERE|glassfish3.1.2|javax.enterprise.system.std.com.sun.enterprise.server.logging|_ThreadID=97;_ThreadName=Thread-2;|2015-01-24T16:05:04.193+01:00: LoadService: trying fileResource: classpath:/META-INF/jruby.home/lib/ruby/1.9/jopenssl.class|#]

[#|2015-01-24T16:05:04.195+0100|SEVERE|glassfish3.1.2|javax.enterprise.system.std.com.sun.enterprise.server.logging|_ThreadID=97;_ThreadName=Thread-2;|2015-01-24T16:05:04.195+01:00: LoadService: trying builtinLib: jopenssl.jar|#]

[#|2015-01-24T16:05:04.196+0100|SEVERE|glassfish3.1.2|javax.enterprise.system.std.com.sun.enterprise.server.logging|_ThreadID=97;_ThreadName=Thread-2;|2015-01-24T16:05:04.195+01:00: LoadService: trying fileResource: /home/amos/sample/common/modules/platform/amos_qt/jopenssl.jar|#]

[#|2015-01-24T16:05:04.196+0100|SEVERE|glassfish3.1.2|javax.enterprise.system.std.com.sun.enterprise.server.logging|_ThreadID=97;_ThreadName=Thread-2;|2015-01-24T16:05:04.196+01:00: LoadService: trying fileResource: classpath:/META-INF/jruby.home/lib/ruby/1.9/site_ruby/jopenssl.jar|#]

[#|2015-01-24T16:05:04.198+0100|SEVERE|glassfish3.1.2|javax.enterprise.system.std.com.sun.enterprise.server.logging|_ThreadID=97;_ThreadName=Thread-2;|2015-01-24T16:05:04.198+01:00: LoadService: trying fileResource: classpath:/META-INF/jruby.home/lib/ruby/shared/jopenssl.jar|#]

[#|2015-01-24T16:05:04.206+0100|SEVERE|glassfish3.1.2|javax.enterprise.system.std.com.sun.enterprise.server.logging|_ThreadID=97;_ThreadName=Thread-2;|2015-01-24T16:05:04.206+01:00: LoadService: found fileResource: classpath:/META-INF/jruby.home/lib/ruby/shared/jopenssl.jar|#]

[#|2015-01-24T16:05:04.257+0100|SEVERE|glassfish3.1.2|javax.enterprise.system.std.com.sun.enterprise.server.logging|_ThreadID=97;_ThreadName=Thread-2;|java.lang.IllegalStateException: Stream handler unavailable due to: null
	at org.apache.felix.framework.URLHandlersStreamHandlerProxy.openConnection(URLHandlersStreamHandlerProxy.java:311)
	at java.net.URL.openConnection(URL.java:971)
	at sun.misc.URLClassPath$JarLoader.getJarFile(URLClassPath.java:722)
	at sun.misc.URLClassPath$JarLoader.access$600(URLClassPath.java:591)
	at sun.misc.URLClassPath$JarLoader$1.run(URLClassPath.java:673)
	at sun.misc.URLClassPath$JarLoader$1.run(URLClassPath.java:666)
	at java.security.AccessController.doPrivileged(Native Method)
	at sun.misc.URLClassPath$JarLoader.ensureOpen(URLClassPath.java:665)
	at sun.misc.URLClassPath$JarLoader.<init>(URLClassPath.java:616)
	at sun.misc.URLClassPath$3.run(URLClassPath.java:366)
	at sun.misc.URLClassPath$3.run(URLClassPath.java:356)
	at java.security.AccessController.doPrivileged(Native Method)
	at sun.misc.URLClassPath.getLoader(URLClassPath.java:355)
	at sun.misc.URLClassPath.getLoader(URLClassPath.java:332)
	at sun.misc.URLClassPath.findResource(URLClassPath.java:175)
	at java.net.URLClassLoader$2.run(URLClassLoader.java:551)
	at java.net.URLClassLoader$2.run(URLClassLoader.java:549)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findResource(URLClassLoader.java:548)
	at org.jruby.util.JRubyClassLoader.findResource(JRubyClassLoader.java:228)
	at java.lang.ClassLoader.getResource(ClassLoader.java:1139)
	at org.jruby.runtime.load.ClassExtensionLibrary.tryServiceLoad(ClassExtensionLibrary.java:148)
´´´

**Comment by mkristian** [comment]
this gives more inside. is glassfish using an osgi container under the hood ? at least they use the felix framework their stream-handlers.

could you prepend
```
$LOAD.unshift 'uri:classloader:/META-INF/jruby.home/lib/ruby/shared'
```
before requiring openssl. the 'uri:classloader:' does work with felix so there is a chance this solves the glassfish probelm as well.

**Comment by areman** [comment]
Yes it seems to work !! My tests are running.
I added a WEB-INF/init.rb file
with the content
```
$LOAD_PATH.unshift 'uri:classloader:/META-INF/jruby.home/lib/ruby/shared'
require 'jopenssl'
```
Thank you !!

**Comment by mkristian** [comment]
cool - since this is default for jruby-9k it good to hear that it removes
those problems ;)

**Comment by renaldi1982** [comment]
@areman 

I'm having the same problem, please bear with me as this is my first time using Jruby, rails, warbler and glassfish together. My goal is just to have jruby hello world running on glassfish and i opted using warbler since v4 does not have jruby on glassfish anymore.

So here's what I did, 
1. create rails application - rails new hello
2. added gem 'jruby-openssl' to Gemfile
3. do bundle install
4. warble -> created hello.war
5. deploy hello.war
6. getting the same error as yours.
7. trying added applications/hello/WEB-INF/init.rb with content
$LOAD_PATH.unshift 'uri:classloader:/META-INF/jruby.home/lib/ruby/shared'
require 'jopenssl'
8. Still getting the same error

What am i missing? is there any steps I need to add before creating hello.war?
I did not get any error during creating the .war file or on deployment.

Thanks in advance for your assistance.

**Comment by mkristian** [comment]
jruby comes with jruby-openssl gem bundles there is no need of adding this
on the Gemfile. try the same thing without the jruby-openssl gem !

did you try jruby-9.0.0.0.pre2 ? which would not need the WEB-INF/init.rb
workaround

**Comment by renaldi1982** [comment]
@mkristian 

I apologize I failed to mention my setup.
Here goes:
JRuby-1.7.19 - installed as multi-users (I'm not sure if this matters or not)
Glassfish 4.1
Ubuntu 14.04 on VPS

First try I just created new rails project and generate controller and a view for the controller followed by creating the .war file, and I did not have jruby-openssl in Gemfile and it generates the same error. Then I added jruby-openssl -> same error. Try to add WEB-INF/init.rb and still getting the same error. . 

I will try JRuby 9k and report back. Thank you kristian.

**Comment by renaldi1982** [comment]
Another update.

Tried with jruby-1.7.20 and still nada 
So now I have 3 installation of jruby namely 1.7.19, 1.7.20 and 9.0.0.0.pre 2 all managed by RVM. 

I tried run:
warble executable war
java -jar hello.war

it worked fine. 

But I want it to deploy it with glassfish since I already have my other Applications run in glassfish(PHP, AngularJS, JSF)

**Comment by mkristian** [comment]
well, rvm is setting GEM_HOME which can interfere with java application running jruby unless they explicitly set GEM_HOME to point to standard GEM_HOME from jruby or the "gems" folder of you application.

your stacktrace looks as it is when you did not have WEB-INF/init.rb with the LOAD_PATH fix

I downloaded glassfish4.1 and try to reproduce your problem on my side but for some reason the domain does not start up :(

so you could you do the same as I asked here: https://github.com/jruby/warbler/issues/266#issuecomment-71319808
to set the system property 'jruby.debug.loadService=true'

**Comment by mkristian** [comment]
@renaldi1982 what I did:

created file ./config/warbler.rb
```
Warbler::Config.new do |config|
  config.includes = FileList["init.rb"]
end
```
and ./init.rb inside the rails root directory
```
$LOAD_PATH.unshift 'uri:classloader:/META-INF/jruby.home/lib/ruby/shared'
```

this removed the initial error I did see regarding jopenssl.

**Comment by renaldi1982** [comment]
Thanks Kristian, I will try to add that and report back here.

**Comment by cshupp1** [comment]
I have experienced the exact same issue.  Given that open ssl is now part of JRuby I experienced the same error (on glassfish) that everyone else did but I seem to have found a much simpler fix.  Without doing any of the other stuff I simply added JRuby's complete jar to the domain's extension directorys, so in (my case):

C:\work\ETS\glassfish\glassfish4\glassfish\domains\domain1\lib\ext

I added the following jar file:

jruby-complete-9.0.4.0.jar

And that is it!
