### ISSUE TITLE
rails 3 app war file fails in jetty 7.3

### ISSUE THREAD

**Issue by tc** [jruby/warbler#28]
I gem install warbler on my mac os x 10.6 and ruby 1.9.2-p180.

I was able to warble my rails 3 application, but when I put the war file in the webapps dir, it fails:
Any ideas?

$2011-05-03 23:33:40.300:INFO::Deployable added: /usr/local/jetty-distribution-7.3.0.v20110203/webapps/researchwatch-web.war
2011-05-03 23:33:40.303:INFO::Extract jar:file:/usr/local/jetty-distribution-7.3.0.v20110203/webapps/researchwatch-web.war!/ to /private/var/folders/Le/LeI6Y06KG-qmFa40j48SDU+++TI/-Tmp-/jetty-0.0.0.0-8983-researchwatch-web.war-_researchwatch-web-any-/webapp
2011-05-03 23:33:44.034:INFO:researchwatch-web:Warning: no max runtimes specified.
2011-05-03 23:33:44.117:INFO:researchwatch-web:jruby 1.6.1 (ruby-1.8.7-p330) (2011-04-12 85838f6) (Java HotSpot(TM) 64-Bit Server VM 1.6.0_24) [darwin-x86_64-java]
2011-05-03 23:33:44.117:INFO:researchwatch-web:Info: using runtime pool timeout of 30 seconds
2011-05-03 23:33:44.117:INFO:researchwatch-web:Warning: no min runtimes specified.
2011-05-03 23:33:44.117:INFO:researchwatch-web:Warning: no max runtimes specified.
2011-05-03 23:33:44.117:INFO::started o.e.j.w.WebAppContext{/researchwatch-web,file:/private/var/folders/Le/LeI6Y06KG-qmFa40j48SDU+++TI/-Tmp-/jetty-0.0.0.0-8983-researchwatch-web.war-_researchwatch-web-any-/webapp/},/usr/local/jetty-distribution-7.3.0.v20110203/webapps/researchwatch-web.war
Could not find abstract-1.0.0 in any of the sources
2011-05-03 23:34:06.174:WARN:researchwatch-web:Application Error
org.jruby.rack.RackInitializationException: exit|?from org/jruby/RubyKernel.java:836:in `exit'|?from /usr/local/Cellar/ruby/1.9.2-p180/lib/ruby/gems/1.9.1/gems/bundler-1.0.10/lib/bundler/setup.rb:10:in `(root)'|
	at org.jruby.rack.DefaultRackApplicationFactory.initializeContainer(DefaultRackApplicationFactory.java:192)
	at org.jruby.rack.DefaultRackApplicationFactory.newContainer(DefaultRackApplicationFactory.java:200)
	at org.jruby.rack.DefaultRackApplicationFactory.createApplication(DefaultRackApplicationFactory.java:216)
	at org.jruby.rack.DefaultRackApplicationFactory.newApplication(DefaultRackApplicationFactory.java:48)
	at org.jruby.rack.DefaultRackApplicationFactory.getApplication(DefaultRackApplicationFactory.java:56)
	at org.jruby.rack.PoolingRackApplicationFactory.getApplication(PoolingRackApplicationFactory.java:95)
	at org.jruby.rack.DefaultRackDispatcher.process(DefaultRackDispatcher.java:28)
	at org.jruby.rack.RackFilter.doFilter(RackFilter.java:58)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1323)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:474)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:119)
	at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:480)
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:226)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:935)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:404)
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:184)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:870)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:117)
	at org.eclipse.jetty.server.handler.ContextHandlerCollection.handle(ContextHandlerCollection.java:247)
	at org.eclipse.jetty.server.handler.HandlerCollection.handle(HandlerCollection.java:151)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:116)
	at org.eclipse.jetty.server.Server.handle(Server.java:346)
	at org.eclipse.jetty.server.HttpConnection.handleRequest(HttpConnection.java:596)
	at org.eclipse.jetty.server.HttpConnection$RequestHandler.headerComplete(HttpConnection.java:1051)
	at org.eclipse.jetty.http.HttpParser.parseNext(HttpParser.java:592)
	at org.eclipse.jetty.http.HttpParser.parseAvailable(HttpParser.java:214)
	at org.eclipse.jetty.server.HttpConnection.handle(HttpConnection.java:426)
	at org.eclipse.jetty.io.nio.SelectChannelEndPoint.handle(SelectChannelEndPoint.java:520)
	at org.eclipse.jetty.io.nio.SelectChannelEndPoint$1.run(SelectChannelEndPoint.java:40)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:528)
	at java.lang.Thread.run(Thread.java:680)
Caused by: 
org.jruby.exceptions.RaiseException: (SystemExit) exit
	at org.jruby.RubyKernel.exit(org/jruby/RubyKernel.java:867)
	at org.jruby.RubyKernel.exit(org/jruby/RubyKernel.java:836)
	at #<Class:0x14eb98fe1>.(root)(/usr/local/Cellar/ruby/1.9.2-p180/lib/ruby/gems/1.9.1/gems/bundler-1.0.10/lib/bundler/setup.rb:10)

**Comment by kares** [comment]
old Bundler gem resolution issue - no longer relevant under JRuby 1.7 ... let us know otherwise, thx!
