### ISSUE TITLE
Compilation FAILED

### ISSUE THREAD

**Issue by mehmetdavut** [jruby/warbler#287]
I am getting Compilation FAILED errors when trying to compile rails project. It happens time to time, when i update some other gems or warble. How can i become sure to warble will work? Which development requirements should i have?

My system is like that:
***$ javac -version***
javac 1.8.0_20

***$ ruby -v***
jruby 1.7.12 (1.9.3p392) 2014-04-15 643e292 on Java HotSpot(TM) 64-Bit Server VM 1.8.0_20-b26 +indy [darwin-x86_64]

***$ rails -v***
Rails 4.0.2

***$ warble --version***
Warbler version 1.4.4

And full trace is like that:

***$ warble --trace***
```
Sep 08, 2014 5:05:52 PM sun.reflect.NativeMethodAccessorImpl invoke0
INFO: Using Ehcache version 2.4.6
** Invoke default (first_time)
** Invoke war (first_time)
** Execute war
** Invoke war:compiled (first_time)
** Execute war:compiled
Failure during compilation of file vendor/bundle/jruby/1.9/gems/actionmailer-4.0.2/lib/rails/generators/mailer/templates/mailer.rb:
vendor/bundle/jruby/1.9/gems/actionmailer-4.0.2/lib/rails/generators/mailer/templates/mailer.rb:1: syntax error, unexpected tLT
<% module_namespacing do -%>
 ^
/Users/mehmetdavut/.rvm/gems/jruby-1.7.12/gems/jruby-jars-1.7.15/lib/jruby-stdlib-complete-1.7.15.jar!/META-INF/jruby.home/lib/ruby/shared/jruby/compiler.rb:135:in `compile_files_with_options'
org/jruby/RubyProc.java:271:in `call'
/Users/mehmetdavut/.rvm/gems/jruby-1.7.12/gems/jruby-jars-1.7.15/lib/jruby-stdlib-complete-1.7.15.jar!/META-INF/jruby.home/lib/ruby/shared/jruby/compiler.rb:214:in `compile_files_with_options'
org/jruby/RubyArray.java:1613:in `each'
/Users/mehmetdavut/.rvm/gems/jruby-1.7.12/gems/jruby-jars-1.7.15/lib/jruby-stdlib-complete-1.7.15.jar!/META-INF/jruby.home/lib/ruby/shared/jruby/compiler.rb:198:in `compile_files_with_options'
/Users/mehmetdavut/.rvm/gems/jruby-1.7.12/gems/jruby-jars-1.7.15/lib/jruby-stdlib-complete-1.7.15.jar!/META-INF/jruby.home/lib/ruby/shared/jruby/compiler.rb:90:in `compile_argv'
/Users/mehmetdavut/.rvm/gems/jruby-1.7.12/gems/jruby-jars-1.7.15/lib/jruby-stdlib-complete-1.7.15.jar!/META-INF/jruby.home/bin/jrubyc:5:in `(root)'
org/jruby/RubyKernel.java:1081:in `load'
file:/Users/mehmetdavut/.rvm/gems/jruby-1.7.12/gems/jruby-jars-1.7.15/lib/jruby-core-complete-1.7.15.jar!/jruby/commands.rb:1:in `(root)'
jrubyc:1:in `(root)'
Failure during compilation of file vendor/bundle/jruby/1.9/gems/activerecord-4.0.2/lib/rails/generators/active_record/migration/templates/create_table_migration.rb:
vendor/bundle/jruby/1.9/gems/activerecord-4.0.2/lib/rails/generators/active_record/migration/templates/create_table_migration.rb:1: syntax error, unexpected tLT
class <%= migration_class_name %> < ActiveRecord::Migration
       ^
/Users/mehmetdavut/.rvm/gems/jruby-1.7.12/gems/jruby-jars-1.7.15/lib/jruby-stdlib-complete-1.7.15.jar!/META-INF/jruby.home/lib/ruby/shared/jruby/compiler.rb:135:in `compile_files_with_options'
org/jruby/RubyProc.java:271:in `call'
/Users/mehmetdavut/.rvm/gems/jruby-1.7.12/gems/jruby-jars-1.7.15/lib/jruby-stdlib-complete-1.7.15.jar!/META-INF/jruby.home/lib/ruby/shared/jruby/compiler.rb:214:in `compile_files_with_options'
org/jruby/RubyArray.java:1613:in `each'
/Users/mehmetdavut/.rvm/gems/jruby-1.7.12/gems/jruby-jars-1.7.15/lib/jruby-stdlib-complete-1.7.15.jar!/META-INF/jruby.home/lib/ruby/shared/jruby/compiler.rb:198:in `compile_files_with_options'
/Users/mehmetdavut/.rvm/gems/jruby-1.7.12/gems/jruby-jars-1.7.15/lib/jruby-stdlib-complete-1.7.15.jar!/META-INF/jruby.home/lib/ruby/shared/jruby/compiler.rb:90:in `compile_argv'
/Users/mehmetdavut/.rvm/gems/jruby-1.7.12/gems/jruby-jars-1.7.15/lib/jruby-stdlib-complete-1.7.15.jar!/META-INF/jruby.home/bin/jrubyc:5:in `(root)'
org/jruby/RubyKernel.java:1081:in `load'
file:/Users/mehmetdavut/.rvm/gems/jruby-1.7.12/gems/jruby-jars-1.7.15/lib/jruby-core-complete-1.7.15.jar!/jruby/commands.rb:1:in `(root)'
jrubyc:1:in `(root)'
Failure during compilation of file vendor/bundle/jruby/1.9/gems/activerecord-4.0.2/lib/rails/generators/active_record/migration/templates/migration.rb:
vendor/bundle/jruby/1.9/gems/activerecord-4.0.2/lib/rails/generators/active_record/migration/templates/migration.rb:1: syntax error, unexpected tLT
class <%= migration_class_name %> < ActiveRecord::Migration
       ^
/Users/mehmetdavut/.rvm/gems/jruby-1.7.12/gems/jruby-jars-1.7.15/lib/jruby-stdlib-complete-1.7.15.jar!/META-INF/jruby.home/lib/ruby/shared/jruby/compiler.rb:135:in `compile_files_with_options'
org/jruby/RubyProc.java:271:in `call'
/Users/mehmetdavut/.rvm/gems/jruby-1.7.12/gems/jruby-jars-1.7.15/lib/jruby-stdlib-complete-1.7.15.jar!/META-INF/jruby.home/lib/ruby/shared/jruby/compiler.rb:214:in `compile_files_with_options'
org/jruby/RubyArray.java:1613:in `each'
/Users/mehmetdavut/.rvm/gems/jruby-1.7.12/gems/jruby-jars-1.7.15/lib/jruby-stdlib-complete-1.7.15.jar!/META-INF/jruby.home/lib/ruby/shared/jruby/compiler.rb:198:in `compile_files_with_options'
/Users/mehmetdavut/.rvm/gems/jruby-1.7.12/gems/jruby-jars-1.7.15/lib/jruby-stdlib-complete-1.7.15.jar!/META-INF/jruby.home/lib/ruby/shared/jruby/compiler.rb:90:in `compile_argv'
/Users/mehmetdavut/.rvm/gems/jruby-1.7.12/gems/jruby-jars-1.7.15/lib/jruby-stdlib-complete-1.7.15.jar!/META-INF/jruby.home/bin/jrubyc:5:in `(root)'
org/jruby/RubyKernel.java:1081:in `load'
file:/Users/mehmetdavut/.rvm/gems/jruby-1.7.12/gems/jruby-jars-1.7.15/lib/jruby-core-complete-1.7.15.jar!/jruby/commands.rb:1:in `(root)'
jrubyc:1:in `(root)'
Failure during compilation of file vendor/bundle/jruby/1.9/gems/activerecord-4.0.2/lib/rails/generators/active_record/model/templates/model.rb:
vendor/bundle/jruby/1.9/gems/activerecord-4.0.2/lib/rails/generators/active_record/model/templates/model.rb:1: syntax error, unexpected tLT
<% module_namespacing do -%>
 ^
/Users/mehmetdavut/.rvm/gems/jruby-1.7.12/gems/jruby-jars-1.7.15/lib/jruby-stdlib-complete-1.7.15.jar!/META-INF/jruby.home/lib/ruby/shared/jruby/compiler.rb:135:in `compile_files_with_options'
org/jruby/RubyProc.java:271:in `call'
/Users/mehmetdavut/.rvm/gems/jruby-1.7.12/gems/jruby-jars-1.7.15/lib/jruby-stdlib-complete-1.7.15.jar!/META-INF/jruby.home/lib/ruby/shared/jruby/compiler.rb:214:in `compile_files_with_options'
org/jruby/RubyArray.java:1613:in `each'
/Users/mehmetdavut/.rvm/gems/jruby-1.7.12/gems/jruby-jars-1.7.15/lib/jruby-stdlib-complete-1.7.15.jar!/META-INF/jruby.home/lib/ruby/shared/jruby/compiler.rb:198:in `compile_files_with_options'
/Users/mehmetdavut/.rvm/gems/jruby-1.7.12/gems/jruby-jars-1.7.15/lib/jruby-stdlib-complete-1.7.15.jar!/META-INF/jruby.home/lib/ruby/shared/jruby/compiler.rb:90:in `compile_argv'
/Users/mehmetdavut/.rvm/gems/jruby-1.7.12/gems/jruby-jars-1.7.15/lib/jruby-stdlib-complete-1.7.15.jar!/META-INF/jruby.home/bin/jrubyc:5:in `(root)'
org/jruby/RubyKernel.java:1081:in `load'
file:/Users/mehmetdavut/.rvm/gems/jruby-1.7.12/gems/jruby-jars-1.7.15/lib/jruby-core-complete-1.7.15.jar!/jruby/commands.rb:1:in `(root)'
jrubyc:1:in `(root)'
Failure during compilation of file vendor/bundle/jruby/1.9/gems/activerecord-4.0.2/lib/rails/generators/active_record/model/templates/module.rb:
vendor/bundle/jruby/1.9/gems/activerecord-4.0.2/lib/rails/generators/active_record/model/templates/module.rb:1: syntax error, unexpected tLT
<% module_namespacing do -%>
 ^
/Users/mehmetdavut/.rvm/gems/jruby-1.7.12/gems/jruby-jars-1.7.15/lib/jruby-stdlib-complete-1.7.15.jar!/META-INF/jruby.home/lib/ruby/shared/jruby/compiler.rb:135:in `compile_files_with_options'
org/jruby/RubyProc.java:271:in `call'
/Users/mehmetdavut/.rvm/gems/jruby-1.7.12/gems/jruby-jars-1.7.15/lib/jruby-stdlib-complete-1.7.15.jar!/META-INF/jruby.home/lib/ruby/shared/jruby/compiler.rb:214:in `compile_files_with_options'
org/jruby/RubyArray.java:1613:in `each'
/Users/mehmetdavut/.rvm/gems/jruby-1.7.12/gems/jruby-jars-1.7.15/lib/jruby-stdlib-complete-1.7.15.jar!/META-INF/jruby.home/lib/ruby/shared/jruby/compiler.rb:198:in `compile_files_with_options'
/Users/mehmetdavut/.rvm/gems/jruby-1.7.12/gems/jruby-jars-1.7.15/lib/jruby-stdlib-complete-1.7.15.jar!/META-INF/jruby.home/lib/ruby/shared/jruby/compiler.rb:90:in `compile_argv'
/Users/mehmetdavut/.rvm/gems/jruby-1.7.12/gems/jruby-jars-1.7.15/lib/jruby-stdlib-complete-1.7.15.jar!/META-INF/jruby.home/bin/jrubyc:5:in `(root)'
org/jruby/RubyKernel.java:1081:in `load'
file:/Users/mehmetdavut/.rvm/gems/jruby-1.7.12/gems/jruby-jars-1.7.15/lib/jruby-core-complete-1.7.15.jar!/jruby/commands.rb:1:in `(root)'
jrubyc:1:in `(root)'
Failure during compilation of file vendor/bundle/jruby/1.9/gems/builder-3.1.4/test/performance.rb:
vendor/bundle/jruby/1.9/gems/builder-3.1.4/test/performance.rb:16: invalid multibyte char (US-ASCII)
/Users/mehmetdavut/.rvm/gems/jruby-1.7.12/gems/jruby-jars-1.7.15/lib/jruby-stdlib-complete-1.7.15.jar!/META-INF/jruby.home/lib/ruby/shared/jruby/compiler.rb:135:in `compile_files_with_options'
org/jruby/RubyProc.java:271:in `call'
/Users/mehmetdavut/.rvm/gems/jruby-1.7.12/gems/jruby-jars-1.7.15/lib/jruby-stdlib-complete-1.7.15.jar!/META-INF/jruby.home/lib/ruby/shared/jruby/compiler.rb:214:in `compile_files_with_options'
org/jruby/RubyArray.java:1613:in `each'
/Users/mehmetdavut/.rvm/gems/jruby-1.7.12/gems/jruby-jars-1.7.15/lib/jruby-stdlib-complete-1.7.15.jar!/META-INF/jruby.home/lib/ruby/shared/jruby/compiler.rb:198:in `compile_files_with_options'
/Users/mehmetdavut/.rvm/gems/jruby-1.7.12/gems/jruby-jars-1.7.15/lib/jruby-stdlib-complete-1.7.15.jar!/META-INF/jruby.home/lib/ruby/shared/jruby/compiler.rb:90:in `compile_argv'
/Users/mehmetdavut/.rvm/gems/jruby-1.7.12/gems/jruby-jars-1.7.15/lib/jruby-stdlib-complete-1.7.15.jar!/META-INF/jruby.home/bin/jrubyc:5:in `(root)'
org/jruby/RubyKernel.java:1081:in `load'
file:/Users/mehmetdavut/.rvm/gems/jruby-1.7.12/gems/jruby-jars-1.7.15/lib/jruby-core-complete-1.7.15.jar!/jruby/commands.rb:1:in `(root)'
jrubyc:1:in `(root)'
Failure during compilation of file vendor/bundle/jruby/1.9/gems/carrierwave-0.9.0/lib/generators/templates/uploader.rb:
vendor/bundle/jruby/1.9/gems/carrierwave-0.9.0/lib/generators/templates/uploader.rb:3: syntax error, unexpected tLT
class <%= class_name %>Uploader < CarrierWave::Uploader::Base
       ^
/Users/mehmetdavut/.rvm/gems/jruby-1.7.12/gems/jruby-jars-1.7.15/lib/jruby-stdlib-complete-1.7.15.jar!/META-INF/jruby.home/lib/ruby/shared/jruby/compiler.rb:135:in `compile_files_with_options'
org/jruby/RubyProc.java:271:in `call'
/Users/mehmetdavut/.rvm/gems/jruby-1.7.12/gems/jruby-jars-1.7.15/lib/jruby-stdlib-complete-1.7.15.jar!/META-INF/jruby.home/lib/ruby/shared/jruby/compiler.rb:214:in `compile_files_with_options'
org/jruby/RubyArray.java:1613:in `each'
/Users/mehmetdavut/.rvm/gems/jruby-1.7.12/gems/jruby-jars-1.7.15/lib/jruby-stdlib-complete-1.7.15.jar!/META-INF/jruby.home/lib/ruby/shared/jruby/compiler.rb:198:in `compile_files_with_options'
/Users/mehmetdavut/.rvm/gems/jruby-1.7.12/gems/jruby-jars-1.7.15/lib/jruby-stdlib-complete-1.7.15.jar!/META-INF/jruby.home/lib/ruby/shared/jruby/compiler.rb:90:in `compile_argv'
/Users/mehmetdavut/.rvm/gems/jruby-1.7.12/gems/jruby-jars-1.7.15/lib/jruby-stdlib-complete-1.7.15.jar!/META-INF/jruby.home/bin/jrubyc:5:in `(root)'
org/jruby/RubyKernel.java:1081:in `load'
file:/Users/mehmetdavut/.rvm/gems/jruby-1.7.12/gems/jruby-jars-1.7.15/lib/jruby-core-complete-1.7.15.jar!/jruby/commands.rb:1:in `(root)'
jrubyc:1:in `(root)'
Compilation FAILED: 7 error(s) encountered
warble aborted!
Compile failed
/Users/mehmetdavut/.rvm/gems/jruby-1.7.12/gems/warbler-1.4.4/lib/warbler/jar.rb:70:in `run_javac'
org/jruby/RubyArray.java:1653:in `each_slice'
/Users/mehmetdavut/.rvm/gems/jruby-1.7.12/gems/rake-10.3.2/lib/rake/file_list.rb:81:in `each_slice'
/Users/mehmetdavut/.rvm/gems/jruby-1.7.12/gems/warbler-1.4.4/lib/warbler/jar.rb:62:in `run_javac'
/Users/mehmetdavut/.rvm/gems/jruby-1.7.12/gems/warbler-1.4.4/lib/warbler/jar.rb:50:in `compile'
/Users/mehmetdavut/.rvm/gems/jruby-1.7.12/gems/warbler-1.4.4/lib/warbler/task.rb:109:in `define_compiled_task'
org/jruby/RubyProc.java:271:in `call'
/Users/mehmetdavut/.rvm/gems/jruby-1.7.12/gems/rake-10.3.2/lib/rake/task.rb:240:in `execute'
org/jruby/RubyArray.java:1613:in `each'
/Users/mehmetdavut/.rvm/gems/jruby-1.7.12/gems/rake-10.3.2/lib/rake/task.rb:235:in `execute'
/Users/mehmetdavut/.rvm/gems/jruby-1.7.12/gems/rake-10.3.2/lib/rake/task.rb:179:in `invoke_with_call_chain'
/Users/mehmetdavut/.rvm/rubies/jruby-1.7.12/lib/ruby/1.9/monitor.rb:211:in `mon_synchronize'
/Users/mehmetdavut/.rvm/gems/jruby-1.7.12/gems/rake-10.3.2/lib/rake/task.rb:172:in `invoke_with_call_chain'
/Users/mehmetdavut/.rvm/gems/jruby-1.7.12/gems/rake-10.3.2/lib/rake/task.rb:165:in `invoke'
/Users/mehmetdavut/.rvm/gems/jruby-1.7.12/gems/warbler-1.4.4/lib/warbler/task.rb:88:in `define_main_task'
org/jruby/RubyArray.java:1613:in `each'
/Users/mehmetdavut/.rvm/gems/jruby-1.7.12/gems/warbler-1.4.4/lib/warbler/task.rb:82:in `define_main_task'
org/jruby/RubyProc.java:271:in `call'
/Users/mehmetdavut/.rvm/gems/jruby-1.7.12/gems/rake-10.3.2/lib/rake/task.rb:240:in `execute'
org/jruby/RubyArray.java:1613:in `each'
/Users/mehmetdavut/.rvm/gems/jruby-1.7.12/gems/rake-10.3.2/lib/rake/task.rb:235:in `execute'
/Users/mehmetdavut/.rvm/gems/jruby-1.7.12/gems/rake-10.3.2/lib/rake/task.rb:179:in `invoke_with_call_chain'
/Users/mehmetdavut/.rvm/rubies/jruby-1.7.12/lib/ruby/1.9/monitor.rb:211:in `mon_synchronize'
/Users/mehmetdavut/.rvm/gems/jruby-1.7.12/gems/rake-10.3.2/lib/rake/task.rb:172:in `invoke_with_call_chain'
/Users/mehmetdavut/.rvm/gems/jruby-1.7.12/gems/rake-10.3.2/lib/rake/task.rb:201:in `invoke_prerequisites'
org/jruby/RubyArray.java:1613:in `each'
/Users/mehmetdavut/.rvm/gems/jruby-1.7.12/gems/rake-10.3.2/lib/rake/task.rb:199:in `invoke_prerequisites'
/Users/mehmetdavut/.rvm/gems/jruby-1.7.12/gems/rake-10.3.2/lib/rake/task.rb:178:in `invoke_with_call_chain'
/Users/mehmetdavut/.rvm/rubies/jruby-1.7.12/lib/ruby/1.9/monitor.rb:211:in `mon_synchronize'
/Users/mehmetdavut/.rvm/gems/jruby-1.7.12/gems/rake-10.3.2/lib/rake/task.rb:172:in `invoke_with_call_chain'
/Users/mehmetdavut/.rvm/gems/jruby-1.7.12/gems/rake-10.3.2/lib/rake/task.rb:165:in `invoke'
/Users/mehmetdavut/.rvm/gems/jruby-1.7.12/gems/rake-10.3.2/lib/rake/application.rb:150:in `invoke_task'
/Users/mehmetdavut/.rvm/gems/jruby-1.7.12/gems/rake-10.3.2/lib/rake/application.rb:106:in `top_level'
org/jruby/RubyArray.java:1613:in `each'
/Users/mehmetdavut/.rvm/gems/jruby-1.7.12/gems/rake-10.3.2/lib/rake/application.rb:106:in `top_level'
/Users/mehmetdavut/.rvm/gems/jruby-1.7.12/gems/rake-10.3.2/lib/rake/application.rb:115:in `run_with_threads'
/Users/mehmetdavut/.rvm/gems/jruby-1.7.12/gems/rake-10.3.2/lib/rake/application.rb:100:in `top_level'
/Users/mehmetdavut/.rvm/gems/jruby-1.7.12/gems/rake-10.3.2/lib/rake/application.rb:78:in `run'
/Users/mehmetdavut/.rvm/gems/jruby-1.7.12/gems/rake-10.3.2/lib/rake/application.rb:176:in `standard_exception_handling'
/Users/mehmetdavut/.rvm/gems/jruby-1.7.12/gems/rake-10.3.2/lib/rake/application.rb:75:in `run'
/Users/mehmetdavut/.rvm/gems/jruby-1.7.12/gems/warbler-1.4.4/lib/warbler/application.rb:77:in `run'
/Users/mehmetdavut/.rvm/gems/jruby-1.7.12/gems/warbler-1.4.4/bin/warble:11:in `(root)'
org/jruby/RubyKernel.java:1081:in `load'
/Users/mehmetdavut/.rvm/gems/jruby-1.7.12/bin/warble:1:in `(root)'
org/jruby/RubyKernel.java:1101:in `eval'
/Users/mehmetdavut/.rvm/gems/jruby-1.7.12/bin/jruby_executable_hooks:15:in `(root)'
Tasks: TOP => war:compiled
```

**Comment by kares** [comment]
actually, hit this as well while having vendor-bundled with `bundle install --deployment` ... same old thing - mailer from Rails gem except now at 4.2.5.1. I believe Warbler is doing the correct thing (and its good to have the flexibility of easily pre-compiling gems besides application .rb files as well) by default so I might try to escalate this at Rails.

**Comment by kares** [comment]
reported at Rails https://github.com/rails/rails/issues/23847 and seems they're willing to rename those template files. there's already a PR which renamed the relevant ones (should get into Rails 5 - in the mean-time - filtering by hand it is).

**Comment by jkutner** [comment]
@kares wow, nice work
