### ISSUE TITLE
no such file to load -- bundler/setup

### ISSUE THREAD

**Issue by joedaniels29** [jruby/warbler#303]
I've seen other posts about similar issues, but as they are for a previous release i figured i would make a new issue. when warbling with warbler (v 1.4.4) and deploying onto glassfish, I'm getting the following error

```
ERROR: initialization failed
org.jruby.rack.RackInitializationException: no such file to load -- bundler/setup
```

I've tried using bundle install with and without the  `--depoloyment` flag set. This is for a rails 4 project. 

Any ideas?
##

**Comment by mkristian** [comment]
could you run glassfish with ```-Djruby.debug.laodService=true``` and post the output ? this would give more info on what is going on and maybe a remedy.

**Comment by joedaniels29** [comment]
So, I was able to get around this by specifying `config.webxml.jruby.compat.version = "1.9"` in my warble.rb and setting jruby-jars to the latest version, where jruby-jars 1.6.x before (`gem 'jruby-jars', '=1.7.16` ) 

Since my Ruby interpreter is the latest Jruby release, I had thought I didn't need to set the language version because 1.9 was default in 1.7.x, but I guess because the gemfile's jruby-jars version is what matters here and not my rvm installed interpreter?

Though I'm curious where I would append that option? system wide JAVA_OPTS or JRUBY_OPTS or perhaps in the asadmin command like this guide suggests? http://docs.oracle.com/cd/E19798-01/821-1751/ggnes/index.html

If I may, though, now I have an even more strange error:
```
ERROR: initialization failed
org.jruby.rack.RackInitializationException: unable to load readline subsystem: missing class or uppercase package name (`org.jruby.ext.readline.ReadlineService'), caused by (NameError) cannot load Java class org.jruby.ext.readline.ReadlineService
        from org/jruby/javasupport/JavaUtilities.java:54:in `get_proxy_or_package_under_package'
        from file:/Users/josephdaniels/Projects/Work/glassfish4/glassfish/domains/domain1/applications/resident-worklist.war.1/WEB-INF/lib/jruby-core-1.7.18.jar!/jruby/java/java_package_module_template.rb:14:in `method_missing'
        from /Users/josephdaniels/Projects/Work/glassfish4/glassfish/domains/domain1/applications/resident-worklist.war.1/WEB-INF/lib/jruby-stdlib-1.7.18.jar!/META-INF/jruby.home/lib/ruby/shared/readline.rb:11:in `(root)'
        from org/jruby/RubyKernel.java:1071:in `require'
        from /Users/josephdaniels/Projects/Work/glassfish4/glassfish/domains/domain1/applications/resident-worklist.war.1/WEB-INF/gems/gems/activesupport-4.1.2/lib/active_support/dependencies.rb:247:in `require'
        from /Users/josephdaniels/Projects/Work/glassfish4/glassfish/domains/domain1/applications/resident-worklist.war.1/WEB-INF/gems/gems/activesupport-4.1.2/lib/active_support/dependencies.rb:232:in `load_dependency'
        from /Users/josephdaniels/Projects/Work/glassfish4/glassfish/domains/domain1/applications/resident-worklist.war.1/WEB-INF/gems/gems/activesupport-4.1.2/lib/active_support/dependencies.rb:247:in `require'
        from /Users/josephdaniels/Projects/Work/glassfish4/glassfish/domains/domain1/applications/resident-worklist.war.1/WEB-INF/gems/gems/thor-0.19.1/lib/thor/line_editor/readline.rb:1:in `(root)'
        from org/jruby/RubyKernel.java:1071:in `require'
```
is it better to open another issue?

**Comment by mkristian** [comment]
the request on more debugging output - the oracle guide looks the way to go.

I think both "issues" are related, something goes wrong with the LoadService

**Comment by joedaniels29** [comment]
I enabled the option in Glassfish's asadmin, rebooted glassfish and saw the Param show up in the Glassfish JVM options gui; though I didn't see anything in the logs that gave away that the param was passed through the to the app. Anyways, here's the GF log starting from about where the Error occurred:
```

[2015-01-15T14:11:28.438-0500] [glassfish 4.1] [INFO] [] [javax.enterprise.web] [tid: _ThreadID=63 _ThreadName=JRuby-Rack-App-Init-0] [timeMillis: 1421349088438] [levelValue: 800] [[
  WebModule[null] ServletContext.log():An exception happened during JRuby-Rack startup
unable to load readline subsystem: missing class or uppercase package name (`org.jruby.ext.readline.ReadlineService'), caused by (NameError) cannot load Java class org.jruby.ext.readline.ReadlineService
--- System
jruby 1.7.16 (1.9.3p392) 2014-09-25 575b395 on Java HotSpot(TM) 64-Bit Server VM 1.7.0_40-b43 +jit [darwin-x86_64]
Time: 2015-01-15 14:11:28 -0500
Server: GlassFish Server Open Source Edition  4.1 
jruby.home: file:/Users/josephdaniels/Projects/Work/glassfish4/glassfish/domains/domain1/applications/resident-worklist.war.1/WEB-INF/lib/jruby-stdlib-complete-1.7.16.jar!/META-INF/jruby.home

--- Context Init Parameters:
com.sun.faces.forceLoadConfiguration = true
com.sun.faces.validateXml = true
jruby.compat.version = 1.9
jruby.max.runtimes = 10
jruby.min.runtimes = 2
public.root = /
rails.env = production

--- Backtrace
NameError: unable to load readline subsystem: missing class or uppercase package name (`org.jruby.ext.readline.ReadlineService'), caused by (NameError) cannot load Java class org.jruby.ext.readline.ReadlineService

--- RubyGems
Gem.dir: /Users/josephdaniels/Projects/Work/glassfish4/glassfish/domains/domain1/applications/resident-worklist.war.1/WEB-INF/gems
Gem.path:
/Users/josephdaniels/Projects/Work/glassfish4/glassfish/domains/domain1/applications/resident-worklist.war.1/WEB-INF/gems
/Users/josephdaniels/.rvm/gems/ruby-2.1.2
/Users/josephdaniels/.rvm/gems/ruby-2.1.2@global
Activated gems:
  bundler-1.7.12
  rake-10.4.2
  i18n-0.7.0
  json-1.8.2-java
  minitest-5.5.1
  thread_safe-0.3.4-java
  tzinfo-1.2.2
  activesupport-4.1.2
  builder-3.2.2
  erubis-2.7.0
  actionview-4.1.2
  rack-1.5.2
  rack-test-0.6.3
  actionpack-4.1.2
  mime-types-1.25.1
  polyglot-0.3.5
  treetop-1.4.15
  mail-2.5.4
  actionmailer-4.1.2
  activemodel-4.1.2
  active_model_serializers-0.9.2
  arel-5.0.1.20140414130214
  activerecord-4.1.2
  bouncy-castle-java-1.5.0147
  nokogiri-1.6.5-java
  xpath-2.0.0
  capybara-2.4.4
  hike-1.2.3
  thor-0.19.1
  railties-4.1.2
  jquery-rails-3.1.2
  jruby-jars-1.7.16
  jruby-openssl-0.8.10
  jruby-rack-1.1.18
  multi_json-1.10.1
  nifty-generators-0.4.6
  tilt-1.4.1
  sprockets-2.12.3
  sprockets-rails-2.2.2
  rails-4.1.2
  rubyzip-0.9.9
  ruby-ole-1.2.11.8
  spreadsheet-1.0.0
  roo-1.13.2
  warbler-1.4.4
  trelawney-0.0.17

--- Bundler
Bundler.bundle_path: /Users/josephdaniels/Projects/Work/glassfish4/glassfish/domains/domain1/applications/resident-worklist.war.1/WEB-INF/gems
Bundler.root: /Users/josephdaniels/Projects/Work/glassfish4/glassfish/domains/domain1/applications/resident-worklist.war.1/WEB-INF
Gemfile: /Users/josephdaniels/Projects/Work/glassfish4/glassfish/domains/domain1/applications/resident-worklist.war.1/WEB-INF/Gemfile
Settings:
  jobs = 7
  gemfile = /Users/josephdaniels/Projects/Work/glassfish4/glassfish/domains/domain1/applications/resident-worklist.war.1/WEB-INF/Gemfile
  without = development:test:assets
  frozen = true
  bin_path = /Users/josephdaniels/Projects/Work/glassfish4/glassfish/domains/domain1/applications/resident-worklist.war.1/WEB-INF/gems/gems/bundler-1.7.12/bin/bundle

--- JRuby-Rack Config
compat_version = RUBY1_9
default_logger = org.jruby.rack.logging.StandardOutLogger@25f3a4af
equals = <error: 32512>
err = com.sun.common.util.logging.LoggingOutputStream$LoggingPrintStream@41835abf
filter_adds_html = true
filter_verifies_resource = false
ignore_environment = false
initial_memory_buffer_size = 
initial_runtimes = 2
jms_connection_factory = 
jms_jndi_properties = 
logger = org.jruby.rack.logging.ServletContextLogger@65fa83a6
logger_class_name = servlet_context
logger_name = jruby.rack
maximum_memory_buffer_size = 
maximum_runtimes = 10
num_initializer_threads = 
out = com.sun.common.util.logging.LoggingOutputStream$LoggingPrintStream@21d93b98
rackup = 
rackup_path = 
rewindable = true
runtime_arguments = 
runtime_environment = 
runtime_timeout_seconds = 
serial_initialization = false
servlet_context = org.apache.catalina.core.ApplicationContextFacade@5e6d3656
throw_init_exception = false
]]

[2015-01-15T14:11:28.438-0500] [glassfish 4.1] [INFO] [] [javax.enterprise.web] [tid: _ThreadID=64 _ThreadName=JRuby-Rack-App-Init-1] [timeMillis: 1421349088438] [levelValue: 800] [[
  WebModule[null] ServletContext.log():An exception happened during JRuby-Rack startup
unable to load readline subsystem: missing class or uppercase package name (`org.jruby.ext.readline.ReadlineService'), caused by (NameError) cannot load Java class org.jruby.ext.readline.ReadlineService
--- System
jruby 1.7.16 (1.9.3p392) 2014-09-25 575b395 on Java HotSpot(TM) 64-Bit Server VM 1.7.0_40-b43 +jit [darwin-x86_64]
Time: 2015-01-15 14:11:28 -0500
Server: GlassFish Server Open Source Edition  4.1 
jruby.home: file:/Users/josephdaniels/Projects/Work/glassfish4/glassfish/domains/domain1/applications/resident-worklist.war.1/WEB-INF/lib/jruby-stdlib-complete-1.7.16.jar!/META-INF/jruby.home

--- Context Init Parameters:
com.sun.faces.forceLoadConfiguration = true
com.sun.faces.validateXml = true
jruby.compat.version = 1.9
jruby.max.runtimes = 10
jruby.min.runtimes = 2
public.root = /
rails.env = production

--- Backtrace
NameError: unable to load readline subsystem: missing class or uppercase package name (`org.jruby.ext.readline.ReadlineService'), caused by (NameError) cannot load Java class org.jruby.ext.readline.ReadlineService

--- RubyGems
Gem.dir: /Users/josephdaniels/Projects/Work/glassfish4/glassfish/domains/domain1/applications/resident-worklist.war.1/WEB-INF/gems
Gem.path:
/Users/josephdaniels/Projects/Work/glassfish4/glassfish/domains/domain1/applications/resident-worklist.war.1/WEB-INF/gems
/Users/josephdaniels/.rvm/gems/ruby-2.1.2
/Users/josephdaniels/.rvm/gems/ruby-2.1.2@global
Activated gems:
  bundler-1.7.12
  rake-10.4.2
  i18n-0.7.0
  json-1.8.2-java
  minitest-5.5.1
  thread_safe-0.3.4-java
  tzinfo-1.2.2
  activesupport-4.1.2
  builder-3.2.2
  erubis-2.7.0
  actionview-4.1.2
  rack-1.5.2
  rack-test-0.6.3
  actionpack-4.1.2
  mime-types-1.25.1
  polyglot-0.3.5
  treetop-1.4.15
  mail-2.5.4
  actionmailer-4.1.2
  activemodel-4.1.2
  active_model_serializers-0.9.2
  arel-5.0.1.20140414130214
  activerecord-4.1.2
  bouncy-castle-java-1.5.0147
  nokogiri-1.6.5-java
  xpath-2.0.0
  capybara-2.4.4
  hike-1.2.3
  thor-0.19.1
  railties-4.1.2
  jquery-rails-3.1.2
  jruby-jars-1.7.16
  jruby-openssl-0.8.10
  jruby-rack-1.1.18
  multi_json-1.10.1
  nifty-generators-0.4.6
  tilt-1.4.1
  sprockets-2.12.3
  sprockets-rails-2.2.2
  rails-4.1.2
  rubyzip-0.9.9
  ruby-ole-1.2.11.8
  spreadsheet-1.0.0
  roo-1.13.2
  warbler-1.4.4
  trelawney-0.0.17

--- Bundler
Bundler.bundle_path: /Users/josephdaniels/Projects/Work/glassfish4/glassfish/domains/domain1/applications/resident-worklist.war.1/WEB-INF/gems
Bundler.root: /Users/josephdaniels/Projects/Work/glassfish4/glassfish/domains/domain1/applications/resident-worklist.war.1/WEB-INF
Gemfile: /Users/josephdaniels/Projects/Work/glassfish4/glassfish/domains/domain1/applications/resident-worklist.war.1/WEB-INF/Gemfile
Settings:
  jobs = 7
  gemfile = /Users/josephdaniels/Projects/Work/glassfish4/glassfish/domains/domain1/applications/resident-worklist.war.1/WEB-INF/Gemfile
  without = development:test:assets
  frozen = true
  bin_path = /Users/josephdaniels/Projects/Work/glassfish4/glassfish/domains/domain1/applications/resident-worklist.war.1/WEB-INF/gems/gems/bundler-1.7.12/bin/bundle

--- JRuby-Rack Config
compat_version = RUBY1_9
default_logger = org.jruby.rack.logging.StandardOutLogger@1ba5db97
equals = <error: 32512>
err = com.sun.common.util.logging.LoggingOutputStream$LoggingPrintStream@41835abf
filter_adds_html = true
filter_verifies_resource = false
ignore_environment = false
initial_memory_buffer_size = 
initial_runtimes = 2
jms_connection_factory = 
jms_jndi_properties = 
logger = org.jruby.rack.logging.ServletContextLogger@65fa83a6
logger_class_name = servlet_context
logger_name = jruby.rack
maximum_memory_buffer_size = 
maximum_runtimes = 10
num_initializer_threads = 
out = com.sun.common.util.logging.LoggingOutputStream$LoggingPrintStream@21d93b98
rackup = 
rackup_path = 
rewindable = true
runtime_arguments = 
runtime_environment = 
runtime_timeout_seconds = 
serial_initialization = false
servlet_context = org.apache.catalina.core.ApplicationContextFacade@5e6d3656
throw_init_exception = false
]]

[2015-01-15T14:11:28.439-0500] [glassfish 4.1] [SEVERE] [] [javax.enterprise.web] [tid: _ThreadID=63 _ThreadName=JRuby-Rack-App-Init-0] [timeMillis: 1421349088439] [levelValue: 1000] [[
  WebModule[/resident-worklist]ERROR: unable to initialize application
org.jruby.exceptions.RaiseException: (NameError) unable to load readline subsystem: missing class or uppercase package name (`org.jruby.ext.readline.ReadlineService'), caused by (NameError) cannot load Java class org.jruby.ext.readline.ReadlineService
]]

[2015-01-15T14:11:28.439-0500] [glassfish 4.1] [INFO] [] [javax.enterprise.web] [tid: _ThreadID=63 _ThreadName=JRuby-Rack-App-Init-0] [timeMillis: 1421349088439] [levelValue: 800] [[
  WebModule[null] ServletContext.log():INFO: added application to pool, size now = 1]]

[2015-01-15T14:11:28.440-0500] [glassfish 4.1] [INFO] [] [javax.enterprise.web] [tid: _ThreadID=64 _ThreadName=JRuby-Rack-App-Init-1] [timeMillis: 1421349088440] [levelValue: 800] [[
  WebModule[null] ServletContext.log():INFO: added application to pool, size now = 2]]

[2015-01-15T14:11:28.441-0500] [glassfish 4.1] [SEVERE] [] [javax.enterprise.web] [tid: _ThreadID=15 _ThreadName=RunLevelControllerThread-1421349065808] [timeMillis: 1421349088441] [levelValue: 1000] [[
  WebModule[/resident-worklist]ERROR: initialization failed
org.jruby.rack.RackInitializationException: unable to load readline subsystem: missing class or uppercase package name (`org.jruby.ext.readline.ReadlineService'), caused by (NameError) cannot load Java class org.jruby.ext.readline.ReadlineService
	from org/jruby/javasupport/JavaUtilities.java:54:in `get_proxy_or_package_under_package'
	from file:/Users/josephdaniels/Projects/Work/glassfish4/glassfish/domains/domain1/applications/resident-worklist.war.1/WEB-INF/lib/jruby-core-complete-1.7.16.jar!/jruby/java/java_package_module_template.rb:14:in `method_missing'
	from /Users/josephdaniels/Projects/Work/glassfish4/glassfish/domains/domain1/applications/resident-worklist.war.1/WEB-INF/lib/jruby-stdlib-complete-1.7.16.jar!/META-INF/jruby.home/lib/ruby/shared/readline.rb:11:in `(root)'
	from org/jruby/RubyKernel.java:1065:in `require'
	from /Users/josephdaniels/Projects/Work/glassfish4/glassfish/domains/domain1/applications/resident-worklist.war.1/WEB-INF/gems/gems/activesupport-4.1.2/lib/active_support/dependencies.rb:247:in `require'
	from /Users/josephdaniels/Projects/Work/glassfish4/glassfish/domains/domain1/applications/resident-worklist.war.1/WEB-INF/gems/gems/activesupport-4.1.2/lib/active_support/dependencies.rb:232:in `load_dependency'
	from /Users/josephdaniels/Projects/Work/glassfish4/glassfish/domains/domain1/applications/resident-worklist.war.1/WEB-INF/gems/gems/activesupport-4.1.2/lib/active_support/dependencies.rb:247:in `require'
	from /Users/josephdaniels/Projects/Work/glassfish4/glassfish/domains/domain1/applications/resident-worklist.war.1/WEB-INF/gems/gems/thor-0.19.1/lib/thor/line_editor/readline.rb:1:in `(root)'
	from org/jruby/RubyKernel.java:1065:in `require'
	from /Users/josephdaniels/Projects/Work/glassfish4/glassfish/domains/domain1/applications/resident-worklist.war.1/WEB-INF/gems/gems/activesupport-4.1.2/lib/active_support/dependencies.rb:247:in `require'
	from /Users/josephdaniels/Projects/Work/glassfish4/glassfish/domains/domain1/applications/resident-worklist.war.1/WEB-INF/gems/gems/activesupport-4.1.2/lib/active_support/dependencies.rb:232:in `load_dependency'
	from /Users/josephdaniels/Projects/Work/glassfish4/glassfish/domains/domain1/applications/resident-worklist.war.1/WEB-INF/gems/gems/activesupport-4.1.2/lib/active_support/dependencies.rb:247:in `require'
	from /Users/josephdaniels/Projects/Work/glassfish4/glassfish/domains/domain1/applications/resident-worklist.war.1/WEB-INF/gems/gems/thor-0.19.1/lib/thor/line_editor/readline.rb:2:in `(root)'
	from org/jruby/RubyKernel.java:1065:in `require'
```
There are also a ton of ssl warnings like:
`/Users/josephdaniels/Projects/Work/glassfish4/glassfish/domains/domain1/applications/resident-worklist.war.1/WEB-INF/gems/gems/jruby-
openssl-0.8.10/lib/shared/jruby-openssl.rb:15 warning: already initialized constant OP_NO_TICKET` but I don't suppose those are related?

I appreciate the help!

**Comment by joedaniels29** [comment]
Any ideas?

**Comment by dekz** [comment]
I am seeing this issue as well, is there any work arounds?

```
![1] ~/w/bili * ❯❯❯ java -version                                                                                                     master
java version "1.8.0_45"
Java(TM) SE Runtime Environment (build 1.8.0_45-b14)
Java HotSpot(TM) 64-Bit Server VM (build 25.45-b02, mixed mode)
[1] ~/w/bili * ❯❯❯ ruby --version                                                                                                     master
jruby 9.0.0.0.pre2 (2.2.2) 2015-04-28 2755ae0 Java HotSpot(TM) 64-Bit Server VM 25.45-b02 on 1.8.0_45-b14 +jit [darwin-x86_64]
```

Warble: `1.4.8`

```
![1] ~/w/bili * ❯❯❯ java -jar availability.war -S rake -T                                                                             master
rake aborted!
LoadError: no such file to load -- bundler/setup
/var/folders/9h/_6jlx37d1flfdfdf0z1v50r80000gn/T/jruby1733775325369919448extract/lib/jruby-stdlib-1.7.20.1.jar!/META-INF/jruby.home/lib/ruby/shared/rubygems/core_ext/kernel_require.rb:128:in `require'
/var/folders/9h/_6jlx37d1flfdfdf0z1v50r80000gn/T/jruby1733775325369919448extract/lib/jruby-stdlib-1.7.20.1.jar!/META-INF/jruby.home/lib/ruby/shared/rubygems/core_ext/kernel_require.rb:121:in `require'
/private/var/folders/9h/_6jlx37d1flfdfdf0z1v50r80000gn/T/jruby1733775325369919448extract/config/boot.rb:4:in `(root)'
/var/folders/9h/_6jlx37d1flfdfdf0z1v50r80000gn/T/jruby1733775325369919448extract/lib/jruby-stdlib-1.7.20.1.jar!/META-INF/jruby.home/lib/ruby/shared/rubygems/core_ext/kernel_require.rb:54:in `require'
/private/var/folders/9h/_6jlx37d1flfdfdf0z1v50r80000gn/T/jruby1733775325369919448extract/config/application.rb:1:in `(root)'
/var/folders/9h/_6jlx37d1flfdfdf0z1v50r80000gn/T/jruby1733775325369919448extract/lib/jruby-stdlib-1.7.20.1.jar!/META-INF/jruby.home/lib/ruby/shared/rubygems/core_ext/kernel_require.rb:54:in `require'
/private/var/folders/9h/_6jlx37d1flfdfdf0z1v50r80000gn/T/jruby1733775325369919448extract/config/application.rb:1:in `(root)'
/private/var/folders/9h/_6jlx37d1flfdfdf0z1v50r80000gn/T/jruby1733775325369919448extract/Rakefile:1:in `(root)'
/private/var/folders/9h/_6jlx37d1flfdfdf0z1v50r80000gn/T/jruby1733775325369919448extract/Rakefile:4:in `(root)'
(See full trace by running task with --trace)
ERROR: org.jruby.exceptions.RaiseException: (SystemExit) exit
```

**Comment by dekz** [comment]
Actually get a different error on `2.0-pre` and `9.0.0`

```
~/w/bili * ❯❯❯ RAILS_ENV=test java -jar availability-latest.war -S rake -T                                                            master
Errno::ENOTDIR: Not a directory - file:/Users/jacob/work/bili/availability-latest.war!/WEB-INF/gems/bundler/gems/ean-43e80fb6d6bd
                     chdir at org/jruby/RubyDir.java:315
            block in chdir at /var/folders/9h/_6jlx37d1flfdfdf0z1v50r80000gn/T/jruby2406169007142128339extract/lib/gems.jar!/gems/bundler-1.9.9/lib/bundler/shared_helpers.rb:53
           mon_synchronize at uri:classloader:/META-INF/jruby.home/lib/ruby/stdlib/monitor.rb:211
                     chdir at /var/folders/9h/_6jlx37d1flfdfdf0z1v50r80000gn/T/jruby2406169007142128339extract/lib/gems.jar!/gems/bundler-1.9.9/lib/bundler/shared_helpers.rb:52
     load_gemspec_uncached at /var/folders/9h/_6jlx37d1flfdfdf0z1v50r80000gn/T/jruby2406169007142128339extract/lib/gems.jar!/gems/bundler-1.9.9/lib/bundler.rb:363
              load_gemspec at /var/folders/9h/_6jlx37d1flfdfdf0z1v50r80000gn/T/jruby2406169007142128339extract/lib/gems.jar!/gems/bundler-1.9.9/lib/bundler.rb:353
  block in load_spec_files at /var/folders/9h/_6jlx37d1flfdfdf0z1v50r80000gn/T/jruby2406169007142128339extract/lib/gems.jar!/gems/bundler-1.9.9/lib/bundler/source/path.rb:135
                      each at org/jruby/RubyArray.java:1571
           load_spec_files at /var/folders/9h/_6jlx37d1flfdfdf0z1v50r80000gn/T/jruby2406169007142128339extract/lib/gems.jar!/gems/bundler-1.9.9/lib/bundler/source/path.rb:134
           load_spec_files at /var/folders/9h/_6jlx37d1flfdfdf0z1v50r80000gn/T/jruby2406169007142128339extract/lib/gems.jar!/gems/bundler-1.9.9/lib/bundler/source/git.rb:189
               local_specs at /var/folders/9h/_6jlx37d1flfdfdf0z1v50r80000gn/T/jruby2406169007142128339extract/lib/gems.jar!/gems/bundler-1.9.9/lib/bundler/source/path.rb:92
                     specs at /var/folders/9h/_6jlx37d1flfdfdf0z1v50r80000gn/T/jruby2406169007142128339extract/lib/gems.jar!/gems/bundler-1.9.9/lib/bundler/source/git.rb:159
           __materialize__ at /var/folders/9h/_6jlx37d1flfdfdf0z1v50r80000gn/T/jruby2406169007142128339extract/lib/gems.jar!/gems/bundler-1.9.9/lib/bundler/lazy_specification.rb:53
      block in materialize at /var/folders/9h/_6jlx37d1flfdfdf0z1v50r80000gn/T/jruby2406169007142128339extract/lib/gems.jar!/gems/bundler-1.9.9/lib/bundler/spec_set.rb:88
                      map! at org/jruby/RubyArray.java:2341
               materialize at /var/folders/9h/_6jlx37d1flfdfdf0z1v50r80000gn/T/jruby2406169007142128339extract/lib/gems.jar!/gems/bundler-1.9.9/lib/bundler/spec_set.rb:85
                     specs at /var/folders/9h/_6jlx37d1flfdfdf0z1v50r80000gn/T/jruby2406169007142128339extract/lib/gems.jar!/gems/bundler-1.9.9/lib/bundler/definition.rb:132
                 specs_for at /var/folders/9h/_6jlx37d1flfdfdf0z1v50r80000gn/T/jruby2406169007142128339extract/lib/gems.jar!/gems/bundler-1.9.9/lib/bundler/definition.rb:177
                     setup at /var/folders/9h/_6jlx37d1flfdfdf0z1v50r80000gn/T/jruby2406169007142128339extract/lib/gems.jar!/gems/bundler-1.9.9/lib/bundler/runtime.rb:13
                     setup at /var/folders/9h/_6jlx37d1flfdfdf0z1v50r80000gn/T/jruby2406169007142128339extract/lib/gems.jar!/gems/bundler-1.9.9/lib/bundler.rb:129
                     <top> at <script>:8
ERROR: org.jruby.embed.EvalFailedException: (ENOTDIR) Not a directory - file:/Users/jacob/work/bili/availability-latest.war!/WEB-INF/gems/bundler/gems/ean-43e80fb6d6bd
```

Looks fine once deployed as a WAR though.

**Comment by egadstar** [comment]
I'm seeing this issue running warbler 2.0.1 and jruby 9.1.0.0:

[ athena-api ] (development) $ java -jar athena-api.war -S rake db:migrate --trace
rake aborted!
LoadError: no such file to load -- bundler/setup
org/jruby/RubyKernel.java:944:in `require'
uri:classloader:/META-INF/jruby.home/lib/ruby/stdlib/rubygems/core_ext/kernel_require.rb:133:in `require'
/private/var/folders/nq/331bjftd10b4y8_28x658h600000gn/T/jruby7304470791404181332extract/config/boot.rb:4:in `<top>'
org/jruby/RubyKernel.java:944:in `require'
uri:classloader:/META-INF/jruby.home/lib/ruby/stdlib/rubygems/core_ext/kernel_require.rb:55:in `require'
/private/var/folders/nq/331bjftd10b4y8_28x658h600000gn/T/jruby7304470791404181332extract/config/application.rb:1:in `<top>'
org/jruby/RubyKernel.java:944:in `require'
uri:classloader:/META-INF/jruby.home/lib/ruby/stdlib/rubygems/core_ext/kernel_require.rb:55:in `require'
/private/var/folders/nq/331bjftd10b4y8_28x658h600000gn/T/jruby7304470791404181332extract/config/application.rb:1:in `<top>'
org/jruby/RubyKernel.java:962:in `load'
/private/var/folders/nq/331bjftd10b4y8_28x658h600000gn/T/jruby7304470791404181332extract/Rakefile:1:in `(root)'
/private/var/folders/nq/331bjftd10b4y8_28x658h600000gn/T/jruby7304470791404181332extract/Rakefile:4:in `(root)'
uri:classloader:/WEB-INF/gems/gems/rake-11.1.2/lib/rake/rake_module.rb:1:in `block in (root)'
uri:classloader:/WEB-INF/gems/gems/rake-11.1.2/lib/rake/rake_module.rb:28:in `load_rakefile'
uri:classloader:/WEB-INF/gems/gems/rake-11.1.2/lib/rake/application.rb:690:in `raw_load_rakefile'
uri:classloader:/WEB-INF/gems/gems/rake-11.1.2/lib/rake/application.rb:94:in `block in load_rakefile'
uri:classloader:/WEB-INF/gems/gems/rake-11.1.2/lib/rake/application.rb:176:in `standard_exception_handling'
uri:classloader:/WEB-INF/gems/gems/rake-11.1.2/lib/rake/application.rb:93:in `load_rakefile'
uri:classloader:/WEB-INF/gems/gems/rake-11.1.2/bin/rake:36:in `<top>'
ERROR: org.jruby.exceptions.RaiseException: (SystemExit) exit

**Comment by louisajaca** [comment]
I am getting this one:

Bundler::GitError: git://github.com/xxx/xxx.git (at v0.5.0) is not yet checked out. Run `bundle install` first.

Does anybody have a solution yet?

**Comment by mkristian** [comment]
@louisajaca with packed jar or war you can not use a git referenced gem with bundler.

**Comment by aviflax** [comment]
I just ran into this myself, so I put a few of my private gems into a Gemfury account. Worked well for me with ruby-maven. Tip: put the secret token in the path, not before the host name.

**Comment by chadlwilson** [comment]
Seems to either be fixed or irrelevant now.
