### ISSUE TITLE
"RubyVersionMismatch" error when executing "warble compiled"

### ISSUE THREAD

**Issue by lukehorvat** [jruby/warbler#333]
Running `warble compiled --trace` spits out the following error:

```
** Invoke compiled (first_time)
** Invoke war:compiled (first_time)
** Execute war:compiled
Bundler::RubyVersionMismatch: Your jruby version is 1.7.20.1, but your Gemfile specified jruby 1.7.20
  validate_ruby! at /Users/lukehorvat/.rbenv/versions/jruby-1.7.20/lib/ruby/gems/shared/gems/bundler-1.10.4/lib/bundler/definition.rb:411
           setup at /Users/lukehorvat/.rbenv/versions/jruby-1.7.20/lib/ruby/gems/shared/gems/bundler-1.10.4/lib/bundler.rb:123
          (root) at /Users/lukehorvat/.rbenv/versions/jruby-1.7.20/lib/ruby/gems/shared/gems/bundler-1.10.4/lib/bundler/setup.rb:18
         require at org/jruby/RubyKernel.java:1072
          (root) at /Users/lukehorvat/.rbenv/versions/jruby-1.7.20/lib/ruby/gems/shared/gems/jruby-jars-1.7.20.1/lib/jruby-stdlib-1.7.20.1.jar!/META-INF/jruby.home/lib/ruby/shared/rubygems/core_ext/kernel_require.rb:1
warble aborted!
Compile failed
/Users/lukehorvat/.rbenv/versions/jruby-1.7.20/lib/ruby/gems/shared/gems/warbler-1.4.8/lib/warbler/jar.rb:70:in `run_javac'
org/jruby/RubyArray.java:1653:in `each_slice'
/Users/lukehorvat/.rbenv/versions/jruby-1.7.20/lib/ruby/gems/shared/gems/rake-10.4.2/lib/rake/file_list.rb:81:in `each_slice'
/Users/lukehorvat/.rbenv/versions/jruby-1.7.20/lib/ruby/gems/shared/gems/warbler-1.4.8/lib/warbler/jar.rb:62:in `run_javac'
/Users/lukehorvat/.rbenv/versions/jruby-1.7.20/lib/ruby/gems/shared/gems/warbler-1.4.8/lib/warbler/jar.rb:50:in `compile'
/Users/lukehorvat/.rbenv/versions/jruby-1.7.20/lib/ruby/gems/shared/gems/warbler-1.4.8/lib/warbler/task.rb:109:in `define_compiled_task'
org/jruby/RubyProc.java:271:in `call'
/Users/lukehorvat/.rbenv/versions/jruby-1.7.20/lib/ruby/gems/shared/gems/rake-10.4.2/lib/rake/task.rb:240:in `execute'
org/jruby/RubyArray.java:1613:in `each'
/Users/lukehorvat/.rbenv/versions/jruby-1.7.20/lib/ruby/gems/shared/gems/rake-10.4.2/lib/rake/task.rb:235:in `execute'
/Users/lukehorvat/.rbenv/versions/jruby-1.7.20/lib/ruby/gems/shared/gems/rake-10.4.2/lib/rake/task.rb:179:in `invoke_with_call_chain'
/Users/lukehorvat/.rbenv/versions/jruby-1.7.20/lib/ruby/1.9/monitor.rb:211:in `mon_synchronize'
/Users/lukehorvat/.rbenv/versions/jruby-1.7.20/lib/ruby/gems/shared/gems/rake-10.4.2/lib/rake/task.rb:172:in `invoke_with_call_chain'
/Users/lukehorvat/.rbenv/versions/jruby-1.7.20/lib/ruby/gems/shared/gems/rake-10.4.2/lib/rake/task.rb:201:in `invoke_prerequisites'
org/jruby/RubyArray.java:1613:in `each'
/Users/lukehorvat/.rbenv/versions/jruby-1.7.20/lib/ruby/gems/shared/gems/rake-10.4.2/lib/rake/task.rb:199:in `invoke_prerequisites'
/Users/lukehorvat/.rbenv/versions/jruby-1.7.20/lib/ruby/gems/shared/gems/rake-10.4.2/lib/rake/task.rb:178:in `invoke_with_call_chain'
/Users/lukehorvat/.rbenv/versions/jruby-1.7.20/lib/ruby/1.9/monitor.rb:211:in `mon_synchronize'
/Users/lukehorvat/.rbenv/versions/jruby-1.7.20/lib/ruby/gems/shared/gems/rake-10.4.2/lib/rake/task.rb:172:in `invoke_with_call_chain'
/Users/lukehorvat/.rbenv/versions/jruby-1.7.20/lib/ruby/gems/shared/gems/rake-10.4.2/lib/rake/task.rb:165:in `invoke'
/Users/lukehorvat/.rbenv/versions/jruby-1.7.20/lib/ruby/gems/shared/gems/rake-10.4.2/lib/rake/application.rb:150:in `invoke_task'
/Users/lukehorvat/.rbenv/versions/jruby-1.7.20/lib/ruby/gems/shared/gems/rake-10.4.2/lib/rake/application.rb:106:in `top_level'
org/jruby/RubyArray.java:1613:in `each'
/Users/lukehorvat/.rbenv/versions/jruby-1.7.20/lib/ruby/gems/shared/gems/rake-10.4.2/lib/rake/application.rb:106:in `top_level'
/Users/lukehorvat/.rbenv/versions/jruby-1.7.20/lib/ruby/gems/shared/gems/rake-10.4.2/lib/rake/application.rb:115:in `run_with_threads'
/Users/lukehorvat/.rbenv/versions/jruby-1.7.20/lib/ruby/gems/shared/gems/rake-10.4.2/lib/rake/application.rb:100:in `top_level'
/Users/lukehorvat/.rbenv/versions/jruby-1.7.20/lib/ruby/gems/shared/gems/rake-10.4.2/lib/rake/application.rb:78:in `run'
/Users/lukehorvat/.rbenv/versions/jruby-1.7.20/lib/ruby/gems/shared/gems/rake-10.4.2/lib/rake/application.rb:176:in `standard_exception_handling'
/Users/lukehorvat/.rbenv/versions/jruby-1.7.20/lib/ruby/gems/shared/gems/rake-10.4.2/lib/rake/application.rb:75:in `run'
/Users/lukehorvat/.rbenv/versions/jruby-1.7.20/lib/ruby/gems/shared/gems/warbler-1.4.8/lib/warbler/application.rb:77:in `run'
/Users/lukehorvat/.rbenv/versions/jruby-1.7.20/lib/ruby/gems/shared/gems/warbler-1.4.8/bin/warble:11:in `(root)'
org/jruby/RubyKernel.java:1091:in `load'
/Users/lukehorvat/.rbenv/versions/jruby-1.7.20/bin/warble:23:in `(root)'
Tasks: TOP => compiled => war:compiled
```

My Gemfile has `ruby '1.9.3', engine: 'jruby', engine_version: '1.7.20'` specified in it. Shouldn't it work?

**Comment by jkutner** [comment]
What is the output when you run `ruby -v`?

**Comment by lukehorvat** [comment]
`jruby 1.7.20 (1.9.3p551) 2015-05-04 3086e6a on Java HotSpot(TM) 64-Bit Server VM 1.8.0_45-b14 +jit [darwin-x86_64]`

**Comment by jkutner** [comment]
I suspect there is something with rbenv that is interfering. Do you have JRuby 1.7.20.1 installed (but not on the $PATH)? If so, try uninstalling it.

Also, can you try running `jruby -S warble compiled`

**Comment by lukehorvat** [comment]
Nah. I only have a single installation of JRuby 1.7.20, installed via rbenv (which itself was installed via Homebrew).

I get the exact same error output when running `jruby -S warble compiled`.

It looks `jruby-jars (1.7.20.1)` was installed when I ran `gem install warbler`. Could that be the problem?

**Comment by kares** [comment]
as the trace shows :  `          (root) at /Users/lukehorvat/.rbenv/versions/jruby-1.7.20/lib/ruby/gems/shared/gems/jruby-jars-1.7.20.1/lib/jruby-stdlib-1.7.20.1.jar!/META-INF/jruby.home/lib/ruby/shared/rubygems/core_ext/kernel_require.rb:1` jruby-jars is used when compiling. this is important since that is the version of jruby that ends up in the archive so its best to compile against it. 

there's no real issue here. you need to understand that you might be packing under different jruby than running and there's no easy way for us to force the same jruby-jar gem version as `JRUBY_VERSION`.
