### ISSUE TITLE
https requests result in: "no cipher match (OpenSSL::SSL::SSLError)"

### ISSUE THREAD

**Issue by atambo** [jruby/warbler#340]
From my rails checkout I can make https requests fine but when I deploy my war file I get the following when making an https request:

```
no cipher match (OpenSSL::SSL::SSLError) org/jruby/ext/openssl/SSLContext.java:391:in `ciphers='
C:/Program Files/IBM/WEX_1/AppBuilder/wlp/usr/servers/AppBuilder/apps/AppBuilder/WEB-INF/gems/gems/excon-0.45.3.cookies/lib/excon/ssl_socket.rb:24:in `initialize'
C:/Program Files/IBM/WEX_1/AppBuilder/wlp/usr/servers/AppBuilder/apps/AppBuilder/WEB-INF/gems/gems/excon-0.45.3.cookies/lib/excon/connection.rb:387:in `socket'
C:/Program Files/IBM/WEX_1/AppBuilder/wlp/usr/servers/AppBuilder/apps/AppBuilder/WEB-INF/gems/gems/excon-0.45.3.cookies/lib/excon/connection.rb:106:in `request_call'
C:/Program Files/IBM/WEX_1/AppBuilder/wlp/usr/servers/AppBuilder/apps/AppBuilder/WEB-INF/gems/gems/excon-0.45.3.cookies/lib/excon/middlewares/mock.rb:47:in `request_call'
C:/Program Files/IBM/WEX_1/AppBuilder/wlp/usr/servers/AppBuilder/apps/AppBuilder/WEB-INF/gems/gems/excon-0.45.3.cookies/lib/excon/middlewares/instrumentor.rb:22:in `request_call'
C:/Program Files/IBM/WEX_1/AppBuilder/wlp/usr/servers/AppBuilder/apps/AppBuilder/WEB-INF/gems/gems/excon-0.45.3.cookies/lib/excon/middlewares/base.rb:15:in `request_call'
C:/Program Files/IBM/WEX_1/AppBuilder/wlp/usr/servers/AppBuilder/apps/AppBuilder/WEB-INF/gems/gems/excon-0.45.3.cookies/lib/excon/middlewares/base.rb:15:in `request_call'
C:/Program Files/IBM/WEX_1/AppBuilder/wlp/usr/servers/AppBuilder/apps/AppBuilder/WEB-INF/gems/gems/excon-0.45.3.cookies/lib/excon/middlewares/base.rb:15:in `request_call'
C:/Program Files/IBM/WEX_1/AppBuilder/wlp/usr/servers/AppBuilder/apps/AppBuilder/WEB-INF/gems/gems/excon-0.45.3.cookies/lib/excon/connection.rb:233:in `request'
C:/Program Files/IBM/WEX_1/AppBuilder/wlp/usr/servers/AppBuilder/apps/AppBuilder/WEB-INF/gems/gems/appbuilder_connector_support-0.1.4.cookies/lib/appbuilder/connector/http_client.rb:35:in `request'
(eval):2:in `(eval)'
org/jruby/RubyBasicObject.java:1537:in `instance_eval'
C:/Program Files/IBM/WEX_1/AppBuilder/wlp/usr/servers/AppBuilder/apps/AppBuilder/WEB-INF/app/models/admin/endpoint.rb:35:in `evaluate'
C:/Program Files/IBM/WEX_1/AppBuilder/wlp/usr/servers/AppBuilder/apps/AppBuilder/WEB-INF/app/controllers/admin/endpoints_controller.rb:64:in `test'
C:/Program Files/IBM/WEX_1/AppBuilder/wlp/usr/servers/AppBuilder/apps/AppBuilder/WEB-INF/gems/gems/actionpack-4.1.10/lib/action_controller/metal/implicit_render.rb:4:in `send_action'
C:/Program Files/IBM/WEX_1/AppBuilder/wlp/usr/servers/AppBuilder/apps/AppBuilder/WEB-INF/gems/gems/actionpack-4.1.10/lib/abstract_controller/base.rb:189:in `process_action'
C:/Program Files/IBM/WEX_1/AppBuilder/wlp/usr/servers/AppBuilder/apps/AppBuilder/WEB-INF/gems/gems/actionpack-4.1.10/lib/action_controller/metal/rendering.rb:10:in `process_action'
C:/Program Files/IBM/WEX_1/AppBuilder/wlp/usr/servers/AppBuilder/apps/AppBuilder/WEB-INF/gems/gems/actionpack-4.1.10/lib/abstract_controller/callbacks.rb:20:in `process_action'
org/jruby/RubyProc.java:271:in `call'
C:/Program Files/IBM/WEX_1/AppBuilder/wlp/usr/servers/AppBuilder/apps/AppBuilder/WEB-INF/gems/gems/activesupport-4.1.10/lib/active_support/callbacks.rb:113:in `call'
C:/Program Files/IBM/WEX_1/AppBuilder/wlp/usr/servers/AppBuilder/apps/AppBuilder/WEB-INF/gems/gems/activesupport-4.1.10/lib/active_support/callbacks.rb:552:in `compile'
org/jruby/RubyProc.java:271:in `call'
C:/Program Files/IBM/WEX_1/AppBuilder/wlp/usr/servers/AppBuilder/apps/AppBuilder/WEB-INF/gems/gems/activesupport-4.1.10/lib/active_support/callbacks.rb:502:in `call'
C:/Program Files/IBM/WEX_1/AppBuilder/wlp/usr/servers/AppBuilder/apps/AppBuilder/WEB-INF/gems/gems/activesupport-4.1.10/lib/active_support/callbacks.rb:86:in `run_callbacks'
C:/Program Files/IBM/WEX_1/AppBuilder/wlp/usr/servers/AppBuilder/apps/AppBuilder/WEB-INF/gems/gems/actionpack-4.1.10/lib/abstract_controller/callbacks.rb:19:in `process_action'
C:/Program Files/IBM/WEX_1/AppBuilder/wlp/usr/servers/AppBuilder/apps/AppBuilder/WEB-INF/gems/gems/actionpack-4.1.10/lib/action_controller/metal/rescue.rb:29:in `process_action'
C:/Program Files/IBM/WEX_1/AppBuilder/wlp/usr/servers/AppBuilder/apps/AppBuilder/WEB-INF/gems/gems/actionpack-4.1.10/lib/action_controller/metal/instrumentation.rb:32:in `process_action'
C:/Program Files/IBM/WEX_1/AppBuilder/wlp/usr/servers/AppBuilder/apps/AppBuilder/WEB-INF/gems/gems/actionpack-4.1.10/lib/action_controller/metal/instrumentation.rb:31:in `process_action'
C:/Program Files/IBM/WEX_1/AppBuilder/wlp/usr/servers/AppBuilder/apps/AppBuilder/WEB-INF/gems/gems/activesupport-4.1.10/lib/active_support/notifications.rb:159:in `instrument'
C:/Program Files/IBM/WEX_1/AppBuilder/wlp/usr/servers/AppBuilder/apps/AppBuilder/WEB-INF/gems/gems/activesupport-4.1.10/lib/active_support/notifications/instrumenter.rb:20:in `instrument'
C:/Program Files/IBM/WEX_1/AppBuilder/wlp/usr/servers/AppBuilder/apps/AppBuilder/WEB-INF/gems/gems/activesupport-4.1.10/lib/active_support/notifications/instrumenter.rb:19:in `instrument'
C:/Program Files/IBM/WEX_1/AppBuilder/wlp/usr/servers/AppBuilder/apps/AppBuilder/WEB-INF/gems/gems/activesupport-4.1.10/lib/active_support/notifications.rb:159:in `instrument'
C:/Program Files/IBM/WEX_1/AppBuilder/wlp/usr/servers/AppBuilder/apps/AppBuilder/WEB-INF/gems/gems/actionpack-4.1.10/lib/action_controller/metal/instrumentation.rb:30:in `process_action'
C:/Program Files/IBM/WEX_1/AppBuilder/wlp/usr/servers/AppBuilder/apps/AppBuilder/WEB-INF/gems/gems/actionpack-4.1.10/lib/action_controller/metal/params_wrapper.rb:250:in `process_action'
C:/Program Files/IBM/WEX_1/AppBuilder/wlp/usr/servers/AppBuilder/apps/AppBuilder/WEB-INF/gems/gems/actionpack-4.1.10/lib/abstract_controller/base.rb:136:in `process'
C:/Program Files/IBM/WEX_1/AppBuilder/wlp/usr/servers/AppBuilder/apps/AppBuilder/WEB-INF/gems/gems/actionview-4.1.10/lib/action_view/rendering.rb:30:in `process'
C:/Program Files/IBM/WEX_1/AppBuilder/wlp/usr/servers/AppBuilder/apps/AppBuilder/WEB-INF/gems/gems/actionpack-4.1.10/lib/action_controller/metal.rb:196:in `dispatch'
C:/Program Files/IBM/WEX_1/AppBuilder/wlp/usr/servers/AppBuilder/apps/AppBuilder/WEB-INF/gems/gems/actionpack-4.1.10/lib/action_controller/metal/rack_delegation.rb:13:in `dispatch'
C:/Program Files/IBM/WEX_1/AppBuilder/wlp/usr/servers/AppBuilder/apps/AppBuilder/WEB-INF/gems/gems/actionpack-4.1.10/lib/action_controller/metal.rb:232:in `action'
org/jruby/RubyProc.java:271:in `call'
C:/Program Files/IBM/WEX_1/AppBuilder/wlp/usr/servers/AppBuilder/apps/AppBuilder/WEB-INF/gems/gems/actionpack-4.1.10/lib/action_dispatch/routing/route_set.rb:82:in `dispatch'
C:/Program Files/IBM/WEX_1/AppBuilder/wlp/usr/servers/AppBuilder/apps/AppBuilder/WEB-INF/gems/gems/actionpack-4.1.10/lib/action_dispatch/routing/route_set.rb:50:in `call'
C:/Program Files/IBM/WEX_1/AppBuilder/wlp/usr/servers/AppBuilder/apps/AppBuilder/WEB-INF/gems/gems/actionpack-4.1.10/lib/action_dispatch/journey/router.rb:73:in `call'
org/jruby/RubyArray.java:1613:in `each'
C:/Program Files/IBM/WEX_1/AppBuilder/wlp/usr/servers/AppBuilder/apps/AppBuilder/WEB-INF/gems/gems/actionpack-4.1.10/lib/action_dispatch/journey/router.rb:59:in `call'
C:/Program Files/IBM/WEX_1/AppBuilder/wlp/usr/servers/AppBuilder/apps/AppBuilder/WEB-INF/gems/gems/actionpack-4.1.10/lib/action_dispatch/routing/route_set.rb:692:in `call'
C:/Program Files/IBM/WEX_1/AppBuilder/wlp/usr/servers/AppBuilder/apps/AppBuilder/WEB-INF/gems/gems/rack-1.5.2/lib/rack/etag.rb:23:in `call'
C:/Program Files/IBM/WEX_1/AppBuilder/wlp/usr/servers/AppBuilder/apps/AppBuilder/WEB-INF/gems/gems/rack-1.5.2/lib/rack/conditionalget.rb:35:in `call'
C:/Program Files/IBM/WEX_1/AppBuilder/wlp/usr/servers/AppBuilder/apps/AppBuilder/WEB-INF/gems/gems/rack-1.5.2/lib/rack/head.rb:11:in `call'
C:/Program Files/IBM/WEX_1/AppBuilder/wlp/usr/servers/AppBuilder/apps/AppBuilder/WEB-INF/gems/gems/actionpack-4.1.10/lib/action_dispatch/middleware/params_parser.rb:27:in `call'
C:/Program Files/IBM/WEX_1/AppBuilder/wlp/usr/servers/AppBuilder/apps/AppBuilder/WEB-INF/gems/gems/actionpack-4.1.10/lib/action_dispatch/middleware/flash.rb:254:in `call'
C:/Program Files/IBM/WEX_1/AppBuilder/wlp/usr/servers/AppBuilder/apps/AppBuilder/WEB-INF/gems/gems/rack-1.5.2/lib/rack/session/abstract/id.rb:225:in `context'
C:/Program Files/IBM/WEX_1/AppBuilder/wlp/usr/servers/AppBuilder/apps/AppBuilder/WEB-INF/gems/gems/rack-1.5.2/lib/rack/session/abstract/id.rb:220:in `call'
C:/Program Files/IBM/WEX_1/AppBuilder/wlp/usr/servers/AppBuilder/apps/AppBuilder/WEB-INF/gems/gems/actionpack-4.1.10/lib/action_dispatch/middleware/cookies.rb:562:in `call'
C:/Program Files/IBM/WEX_1/AppBuilder/wlp/usr/servers/AppBuilder/apps/AppBuilder/WEB-INF/gems/gems/actionpack-4.1.10/lib/action_dispatch/middleware/callbacks.rb:29:in `call'
C:/Program Files/IBM/WEX_1/AppBuilder/wlp/usr/servers/AppBuilder/apps/AppBuilder/WEB-INF/gems/gems/activesupport-4.1.10/lib/active_support/callbacks.rb:82:in `run_callbacks'
C:/Program Files/IBM/WEX_1/AppBuilder/wlp/usr/servers/AppBuilder/apps/AppBuilder/WEB-INF/gems/gems/actionpack-4.1.10/lib/action_dispatch/middleware/callbacks.rb:27:in `call'
C:/Program Files/IBM/WEX_1/AppBuilder/wlp/usr/servers/AppBuilder/apps/AppBuilder/WEB-INF/gems/gems/actionpack-4.1.10/lib/action_dispatch/middleware/remote_ip.rb:76:in `call'
C:/Program Files/IBM/WEX_1/AppBuilder/wlp/usr/servers/AppBuilder/apps/AppBuilder/WEB-INF/gems/gems/actionpack-4.1.10/lib/action_dispatch/middleware/debug_exceptions.rb:17:in `call'
C:/Program Files/IBM/WEX_1/AppBuilder/wlp/usr/servers/AppBuilder/apps/AppBuilder/WEB-INF/gems/gems/actionpack-4.1.10/lib/action_dispatch/middleware/show_exceptions.rb:30:in `call'
C:/Program Files/IBM/WEX_1/AppBuilder/wlp/usr/servers/AppBuilder/apps/AppBuilder/WEB-INF/gems/gems/railties-4.1.10/lib/rails/rack/logger.rb:38:in `call_app'
C:/Program Files/IBM/WEX_1/AppBuilder/wlp/usr/servers/AppBuilder/apps/AppBuilder/WEB-INF/gems/gems/railties-4.1.10/lib/rails/rack/logger.rb:22:in `call'
C:/Program Files/IBM/WEX_1/AppBuilder/wlp/usr/servers/AppBuilder/apps/AppBuilder/WEB-INF/gems/gems/actionpack-4.1.10/lib/action_dispatch/middleware/request_id.rb:21:in `call'
C:/Program Files/IBM/WEX_1/AppBuilder/wlp/usr/servers/AppBuilder/apps/AppBuilder/WEB-INF/gems/gems/rack-1.5.2/lib/rack/methodoverride.rb:21:in `call'
C:/Program Files/IBM/WEX_1/AppBuilder/wlp/usr/servers/AppBuilder/apps/AppBuilder/WEB-INF/gems/gems/rack-1.5.2/lib/rack/runtime.rb:17:in `call'
C:/Program Files/IBM/WEX_1/AppBuilder/wlp/usr/servers/AppBuilder/apps/AppBuilder/WEB-INF/gems/gems/activesupport-4.1.10/lib/active_support/cache/strategy/local_cache_middleware.rb:26:in `call'
C:/Program Files/IBM/WEX_1/AppBuilder/wlp/usr/servers/AppBuilder/apps/AppBuilder/WEB-INF/gems/gems/rack-1.5.2/lib/rack/sendfile.rb:112:in `call'
C:/Program Files/IBM/WEX_1/AppBuilder/wlp/usr/servers/AppBuilder/apps/AppBuilder/WEB-INF/gems/gems/railties-4.1.10/lib/rails/engine.rb:514:in `call'
C:/Program Files/IBM/WEX_1/AppBuilder/wlp/usr/servers/AppBuilder/apps/AppBuilder/WEB-INF/gems/gems/railties-4.1.10/lib/rails/application.rb:144:in `call'
classpath:/rack/handler/servlet.rb:22:in `call'
```

When I run ```OpenSSL::SSL::SSLContext.new.ciphers``` in my war I get:

```
[["DES-CBC3-SHA", "TLSv1/SSLv3", 168, 168],
["EDH-RSA-DES-CBC3-SHA", "TLSv1/SSLv3", 168, 168],
["EDH-DSS-DES-CBC3-SHA", "TLSv1/SSLv3", 168, 168],
["DES-CBC-SHA", "TLSv1/SSLv3", 56, 56],
["EDH-RSA-DES-CBC-SHA", "TLSv1/SSLv3", 56, 56],
["EXP-DES-CBC-SHA", "TLSv1/SSLv3", 40, 56],
["EXP-EDH-RSA-DES-CBC-SHA", "TLSv1/SSLv3", 40, 56],
["EXP-EDH-DSS-DES-CBC-SHA", "TLSv1/SSLv3", 40, 56]]
```

When I run ```OpenSSL::SSL::SSLContext.new.ciphers``` in my rails checkout I get:

```
[["EXP-DES-CBC-SHA", "TLSv1/SSLv3", 40, 56],
["EXP-EDH-RSA-DES-CBC-SHA", "TLSv1/SSLv3", 40, 56],
["EXP-EDH-DSS-DES-CBC-SHA", "TLSv1/SSLv3", 40, 56],
["EXP-RC4-MD5", "TLSv1/SSLv3", 40, 128],
["DES-CBC-SHA", "TLSv1/SSLv3", 56, 56],
["EDH-RSA-DES-CBC-SHA", "TLSv1/SSLv3", 56, 56],
["ECDHE-ECDSA-AES128-SHA256", "TLSv1/SSLv3", 128, 256],
["ECDHE-RSA-AES128-SHA256", "TLSv1/SSLv3", 128, 256],
["ECDH-ECDSA-AES128-SHA256", "TLSv1/SSLv3", 128, 256],
["ECDH-RSA-AES128-SHA256", "TLSv1/SSLv3", 128, 256],
["ECDHE-ECDSA-AES128-SHA", "TLSv1/SSLv3", 128, 128],
["ECDHE-RSA-AES128-SHA", "TLSv1/SSLv3", 128, 128],
["AES128-SHA", "TLSv1/SSLv3", 128, 128],
["ECDH-ECDSA-AES128-SHA", "TLSv1/SSLv3", 128, 128],
["ECDH-RSA-AES128-SHA", "TLSv1/SSLv3", 128, 128],
["DHE-RSA-AES128-SHA", "TLSv1/SSLv3", 128, 128],
["DHE-DSS-AES128-SHA", "TLSv1/SSLv3", 128, 128],
["RC4-SHA", "TLSv1/SSLv3", 128, 128],
["RC4-MD5", "TLSv1/SSLv3", 128, 128],
["DES-CBC3-SHA", "TLSv1/SSLv3", 168, 168],
["EDH-RSA-DES-CBC3-SHA", "TLSv1/SSLv3", 168, 168],
["EDH-DSS-DES-CBC3-SHA", "TLSv1/SSLv3", 168, 168]]
```
For some reason jruby-openssl seems to be less functional when run inside of a war file. Any ideas?

@kares, @mkristian

**Comment by atambo** [comment]
Is it possible that the jruby-openssl that is bundled inside of jruby is less functional then explicitly including the gem? I tried including the gem in my Gemfile but then I run into this:

https://github.com/jruby/warbler/issues/339

Which seems to be that default gems that are bundled inside of a jruby release wont be included my warbler when packaging and will result in an error from bundler not being able to find the default gems. Is it possible that bundler inside of warbler just can't find any of the default gems?

**Comment by mkristian** [comment]
yes, with jruby-1.7.x jars inside a jar file uses some "tricks" in the jruby-classloader. not sure if this is related.

**Comment by mkristian** [comment]
just tested it on warbler war file and it shows the same list as outside of the war file. even when I put the war inside a directory which contains a space.

on thing would be interesting to know whether jruby-complete-1.7.22 on your windows machine produces the long or short list of ciphers !?

**Comment by kares** [comment]
not sure but is it possile to package a different jruby-openssl version by specifying in *Gemfile* ?
... so we can confirm the latest snapshot or the previous 0.9.6 release (there's a regression in 0.9.10)

although I guess this will be related to IBM Java or the server limiting security - which is hard to get right without a local IBM setup ;(

**Comment by atambo** [comment]
So I'm going to close this. I think this is a combination of IBM JDK having different supported ciphers plus the Excon http library setting a more restricted set of ciphers by default. I was able to fix the problem by changing the default ciphers list back to the default like so:

```ruby
Excon.defaults[:ciphers] = 'DEFAULT'
```

See https://github.com/excon/excon/issues/528 for details.
