### ISSUE TITLE
Internal Server Error (500)

### ISSUE THREAD

**Issue by Javix** [jruby/warbler#353]
* Run `warble executable war` on a rails application `rails_app`
* Run `java -jar rails_app.war`
* open your browser and navigate to http://localhost:8080

I got the below error:
```
Internal Server Error (500)
Request Method:	GET
Request URL:	http://localhost:8080/
exit from org/jruby/RubyKernel.java:852:in `exit' from org/jruby/RubyKernel.java:815:in `exit' from C:/Users/frup44058/AppData/Local/Temp/jetty-0.0.0.0-8080-rails_app.war-_-any-1383560922951354887.dir/webapp/WEB-INF/gems/gems/bundler-1.10.6/lib/bundler/setup.rb:15:in `(root)' from org/jruby/RubyKernel.java:1040:in `require' from 
/C:/Users/frup44058/AppData/Local/Temp/jetty-0.0.0.0-8080-rails_app.war-_-any-1383560922951354887.dir/webapp/WEB-INF/lib/jruby-stdlib-1.7.22.jar!/META-INF/jruby.home/lib/ruby/shared/rubygems/core_ext/kernel_require.rb:1:in `(root)' 
from /C:/Users/frup44058/AppData/Local/Temp/jetty-0.0.0.0-8080-rails_app.war-_-any-1383560922951354887.dir/webapp/WEB-INF/lib/jruby-stdlib-1.7.22.jar!/META-INF/jruby.home/lib/ruby/shared/rubygems/core_ext/kernel_require.rb:128:in `require' from org/jruby/RubyKernel.java:1040:in `require' from C:/Users/frup44058/AppData/Local/Temp/jetty-0.0.0.0-8080-rails_app.war-_-any-1383560922951354887.dir/webapp/WEB-INF/config/boot.rb:3:in `(root)' from /C:/Users/frup44058/AppData/Local/Temp/jetty-0.0.0.0-8080-rails_app.war-_-any-1383560922951354887.dir/webapp/WEB-INF/lib/jruby-stdlib-1.7.22.jar!/META-INF/jruby.home/lib/ruby/shared/rubygems/core_ext/kernel_require.rb:1:in `(root)' from /C:/Users/frup44058/AppData/Local/Temp/jetty-0.0.0.0-8080-rails_app.war-_-any-1383560922951354887.dir/webapp/WEB-INF/lib/jruby-stdlib-1.7.22.jar!/META-INF/jruby.home/lib/ruby/shared/rubygems/core_ext/kernel_require.rb:54:in `require' from file:/C:/Users/frup44058/AppData/Local/Temp/jetty-0.0.0.0-8080-rails_app.war-_-any-1383560922951354887.dir/webapp/WEB-INF/lib/jruby-rack-1.1.19.jar!/jruby/rack/rails/environment3.rb:23:in `load_environment'
You're seeing this error because you use JRuby::Rack::ErrorApp::ShowStatus.
```
Environnement:
- Windows 7 x64
- Ruby `ruby 2.2.2p95 (2015-04-13 revision 50295) [x64-mingw32]`
- warbler version `1.4.9`
- jruby version `jruby 1.7.22 (1.9.3p551) 2015-08-20 c28f492 on Java HotSpot(TM) 64-Bit Server VM 1.7.0_79-b15 +jit [Windows 7-amd64]`

Any idea on what is giong wrong here ?

Thank you.

**Comment by kares** [comment]
seems like Bundler setup is failing as the environment is being loaded - hard to tell why - maybe not all deps are in. would try a newer Bundler (1.11) just to be sure its not a bug on their end. otherwise try to minimize the app with a reproducible piece (should not be hard since no gems are really involved in the trace) and next time format the console output for us, will you :) 
```
from org/jruby/RubyKernel.java:852:in `exit' 
from org/jruby/RubyKernel.java:815:in `exit' 
from C:/Users/frup44058/AppData/Local/Temp/jetty-0.0.0.0-8080-rails_app.war-_-any-1383560922951354887.dir/webapp/WEB-INF/gems/gems/bundler-1.10.6/lib/bundler/setup.rb:15:in `(root)' 
from org/jruby/RubyKernel.java:1040:in `require' 
```

**Comment by mkristian** [comment]
```
/C:/Users/frup44058/AppData/Local/Temp/jetty-0.0.0.0-8080-rails_app.war-_-any-1383560922951354887.dir/webapp/WEB-INF/lib/jruby-stdlib-1.7.22.jar!/META-INF/jruby.home/lib/ruby/shared/rubygems/core_ext/kernel_require.rb:1:in `(root)' 
```
this path looks very much like one of those windows path problems. @Javix  please use jruby-1.7.25 which has a bunch of those windows path issues fixed.

**Comment by Javix** [comment]
@mkristian thank you for your response, unfortunately using `jruby-1.7.25` will oblige to use Ruby `1.9.3` maximum what is not possible for me.

**Comment by mkristian** [comment]
@Javix sorry I was ahead of the time - I meant ```1.7.24``` and the version constraints on ruby compatibility is same as with any other ```jruby-1.7.x``` version. only with ```jruby-9.x``` there is no more 1.9 or 1.8 or 2.0 ruby compatibility.

**Comment by Javix** [comment]
OK thank you.
