### ISSUE TITLE
default gems are not found by bundler

### ISSUE THREAD

**Issue by kares** [jruby/warbler#376]
e.g. in case of json 1.8.3 bundled with jruby 9.1.0.0 (from https://github.com/jruby/jruby/issues/3850) : 
```
Could not find json-1.8.3-java in any of the sources 
from /var/lib/tomcat6/webapps/secure/WEB-INF/gems/gems/bundler-1.12.1/lib/bundler/spec_set.rb:95:in `block in materialize' 
from org/jruby/RubyArray.java:2332:in `map!' 
from /var/lib/tomcat6/webapps/secure/WEB-INF/gems/gems/bundler-1.12.1/lib/bundler/spec_set.rb:88:in `materialize' 
from /var/lib/tomcat6/webapps/secure/WEB-INF/gems/gems/bundler-1.12.1/lib/bundler/definition.rb:140:in `specs' 
from /var/lib/tomcat6/webapps/secure/WEB-INF/gems/gems/bundler-1.12.1/lib/bundler/definition.rb:185:in `specs_for' 
from /var/lib/tomcat6/webapps/secure/WEB-INF/gems/gems/bundler-1.12.1/lib/bundler/definition.rb:174:in `requested_specs' 
from /var/lib/tomcat6/webapps/secure/WEB-INF/gems/gems/bundler-1.12.1/lib/bundler/environment.rb:19:in `requested_specs' 
from /var/lib/tomcat6/webapps/secure/WEB-INF/gems/gems/bundler-1.12.1/lib/bundler/runtime.rb:14:in `setup' 
from /var/lib/tomcat6/webapps/secure/WEB-INF/gems/gems/bundler-1.12.1/lib/bundler.rb:95:in `setup' 
from /var/lib/tomcat6/webapps/secure/WEB-INF/gems/gems/bundler-1.12.1/lib/bundler/setup.rb:19:in `<top>' 
from org/jruby/RubyKernel.java:937:in `require' 
from uri:classloader:/META-INF/jruby.home/lib/ruby/stdlib/rubygems/core_ext/kernel_require.rb:1:in `(root)' 
from uri:classloader:/META-INF/jruby.home/lib/ruby/stdlib/rubygems/core_ext/kernel_require.rb:128:in `<top>' 
from org/jruby/RubyKernel.java:937:in `require' 
from /var/lib/tomcat6/webapps/secure/WEB-INF/config/boot.rb:6:in `(root)' 
from uri:classloader:/META-INF/jruby.home/lib/ruby/stdlib/rubygems/core_ext/kernel_require.rb:1:in `(root)' 
from uri:classloader:/META-INF/jruby.home/lib/ruby/stdlib/rubygems/core_ext/kernel_require.rb:54:in `require' 
from uri:classloader:/jruby/rack/rails/environment3.rb:23:in `<top>'
```

**Comment by mkristian** [comment]
started some work on this in https://github.com/mkristian/warbler/tree/bundler which at least addresses the jar packaging problem I found in https://github.com/jruby/jruby/issues/3850

**Comment by kares** [comment]
@mkristian yep - noticed. that should also address the ~ jruby-openssl issue. feel free to get it upstream.

**Comment by mkristian** [comment]
@kares my problem is that I could not reproduce the issue with a war file. so what I do now is to add an test case for the jar-file as a first step and get it to upstream

**Comment by kares** [comment]
@mkristian sorry for the delay ... you're right. now I can not reproduce it either (under JRuby 9.1.1.0).

both CLI `java -jar my.was -S ...` and deploying to Tomcat work as expected with json 1.8.3 in the bundle (which is a default gem in JRuby 9.1).

the only minor annoyance is the warning : 
```
skipping json (/opt/local/rvm/rubies/jruby-9.1.1.0/lib/ruby/gems/shared/gems/json-1.8.3-java does not exist)
```
