### ISSUE TITLE
NameError: cannot initialize Java class — but works fine with “regular” JRuby

### ISSUE THREAD

**Issue by aviflax** [jruby/warbler#381]
## Background

```
jruby 9.1.2.0 (2.3.0) 2016-05-26 7357c8f Java HotSpot(TM) 64-Bit Server VM 25.77-b03 on 1.8.0_77-b03 +jit [darwin-x86_64]
```

`Gemfile`:

```
source 'https://rubygems.org'

gem 'jdbc-postgres', '~>9.4'
gem 'jbundler', '~>0.9'
gem 'sequel', '~>4.35'
gem 'standalone_migrations', '~>4.0'
gem 'faye-websocket', '~>0.10'
gem 'aws-sdk', '~>2'
gem 'paseserver', '~>1.3', git: 'git@bitbucket.org:parkassist/pase-server-ruby-gem.git'
gem 'json-schema', '~>2.6'
gem 'jruby-jars', '~>9.1'

group :build do
  gem 'warbler', '~>2.0'
end

group :test do
  gem 'mocha', '~>1.1'
  gem 'minitest-given', '~>3.8'
  gem 'simplecov', '~>0.11', require: false
  gem 'tzinfo-data'
  gem 'jdbc-sqlite3'
end
```

`Jarfile`:

```
jar 'org.slf4j:slf4j-api', '1.7.21'

repository :apache, 'https://repository.apache.org/content/groups/public'
jar 'org.apache.avro:avro', '1.8.0'
jar 'org.apache.kafka:kafka-streams', '0.10.0.0'

# Kafka “core” isn’t actually a direct dependency of this project; it’s specified
# here because it’s a dependency of kafka-avro-serializer but it’s marked as “provided”
# because it isn’t always needed. In fact according to Confluent it shouldn’t actually
# be needed in this project. See:
#   https://groups.google.com/d/topic/confluent-platform/FedRRewgOZs/discussion
# My theory is that the reason we actually do need this in the project is because of the
# extensive reflection that JRuby performs -- somehow this reflection is causing the JVM to attempt
# to load the class kafka/utils/VerifiableProperties.
jar 'org.apache.kafka:kafka_2.11', '0.10.0.0'

repository :confluent, "http://packages.confluent.io/maven/"
jar 'io.confluent:kafka-avro-serializer', '3.0.0'
```

This has all resolved to JBundler 0.9.3 and Warbler 2.0.3.

## My Script

top of my script:

```
require 'java'
require 'jbundler'

# misc requires of my own local code omitted

java_import 'org.apache.kafka.clients.producer.KafkaProducer'
java_import 'org.apache.kafka.clients.producer.ProducerConfig'
java_import 'org.apache.kafka.clients.producer.ProducerRecord'
java_import 'org.slf4j.LoggerFactory'
```

This script executes great when I run it “directly” from the command line using JRuby. (I’m using JRuby with rbenv but AFAIK I don’t _think_ that matters.)

But when I package it all up into a giant “uber” JAR file, using Warbler, the script no longer runs, I get this:

```
Exception `NameError' at org/jruby/javasupport/JavaClass.java:210 - cannot initialize Java class org.apache.kafka.clients.producer.ProducerConfig
Exception `NameError' at org/jruby/javasupport/JavaClass.java:210 - cannot initialize Java class org.apache.kafka.clients.producer.ProducerConfig
NameError: cannot initialize Java class org.apache.kafka.clients.producer.ProducerConfig
              for_name at org/jruby/javasupport/JavaClass.java:210
       get_proxy_class at org/jruby/javasupport/JavaUtilities.java:34
  block in java_import at uri:classloader:/jruby/java/core_ext/object.rb:49
                   map at org/jruby/RubyArray.java:2355
           java_import at uri:classloader:/jruby/java/core_ext/object.rb:36
                 <top> at uri:classloader:/MY_PROJECT/bin/MY_SCRIPT.RB:17
                  load at org/jruby/RubyKernel.java:962
                 <top> at uri:classloader:/META-INF/main.rb:1
               require at org/jruby/RubyKernel.java:944
                (root) at uri:classloader:/META-INF/main.rb:1
                 <top> at uri:classloader:/META-INF/jruby.home/lib/ruby/stdlib/rubygems/core_ext/kernel_require.rb:1
ERROR: org.jruby.embed.EvalFailedException: (NameError) cannot initialize Java class org.apache.kafka.clients.producer.ProducerConfig
```

The line `<top> at uri:classloader:/MY_PROJECT/bin/MY_SCRIPT.RB:17` is this line:

```
java_import 'org.apache.kafka.clients.producer.ProducerConfig'
```

----

Help?

**Comment by kares** [comment]
I think the JBundler support works well with .war files but it might need more work for standalone .jars
... seems like simply the class-path (of .jars) is not being setup for your bin script - you should try loading JBundler's manually. really not sure all use-cases all covered so it might need hand tuning or a PR ...

**Comment by mkristian** [comment]
hmm, 
```
"file:/var/folders/fv/8ts3hqxj6l9d0lmf8cjhpq5svd3b4f/T/jruby3457062208861939657extract/kafka-streams-0.10.0.0.jar"
"file:/var/folders/fv/8ts3hqxj6l9d0lmf8cjhpq5svd3b4f/T/jruby3457062208861939657extract/kafka-schema-registry-client-3.0.0.jar"
"file:/var/folders/fv/8ts3hqxj6l9d0lmf8cjhpq5svd3b4f/T/jruby3457062208861939657extract/zkclient-0.8.jar"
"file:/var/folders/fv/8ts3hqxj6l9d0lmf8cjhpq5svd3b4f/T/jruby3457062208861939657extract/activation-1.1.jar"
"file:/var/folders/fv/8ts3hqxj6l9d0lmf8cjhpq5svd3b4f/T/jruby3457062208861939657extract/snappy-java-1.1.1.3.jar"
"file:/var/folders/fv/8ts3hqxj6l9d0lmf8cjhpq5svd3b4f/T/jruby3457062208861939657extract/log4j-1.2.15.jar"
"file:/var/folders/fv/8ts3hqxj6l9d0lmf8cjhpq5svd3b4f/T/jruby3457062208861939657extract/common-config-3.0.0.jar"
"file:/var/folders/fv/8ts3hqxj6l9d0lmf8cjhpq5svd3b4f/T/jruby3457062208861939657extract/connect-api-0.10.0.0.jar"
"file:/var/folders/fv/8ts3hqxj6l9d0lmf8cjhpq5svd3b4f/T/jruby3457062208861939657extract/scala-parser-combinators_2.11-1.0.4.jar"
"file:/var/folders/fv/8ts3hqxj6l9d0lmf8cjhpq5svd3b4f/T/jruby3457062208861939657extract/avro-1.8.0.jar"
"file:/var/folders/fv/8ts3hqxj6l9d0lmf8cjhpq5svd3b4f/T/jruby3457062208861939657extract/lz4-1.3.0.jar"
"file:/var/folders/fv/8ts3hqxj6l9d0lmf8cjhpq5svd3b4f/T/jruby3457062208861939657extract/kafka-avro-serializer-3.0.0.jar"
"file:/var/folders/fv/8ts3hqxj6l9d0lmf8cjhpq5svd3b4f/T/jruby3457062208861939657extract/connect-json-0.10.0.0.jar"
"file:/var/folders/fv/8ts3hqxj6l9d0lmf8cjhpq5svd3b4f/T/jruby3457062208861939657extract/jruby-stdlib-9.1.2.0.jar"
"file:/var/folders/fv/8ts3hqxj6l9d0lmf8cjhpq5svd3b4f/T/jruby3457062208861939657extract/slf4j-api-1.7.21.jar"
"file:/var/folders/fv/8ts3hqxj6l9d0lmf8cjhpq5svd3b4f/T/jruby3457062208861939657extract/jackson-core-2.6.3.jar"
"file:/var/folders/fv/8ts3hqxj6l9d0lmf8cjhpq5svd3b4f/T/jruby3457062208861939657extract/slf4j-log4j12-1.7.21.jar"
"file:/var/folders/fv/8ts3hqxj6l9d0lmf8cjhpq5svd3b4f/T/jruby3457062208861939657extract/zookeeper-3.4.6.jar"
"file:/var/folders/fv/8ts3hqxj6l9d0lmf8cjhpq5svd3b4f/T/jruby3457062208861939657extract/jackson-core-asl-1.9.13.jar"
"file:/var/folders/fv/8ts3hqxj6l9d0lmf8cjhpq5svd3b4f/T/jruby3457062208861939657extract/jackson-databind-2.6.3.jar"
"file:/var/folders/fv/8ts3hqxj6l9d0lmf8cjhpq5svd3b4f/T/jruby3457062208861939657extract/common-utils-3.0.0.jar"
"file:/var/folders/fv/8ts3hqxj6l9d0lmf8cjhpq5svd3b4f/T/jruby3457062208861939657extract/jline-0.9.94.jar"
"file:/var/folders/fv/8ts3hqxj6l9d0lmf8cjhpq5svd3b4f/T/jruby3457062208861939657extract/rocksdbjni-4.4.1.jar"
"file:/var/folders/fv/8ts3hqxj6l9d0lmf8cjhpq5svd3b4f/T/jruby3457062208861939657extract/scala-library-2.11.8.jar"
"file:/var/folders/fv/8ts3hqxj6l9d0lmf8cjhpq5svd3b4f/T/jruby3457062208861939657extract/junit-3.8.1.jar"
"file:/var/folders/fv/8ts3hqxj6l9d0lmf8cjhpq5svd3b4f/T/jruby3457062208861939657extract/xz-1.5.jar"
"file:/var/folders/fv/8ts3hqxj6l9d0lmf8cjhpq5svd3b4f/T/jruby3457062208861939657extract/jackson-mapper-asl-1.9.13.jar"
"file:/var/folders/fv/8ts3hqxj6l9d0lmf8cjhpq5svd3b4f/T/jruby3457062208861939657extract/commons-compress-1.8.1.jar"
"file:/var/folders/fv/8ts3hqxj6l9d0lmf8cjhpq5svd3b4f/T/jruby3457062208861939657extract/jackson-annotations-2.6.0.jar"
"file:/var/folders/fv/8ts3hqxj6l9d0lmf8cjhpq5svd3b4f/T/jruby3457062208861939657extract/mail-1.4.jar"
"file:/var/folders/fv/8ts3hqxj6l9d0lmf8cjhpq5svd3b4f/T/jruby3457062208861939657extract/paranamer-2.7.jar"
"file:/var/folders/fv/8ts3hqxj6l9d0lmf8cjhpq5svd3b4f/T/jruby3457062208861939657extract/jopt-simple-4.9.jar"
"file:/var/folders/fv/8ts3hqxj6l9d0lmf8cjhpq5svd3b4f/T/jruby3457062208861939657extract/metrics-core-2.2.0.jar"
"file:/var/folders/fv/8ts3hqxj6l9d0lmf8cjhpq5svd3b4f/T/jruby3457062208861939657extract/kafka_2.11-0.10.0.0.jar"
"file:/var/folders/fv/8ts3hqxj6l9d0lmf8cjhpq5svd3b4f/T/jruby3457062208861939657extract/snakeyaml-1.14.jar"
"file:/var/folders/fv/8ts3hqxj6l9d0lmf8cjhpq5svd3b4f/T/jruby3457062208861939657extract/netty-3.7.0.Final.jar"
"file:/var/folders/fv/8ts3hqxj6l9d0lmf8cjhpq5svd3b4f/T/jruby3457062208861939657extract/jruby-core-9.1.2.0-complete.jar"
"file:/var/folders/fv/8ts3hqxj6l9d0lmf8cjhpq5svd3b4f/T/jruby3457062208861939657extract/kafka-clients-0.10.0.0.jar"
["file:/var/folders/fv/8ts3hqxj6l9d0lmf8cjhpq5svd3b4f/T/jruby-17514/jruby6116253422275752779psych.jar", "file:/Users/cmeier/.m2/repository/org/yaml/snakeyaml/1.14/snakeyaml-1.14.jar"]
```

so the problem is that the classloader semantic is different from the packed jar versus the standalone.

the warbled jar puts all the jars into the application classloader, the standalone requires the jars which will end up inside the jruby-classloader. 

jars are loaded in both cases, not sure why the warbled jar is not working is not clear.

**Comment by kares** [comment]
as the trace suggest (and @mkristian noted) - this seems more like a Java issue specific to Kafka.
you should google around the exception : 
```
Caused by: org.apache.kafka.common.config.ConfigException: Invalid value org.apache.kafka.clients.producer.internals.DefaultPartitioner for configuration partitioner.class: Class org.apache.kafka.clients.producer.internals.DefaultPartitioner could not be found.
    at org.apache.kafka.common.config.ConfigDef.parseType(ConfigDef.java:672)
    at org.apache.kafka.common.config.ConfigDef.define(ConfigDef.java:110)
    at org.apache.kafka.common.config.ConfigDef.define(ConfigDef.java:132)
    at org.apache.kafka.common.config.ConfigDef.define(ConfigDef.java:171)
    at org.apache.kafka.common.config.ConfigDef.define(ConfigDef.java:333)
    at org.apache.kafka.common.config.ConfigDef.define(ConfigDef.java:346)
    at org.apache.kafka.clients.producer.ProducerConfig.<clinit>(ProducerConfig.java:222)
    at org.apache.kafka.clients.producer.KafkaProducer.<init>(KafkaProducer.java:178)
```
... or try to understand what's going on (any class-loader expectations) from the source code.

at JRuby/Warbler's end its pretty much a won't fix.

**Comment by aviflax** [comment]
@kares hmm, well then how do you account for the fact that this app works fine when I run it from the command line using `jruby`, i.e. as a “plain” Ruby app not packaged as a JAR. Couldn’t that imply that perhaps there’s some corner case that the classloader implemented/configured by Warbler doesn’t handle?

**Comment by aviflax** [comment]
@kares could it be related to this: [Kafka-0.9.0.0 does not work as OSGi module](https://issues.apache.org/jira/browse/KAFKA-3218)? This was apparently [fixed in Kafka trunk](https://github.com/apache/kafka/pull/888) but that change has not yet made it into a release.

**Comment by aviflax** [comment]
Ah, it looks like I jumped the gun — the changes in that PR were not actually merged. Looks like the Kafka maintainers are tracking this as [KIP-60](https://cwiki.apache.org/confluence/display/KAFKA/KIP-60+-+Make+Java+client+classloading+more+flexible) and [KAFKA-3680](https://issues.apache.org/jira/browse/KAFKA-3680) so it looks like this is a known issue with Kafka. Ah well, I’ll deal with it for now.

Thanks for the help!

**Comment by mkristian** [comment]
@aviflax but the warbler also changes the classloading semantics from what jruby uses standalone. when packing the jar with gradle and maven - which both keep the classloading semantics from the standalone app - then classes do load as expected.

https://gist.github.com/mkristian/52f1116aff149d7ea30e936221284e36

**Comment by aviflax** [comment]
@mkristian that’s really good to know! And that example looks super-helpful pointing the way for this n00b — thank you!!

(I was hoping to avoid using Maven in this project as I’m basically sick of it, but if that’s a mostly off-the-shelf way of packaging my app with all dependencies up into a single artifact, then it’ll be better for me to use that rather than reinvent it from scratch. BTW I’ve found that many things like this seem to be… under-documented in the JRuby world… or maybe at best the best practices are fragmented, scattered across dozens of different blogs or whatever. I’m surprised that no one has taken the initiative to gather them together into some kind of guide.)
