### ISSUE TITLE
Error running rake with runnable war (Windows)

### ISSUE THREAD

**Issue by fxgallego** [jruby/warbler#382]
I've encountered a problem when running rake with runnable wars. I can reproduce this having the gem 'sunspot_rails' installed. There is something wrong when a war with this gem bundled runs rake but deploying the same war to a server appears to work ok.
(**Edit: Appears to work ok because I've doing my tests in windows and linux. Rake runs ok in linux but it fails on windows**)

Here https://github.com/fxgallego/warbler-test I pushed a repo with a new rails project with the sunspot gem added (that's the only addition to the default Gemfile).

I've done  the following tests:
Without adding sunspot:
1) rake -T OK
2) warble runnable war OK
3) java -jar warbler-test.war -S rake -T OK

With sunspot_rails added:
1) rake -T OK
2) warble runnable war OK
3) java -jar warbler-test.war -S rake -T ERROR
4) java -jar warbler-test.war -S rake routes ERROR

```text
c:\JSC\Dev\Ruby\warbler-test>java -jar warbler-test.war -S rake routes
rake aborted!
Bundler::GemRequireError: There was an error while trying to load the gem 'sunspot_rails'.
Gem Load Error is: uninitialized constant RSolr::Char
Backtrace for gem load error is:
uri:classloader:/WEB-INF/gems/gems/rsolr-1.1.1/lib/rsolr.rb:12:in `<module:RSolr>'
uri:classloader:/WEB-INF/gems/gems/rsolr-1.1.1/lib/rsolr.rb:1:in `<top>'
uri:classloader:/WEB-INF/gems/gems/sunspot-2.2.5/lib/sunspot.rb:1:in `<top>'
uri:classloader:/WEB-INF/gems/gems/sunspot-2.2.5/lib/sunspot.rb:7:in `<top>'
uri:classloader:/WEB-INF/gems/gems/sunspot_rails-2.2.5/lib/sunspot/rails.rb:1:in `<top>'
uri:classloader:/WEB-INF/gems/gems/sunspot_rails-2.2.5/lib/sunspot/rails.rb:1:in `require'
uri:classloader:/WEB-INF/gems/gems/sunspot_rails-2.2.5/lib/sunspot/rails.rb:1:in `block in (root)'
uri:classloader:/WEB-INF/gems/gems/sunspot_rails-2.2.5/lib/sunspot_rails.rb:1:in `each'
uri:classloader:/WEB-INF/gems/gems/sunspot_rails-2.2.5/lib/sunspot_rails.rb:1:in `block in (root)'
uri:classloader:/WEB-INF/gems/gems/sunspot_rails-2.2.5/lib/sunspot_rails.rb:10:in `each'
uri:classloader:/WEB-INF/gems/gems/sunspot_rails-2.2.5/lib/sunspot_rails.rb:10:in `(root)'
C:/Users/SCALVO~1.INF/AppData/Local/Temp/jruby2676920818740234718extract/gems/gems/bundler-1.12.5/lib/bundler/runtime.rb:1:in `(root)'
C:/Users/SCALVO~1.INF/AppData/Local/Temp/jruby2676920818740234718extract/gems/gems/bundler-1.12.5/lib/bundler/runtime.rb:86:in `<top>'
C:/Users/SCALVO~1.INF/AppData/Local/Temp/jruby2676920818740234718extract/gems/gems/bundler-1.12.5/lib/bundler/runtime.rb:81:in `require'
C:/Users/SCALVO~1.INF/AppData/Local/Temp/jruby2676920818740234718extract/gems/gems/bundler-1.12.5/lib/bundler/runtime.rb:81:in `<top>'
C:/Users/SCALVO~1.INF/AppData/Local/Temp/jruby2676920818740234718extract/gems/gems/bundler-1.12.5/lib/bundler/runtime.rb:70:in `load'
C:/Users/SCALVO~1.INF/AppData/Local/Temp/jruby2676920818740234718extract/gems/gems/bundler-1.12.5/lib/bundler/runtime.rb:70:in `require'
C:/Users/SCALVO~1.INF/AppData/Local/Temp/jruby2676920818740234718extract/gems/gems/bundler-1.12.5/lib/bundler.rb:102:in `require'
C:/Users/scalvo.INFOIL/AppData/Local/Temp/jruby2676920818740234718extract/config/application.rb:7:in `block in (root)'
C:/Users/scalvo.INFOIL/AppData/Local/Temp/jruby2676920818740234718extract/rakefile:1:in `(root)'
C:/Users/scalvo.INFOIL/AppData/Local/Temp/jruby2676920818740234718extract/rakefile:4:in `(root)'
uri:classloader:/WEB-INF/gems/gems/rake-11.1.2/lib/rake/rake_module.rb:1:in `block in (root)'
uri:classloader:/WEB-INF/gems/gems/rake-11.1.2/lib/rake/rake_module.rb:28:in `load_rakefile'
uri:classloader:/WEB-INF/gems/gems/rake-11.1.2/lib/rake/application.rb:690:in `raw_load_rakefile'
uri:classloader:/WEB-INF/gems/gems/rake-11.1.2/bin/rake:35:in `<top>'
Bundler Error Backtrace:
C:/Users/SCALVO~1.INF/AppData/Local/Temp/jruby2676920818740234718extract/gems/gems/bundler-1.12.5/lib/bundler/runtime.rb:90:in `block in require'
C:/Users/SCALVO~1.INF/AppData/Local/Temp/jruby2676920818740234718extract/gems/gems/bundler-1.12.5/lib/bundler/runtime.rb:81:in `block in require'
C:/Users/SCALVO~1.INF/AppData/Local/Temp/jruby2676920818740234718extract/gems/gems/bundler-1.12.5/lib/bundler/runtime.rb:70:in `require'
C:/Users/SCALVO~1.INF/AppData/Local/Temp/jruby2676920818740234718extract/gems/gems/bundler-1.12.5/lib/bundler.rb:102:in `require'
C:/Users/scalvo.INFOIL/AppData/Local/Temp/jruby2676920818740234718extract/config/application.rb:7:in `<top>'
C:/Users/scalvo.INFOIL/AppData/Local/Temp/jruby2676920818740234718extract/rakefile:1:in `<top>'
C:/Users/scalvo.INFOIL/AppData/Local/Temp/jruby2676920818740234718extract/rakefile:4:in `(root)'
NameError: uninitialized constant RSolr::Char
uri:classloader:/WEB-INF/gems/gems/rsolr-1.1.1/lib/rsolr.rb:12:in `<module:RSolr>'
uri:classloader:/WEB-INF/gems/gems/rsolr-1.1.1/lib/rsolr.rb:1:in `<top>'
uri:classloader:/WEB-INF/gems/gems/sunspot-2.2.5/lib/sunspot.rb:1:in `<top>'
uri:classloader:/WEB-INF/gems/gems/sunspot-2.2.5/lib/sunspot.rb:7:in `<top>'
uri:classloader:/WEB-INF/gems/gems/sunspot_rails-2.2.5/lib/sunspot/rails.rb:1:in `<top>'
uri:classloader:/WEB-INF/gems/gems/sunspot_rails-2.2.5/lib/sunspot/rails.rb:1:in `require'
uri:classloader:/WEB-INF/gems/gems/sunspot_rails-2.2.5/lib/sunspot/rails.rb:1:in `block in (root)'
uri:classloader:/WEB-INF/gems/gems/sunspot_rails-2.2.5/lib/sunspot_rails.rb:1:in `each'
uri:classloader:/WEB-INF/gems/gems/sunspot_rails-2.2.5/lib/sunspot_rails.rb:1:in `block in (root)'
uri:classloader:/WEB-INF/gems/gems/sunspot_rails-2.2.5/lib/sunspot_rails.rb:10:in `each'
uri:classloader:/WEB-INF/gems/gems/sunspot_rails-2.2.5/lib/sunspot_rails.rb:10:in `(root)'
C:/Users/SCALVO~1.INF/AppData/Local/Temp/jruby2676920818740234718extract/gems/gems/bundler-1.12.5/lib/bundler/runtime.rb:1:in `(root)'
C:/Users/SCALVO~1.INF/AppData/Local/Temp/jruby2676920818740234718extract/gems/gems/bundler-1.12.5/lib/bundler/runtime.rb:86:in `<top>'
C:/Users/SCALVO~1.INF/AppData/Local/Temp/jruby2676920818740234718extract/gems/gems/bundler-1.12.5/lib/bundler/runtime.rb:81:in `require'
C:/Users/SCALVO~1.INF/AppData/Local/Temp/jruby2676920818740234718extract/gems/gems/bundler-1.12.5/lib/bundler/runtime.rb:81:in `<top>'
C:/Users/SCALVO~1.INF/AppData/Local/Temp/jruby2676920818740234718extract/gems/gems/bundler-1.12.5/lib/bundler/runtime.rb:70:in `load'
C:/Users/SCALVO~1.INF/AppData/Local/Temp/jruby2676920818740234718extract/gems/gems/bundler-1.12.5/lib/bundler/runtime.rb:70:in `require'
C:/Users/SCALVO~1.INF/AppData/Local/Temp/jruby2676920818740234718extract/gems/gems/bundler-1.12.5/lib/bundler.rb:102:in `require'
C:/Users/scalvo.INFOIL/AppData/Local/Temp/jruby2676920818740234718extract/config/application.rb:7:in `block in (root)'
C:/Users/scalvo.INFOIL/AppData/Local/Temp/jruby2676920818740234718extract/rakefile:1:in `(root)'
C:/Users/scalvo.INFOIL/AppData/Local/Temp/jruby2676920818740234718extract/rakefile:4:in `(root)'
(See full trace by running task with --trace)
ERROR: org.jruby.exceptions.RaiseException: (SystemExit) exit
```

This was tested on jruby 9.0.5.0 warbler 2.0.3 and Windows 10. As I pointed before there is no problem running the same code from Tomcat.

**Comment by fxgallego** [comment]
I've realized that using bundle exec (java -jar warbler-test.war -S bundle exec rake -T) works ok.

**Comment by fxgallego** [comment]
Well, in Linux rake runs without errors.
This appears to be only in windows and probably related to this https://github.com/jruby/jruby/issues/3197
I've tested under 9.1.2.0 (Windows 10) and the problem is still there.

**Comment by kares** [comment]
@fxgallego you could try patching bundler in a proper place to print the LOADED_FEATURES with the error. so than you can confirm its a require issue. alternatively `-Djruby.debug.loadService=true` system property with `java` - you should see what's being loaded.

**Comment by fxgallego** [comment]
@kares thanks to take care of this. I've done what you said but there is no LOADED_FEATURES defined when the error is raised. 
`NameError: uninitialized constant Bundler::GemRequireError::LOADED_FEATURES`
This is with Bundler 1.12.5 and my patch was in "lib\bundler\errors.rb". I've redeined the method #message as
```ruby
    def message
      "\nLOADED_FEATURES:\n#{LOADED_FEATURES}\n#{super}"
    end
```

Anyway, in my previous tests patching the Rsolr gem (1.1.1 \lib\rsolr.rb) I see the following, the code in that file begins as:
```ruby
module RSolr
  
  Dir.glob(File.expand_path("../rsolr/*.rb", __FILE__)).each{|rb_file| require(rb_file)}
  
  def self.connect *args
    driver = Class === args[0] ? args[0] : RSolr::Connection
    opts = Hash === args[-1] ? args[-1] : {}
    Client.new driver.new, opts
  end
  
  # RSolr.escape, which is deprecated as of 2015-02
  extend Char
```
The last line `extend Char`is causing the name error because it is assumed that the require in the beginning of the file runs as expected.
But the require never runs because `File.expand_path("../rsolr/*.rb", __FILE__)` returns **no results** when it is executed in Windows inside a jar. And that's when I reach to https://github.com/jruby/jruby/issues/3197

Sorry for the delay, I'm not a ruby expert so maybe I misunderstood the instructions about the LOADED_FEATURES patch but I think anyway the point is clear. If you need more concise evidence please let me know.

I could help debugging jruby but I hadn't time right now.

**Comment by kares** [comment]
OK, so it's confirmed to be a JRuby (Windows specific bug) ... seems there's nothing we can do here.
also for the record its `$LOADED_FEATURES` ... since it's a global constant.
