### ISSUE TITLE
TypeError: no implicit conversion from nil to integer -- on jruby-9.0.5.0

### ISSUE THREAD

**Issue by sputnikgugja** [jruby/warbler#394]
```
warble aborted!
TypeError: no implicit conversion from nil to integer
/usr/local/rvm/gems/jruby-9.0.5.0/gems/warbler-1.4.9/lib/warbler/traits/bundler.rb:129:in `relative_from_pwd'
/usr/local/rvm/gems/jruby-9.0.5.0/gems/warbler-1.4.9/lib/warbler/traits/bundler.rb:76:in `add_bundler_gems'
/usr/local/rvm/gems/jruby-9.0.5.0/gems/warbler-1.4.9/lib/warbler/traits/bundler.rb:31:in `after_configure'
/usr/local/rvm/gems/jruby-9.0.5.0/gems/warbler-1.4.9/lib/warbler/traits.rb:33:in `block in after_configure'
/usr/local/rvm/gems/jruby-9.0.5.0/gems/warbler-1.4.9/lib/warbler/traits.rb:33:in `after_configure'
/usr/local/rvm/gems/jruby-9.0.5.0/gems/warbler-1.4.9/lib/warbler/config.rb:215:in `initialize'
/usr/local/rvm/gems/jruby-9.0.5.0/gems/warbler-1.4.9/lib/warbler/task.rb:48:in `initialize'
/usr/local/rvm/gems/jruby-9.0.5.0/gems/warbler-1.4.9/lib/warbler/application.rb:27:in `load_rakefile'
/usr/local/rvm/gems/jruby-9.0.5.0/gems/warbler-1.4.9/lib/warbler/application.rb:77:in `run'
/usr/local/rvm/gems/jruby-9.0.5.0/gems/warbler-1.4.9/bin/warble:11:in `<top>'
/usr/local/rvm/gems/jruby-9.0.5.0/bin/warble:1:in `<eval>'
/usr/local/rvm/gems/jruby-9.0.5.0/bin/jruby_executable_hooks:15:in `<top>'
```
when run `warble` on jruby-9.0.5.0

I have tested warbler-2.0.3, 2.0.0, and 1.4.9. All of those raises it. but on jruby-1.7.23 and warbler-1.4.9, it is not raised

(Ubuntu 16.04 32bit)

**Comment by kares** [comment]
Warbler 1.x is meant for JRuby 1.7 while 2.x uses 9k versions of packed jruby-jars ...you should confirm whether issue is still present on latest 2.0 using latest JRuby 9.1
