### ISSUE TITLE
Exception when deploying on Tomcat

### ISSUE THREAD

**Issue by F2Andy** [jruby/warbler#417]
I am getting a `org.jruby.rack.RackInitializationException: java.lang.NullPointerException` error when I deploy my .war to Tomcat. My project has run fine in the past, and this seems to be a recent issue. I am trying to get two apps to run on one Tomcat, o have updated various bits, and I am not sure which part is causing the error. However, it happens with a new, empty project, so it is not my code!

I have  Rails 4.2.9, JRuby 9.1.12 (64 bit), Java 1.8.0.131 (64 bit), Tomcat 8.5.16 (64 bit), Warbler 2.0.4 on Windows 7 Pro.

Here is an empty project being created, tested and warbled:
```
R:\>rails new testy
      create
      ... etc

R:\>cd testy

R:\testy>rake routes
You don't have any routes defined!
Please add some routes in config/routes.rb.
For more information about routes, see the Rails guide: http://guides.rubyonr

R:\testy>rails c
Loading development environment (Rails 4.2.9)
irb(main):001:0> exit

R:\testy>rails s
=> Booting WEBrick
=> Rails 4.2.9 application starting in development on http://localhost:3000
=> Run `rails server -h` for more startup options
=> Ctrl-C to shutdown server
[2017-07-05 09:06:01] INFO  WEBrick 1.3.1
[2017-07-05 09:06:01] INFO  ruby 2.3.3 (2017-06-15) [java]
[2017-07-05 09:06:01] INFO  WEBrick::HTTPServer#start: pid=8056 port=3000

Started GET "/" for 0:0:0:0:0:0:0:1 at 2017-07-05 09:11:12 +0100
Processing by Rails::WelcomeController#index as HTML
  Rendered C:/jruby/jruby-9.1.12.0/lib/ruby/gems/shared/gems/railties-4.2.9/lib/rails/templates/rails/welcome/index.html.erb (38.0ms)
Completed 200 OK in 651ms (Views: 209.1ms | ActiveRecord: 0.0ms)
[2017-07-05 09:11:24] INFO  going to shutdown ...
[2017-07-05 09:11:24] INFO  WEBrick::HTTPServer#start done.
Exiting
Terminate batch job (Y/N)? y

R:\testy>warble
rm -f testy.war
Creating testy.war
```

I can see the Tomcat manager page, but when going to the app, I see this:
```
org.jruby.rack.RackInitializationException: java.lang.NullPointerException
	at org.jruby.rack.RackInitializationException.wrap(RackInitializationException.java:31)
	at org.jruby.rack.RackApplicationFactoryDecorator.init(RackApplicationFactoryDecorator.java:104)
	at org.jruby.rack.RackServletContextListener.contextInitialized(RackServletContextListener.java:50)
	at org.apache.catalina.core.StandardContext.listenerStart(StandardContext.java:4745)
	at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5207)
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:150)
	at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:752)
	at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:728)
	at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:734)
	at org.apache.catalina.startup.HostConfig.deployWAR(HostConfig.java:988)
	at org.apache.catalina.startup.HostConfig$DeployWar.run(HostConfig.java:1860)
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
Caused by: java.lang.NullPointerException
	at java.lang.String.getBytes(Unknown Source)
	at org.jruby.ast.SymbolNode.<init>(SymbolNode.java:54)
	at org.jruby.parser.ParserSupport.asSymbol(ParserSupport.java:975)
	at org.jruby.parser.RubyParser$379.execute(RubyParser.java:4286)
	at org.jruby.parser.RubyParser.yyparse(RubyParser.java:1677)
	at org.jruby.parser.RubyParser.yyparse(RubyParser.java:1568)
	at org.jruby.parser.RubyParser.parse(RubyParser.java:5365)
	at org.jruby.parser.Parser.parse(Parser.java:128)
	at org.jruby.parser.Parser.parse(Parser.java:77)
	at org.jruby.Ruby.parseEval(Ruby.java:2722)
	at org.jruby.ir.interpreter.Interpreter.prepareIC(Interpreter.java:211)
	at org.jruby.ir.interpreter.Interpreter.evalCommon(Interpreter.java:167)
	at org.jruby.ir.interpreter.Interpreter.evalWithBinding(Interpreter.java:200)
	at org.jruby.RubyKernel.evalCommon(RubyKernel.java:1033)
	at org.jruby.RubyKernel.eval19(RubyKernel.java:1000)
	at org.jruby.RubyKernel$INVOKER$s$0$3$eval19.call(RubyKernel$INVOKER$s$0$3$eval19.gen)
	at org.jruby.runtime.callsite.CachingCallSite.cacheAndCall(CachingCallSite.java:298)
	at org.jruby.runtime.callsite.CachingCallSite.callBlock(CachingCallSite.java:79)
	at org.jruby.runtime.callsite.CachingCallSite.call(CachingCallSite.java:83)
	at org.jruby.ir.instructions.CallBase.interpret(CallBase.java:428)
	at org.jruby.ir.interpreter.InterpreterEngine.processCall(InterpreterEngine.java:355)
	at org.jruby.ir.interpreter.StartupInterpreterEngine.interpret(StartupInterpreterEngine.java:73)
	at org.jruby.ir.interpreter.Interpreter.INTERPRET_BLOCK(Interpreter.java:132)
	at org.jruby.runtime.MixedModeIRBlockBody.commonYieldPath(MixedModeIRBlockBody.java:148)
	at org.jruby.runtime.IRBlockBody.doYield(IRBlockBody.java:186)
	at org.jruby.runtime.BlockBody.yield(BlockBody.java:116)
	at org.jruby.runtime.Block.yield(Block.java:165)
	at org.jruby.RubyArray.each(RubyArray.java:1734)
	at org.jruby.RubyArray$INVOKER$i$0$0$each.call(RubyArray$INVOKER$i$0$0$each.gen)
	at org.jruby.internal.runtime.methods.JavaMethod$JavaMethodZeroBlock.call(JavaMethod.java:498)
	at org.jruby.runtime.callsite.CachingCallSite.cacheAndCall(CachingCallSite.java:298)
	at org.jruby.runtime.callsite.CachingCallSite.callBlock(CachingCallSite.java:79)
	at org.jruby.runtime.callsite.CachingCallSite.call(CachingCallSite.java:83)
	at org.jruby.ir.instructions.CallBase.interpret(CallBase.java:428)
	at org.jruby.ir.interpreter.InterpreterEngine.processCall(InterpreterEngine.java:355)
	at org.jruby.ir.interpreter.StartupInterpreterEngine.interpret(StartupInterpreterEngine.java:73)
	at org.jruby.ir.interpreter.InterpreterEngine.interpret(InterpreterEngine.java:77)
	at org.jruby.internal.runtime.methods.MixedModeIRMethod.INTERPRET_METHOD(MixedModeIRMethod.java:144)
	at org.jruby.internal.runtime.methods.MixedModeIRMethod.call(MixedModeIRMethod.java:130)
	at org.jruby.internal.runtime.methods.DynamicMethod.call(DynamicMethod.java:192)
	at org.jruby.runtime.callsite.CachingCallSite.cacheAndCall(CachingCallSite.java:318)
	at org.jruby.runtime.callsite.CachingCallSite.call(CachingCallSite.java:131)
	at org.jruby.ir.interpreter.InterpreterEngine.processCall(InterpreterEngine.java:339)
	at org.jruby.ir.interpreter.StartupInterpreterEngine.interpret(StartupInterpreterEngine.java:73)
	at org.jruby.internal.runtime.methods.MixedModeIRMethod.INTERPRET_METHOD(MixedModeIRMethod.java:109)
	at org.jruby.internal.runtime.methods.MixedModeIRMethod.call(MixedModeIRMethod.java:95)
	at org.jruby.ir.runtime.IRRuntimeHelpers.instanceSuper(IRRuntimeHelpers.java:983)
	at org.jruby.ir.instructions.InstanceSuperInstr.interpret(InstanceSuperInstr.java:69)
	at org.jruby.ir.interpreter.InterpreterEngine.processCall(InterpreterEngine.java:355)
	at org.jruby.ir.interpreter.StartupInterpreterEngine.interpret(StartupInterpreterEngine.java:73)
	at org.jruby.ir.interpreter.InterpreterEngine.interpret(InterpreterEngine.java:77)
	at org.jruby.internal.runtime.methods.MixedModeIRMethod.INTERPRET_METHOD(MixedModeIRMethod.java:144)
	at org.jruby.internal.runtime.methods.MixedModeIRMethod.call(MixedModeIRMethod.java:130)
	at org.jruby.internal.runtime.methods.DynamicMethod.call(DynamicMethod.java:192)
	at org.jruby.runtime.callsite.CachingCallSite.cacheAndCall(CachingCallSite.java:318)
	at org.jruby.runtime.callsite.CachingCallSite.call(CachingCallSite.java:131)
	at org.jruby.ir.interpreter.InterpreterEngine.processCall(InterpreterEngine.java:339)
	at org.jruby.ir.interpreter.StartupInterpreterEngine.interpret(StartupInterpreterEngine.java:73)
	at org.jruby.ir.interpreter.Interpreter.INTERPRET_ROOT(Interpreter.java:112)
	at org.jruby.ir.interpreter.Interpreter.execute(Interpreter.java:99)
	at org.jruby.ir.interpreter.Interpreter.execute(Interpreter.java:35)
	at org.jruby.ir.IRTranslator.execute(IRTranslator.java:42)
	at org.jruby.Ruby.runInterpreter(Ruby.java:839)
	at org.jruby.Ruby.loadFile(Ruby.java:2876)
	at org.jruby.runtime.load.LibrarySearcher$ResourceLibrary.load(LibrarySearcher.java:243)
	at org.jruby.runtime.load.LibrarySearcher$FoundLibrary.load(LibrarySearcher.java:34)
	at org.jruby.runtime.load.LoadService.load(LoadService.java:343)
	at org.jruby.RubyKernel.loadCommon(RubyKernel.java:987)
	at org.jruby.RubyKernel.load19(RubyKernel.java:979)
	at org.jruby.RubyKernel$INVOKER$s$0$1$load19.call(RubyKernel$INVOKER$s$0$1$load19.gen)
	at org.jruby.internal.runtime.methods.DynamicMethod.call(DynamicMethod.java:204)
	at org.jruby.internal.runtime.methods.DynamicMethod.call(DynamicMethod.java:200)
	at org.jruby.runtime.callsite.CachingCallSite.cacheAndCall(CachingCallSite.java:338)
	at org.jruby.runtime.callsite.CachingCallSite.call(CachingCallSite.java:163)
	at org.jruby.ir.interpreter.InterpreterEngine.processCall(InterpreterEngine.java:314)
	at org.jruby.ir.interpreter.StartupInterpreterEngine.interpret(StartupInterpreterEngine.java:73)
	at org.jruby.ir.interpreter.Interpreter.INTERPRET_ROOT(Interpreter.java:112)
	at org.jruby.ir.interpreter.Interpreter.execute(Interpreter.java:99)
	at org.jruby.ir.interpreter.Interpreter.execute(Interpreter.java:35)
	at org.jruby.ir.IRTranslator.execute(IRTranslator.java:42)
	at org.jruby.Ruby.evalScriptlet(Ruby.java:479)
	at org.jruby.Ruby.evalScriptlet(Ruby.java:455)
	at org.jruby.rack.rails.RailsRackApplicationFactory.createApplicationObject(RailsRackApplicationFactory.java:21)
	at org.jruby.rack.DefaultRackApplicationFactory$1.create(DefaultRackApplicationFactory.java:101)
	at org.jruby.rack.DefaultRackApplicationFactory$RackApplicationImpl.init(DefaultRackApplicationFactory.java:445)
	at org.jruby.rack.DefaultRackApplicationFactory.getApplication(DefaultRackApplicationFactory.java:114)
	at org.jruby.rack.SharedRackApplicationFactory.doInit(SharedRackApplicationFactory.java:34)
	at org.jruby.rack.RackApplicationFactoryDecorator.init(RackApplicationFactoryDecorator.java:100)
	... 14 more
```
Not sure if it is Warbler, to be fair, I am just pointing the finger because Warbler is the glue between Tomcat and JRuby/Rails.

**Comment by F2Andy** [comment]
I think this is a JRuby issue. I got it to work with Rails 4.2.9, JRuby 9.1.2 (32 bit), Java 1.8.0.131 (32 bit), Tomcat 8.0.45 (32 bit), Warbler 2.0.4 on Windows 7 Pro, so will close it.
