### ISSUE TITLE
Warbler doesn't appear to pull in all necessary dependencies from Jarfile

### ISSUE THREAD

**Issue by Taywee** [jruby/warbler#435]
In this case, I'm using the h2 database.  When I use jbundler directly, it appears to work, but after a run through bundler, it finds the h2 engine, but not the dependent h2-mvstore.

Full example:

```sh
$ pwd            
/tmp/warbletest
```

## Gemfile

```ruby
gem "warbler", "~> 2.0"
gem 'jbundler', '~> 0.9'
```

## Jarfile

```ruby
jar 'com.h2database:h2', '1.4.197'
```

## bin/main.rb

```ruby
#!/usr/bin/env ruby

begin
  require 'jbundler'
rescue LoadError
  # This will fail when wrapped in a jar
end

Java::org.h2.Driver

connection = Java::java.sql.DriverManager.get_connection('jdbc:h2:/tmp/h2-warbler-test.db')
connection.auto_commit = false

statement = connection.create_statement
statement.execute_update 'CREATE TABLE IF NOT EXISTS foo (a INTEGER, b CLOB, c BOOLEAN)'
statement.execute_update 'INSERT INTO foo (a, b, c) VALUES (5, \'test\', TRUE)'
connection.commit
```

## Execution

```sh
$ ./bin/main.rb 

$ warble 
No executable matching config.jar_name found, using bin/main.rb
rm -f warbletest.jar
Creating warbletest.jar

$ java -jar warbletest.jar 
Exception in thread "Thread-4" java.lang.NoClassDefFoundError: org/h2/mvstore/MVMap$2
	at org.h2.mvstore.MVMap.entrySet(MVMap.java:827)
	at org.h2.store.LobStorageMap.removeAllForTable(LobStorageMap.java:301)
	at org.h2.engine.Database.removeOrphanedLobs(Database.java:1381)
	at org.h2.engine.Database.close(Database.java:1300)
	at org.h2.engine.DatabaseCloser.run(DatabaseCloser.java:63)
Caused by: java.lang.ClassNotFoundException: org.h2.mvstore.MVMap$2
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 5 more
```

Note that it still happens the same even when I explicitly put the h2-mvstore dependency in the Jarfile.  I haven't been able to find a workaround so far.

**Comment by kares** [comment]
might be an edgy case, you could try "forcing" JRuby's class-loader to be the context-loader during boot.
`require 'jruby'; JRuby.set_context_class_loader` if works Warbler could/should? maybe set it for you

**Comment by Taywee** [comment]
Where should that live?  I put that in my main.rb at the top, and it still fails with the same error.

I've noticed that when I explicitly put h2-mvstore in the jarfile, then it does actually end up in ./META-INF/lib/h2-mvstore-1.4.197.jar in the jar, but otherwise it is absent.  Even when it's in there, the class isn't found, so the jar doesn't appear to end up properly referenced.

**Comment by Taywee** [comment]
I found some interesting things here.  If I explicitly load in the classes in my ruby, it works:

```ruby
...
require 'java'

Java::org.h2.Driver
Java::org.h2.mvstore.const_get('MVMap$2')
Java::org.h2.mvstore.const_get('MVMap$2$1')
Java::org.h2.mvstore.WriteBuffer

connection = Java::java.sql.DriverManager.get_connection('jdbc:h2:/tmp/h2-warbler-test.db')
...
```

This works correctly.  If I don't reference those classes in the main.rb file, I get the NoClassDefFoundError.  I don't actually know a whole lot about Java.  Might this be an issue with how h2 itself is packaged?

**Comment by Taywee** [comment]
It does look like warbler's JarMain always uses URLClassLoader, where the JRuby Main class uses the context class loader.  I assume that might have something to do with it.

**Comment by mkristian** [comment]
so you are talking about an executable jar which does have a different
classloading semantic then running an application in war-file.

this file worked for me:
```
JRuby.set_context_class_loader

connection =
Java::java.sql.DriverManager.get_connection('jdbc:h2:/tmp/h2-warbler-test.db')
connection.auto_commit = false

statement = connection.create_statement
statement.execute_update 'CREATE TABLE IF NOT EXISTS foo (a INTEGER, b
CLOB, c BOOLEAN)'
statement.execute_update 'INSERT INTO foo (a, b, c) VALUES (5, \'test\',
TRUE)'
connection.commit
```

note that I do not load ny Driver class before and important is the
set_context_class_loader to be the very first statement.

**Comment by Taywee** [comment]
Doesn't work for me, even if I do the set_context_class_loader as the very first statement.  This is my main.rb file here:

```ruby
JRuby.set_context_class_loader

connection = Java::java.sql.DriverManager.get_connection('jdbc:h2:/tmp/h2-warbler-test.db')
connection.auto_commit = false

statement = connection.create_statement
statement.execute_update 'CREATE TABLE IF NOT EXISTS foo (a INTEGER, b CLOB, c BOOLEAN)'
statement.execute_update 'INSERT INTO foo (a, b, c) VALUES (5, \'test\', TRUE)'
connection.commit
```

And when I run it:

```sh
$ warble
No executable matching config.jar_name found, using bin/main.rb
rm -f warbletest.jar
Creating warbletest.jar

$ java -jar warbletest.jar
Exception in thread "Thread-3" java.lang.NoClassDefFoundError: org/h2/mvstore/MVMap$2
	at org.h2.mvstore.MVMap.entrySet(MVMap.java:827)
	at org.h2.store.LobStorageMap.removeAllForTable(LobStorageMap.java:301)
	at org.h2.engine.Database.removeOrphanedLobs(Database.java:1381)
	at org.h2.engine.Database.close(Database.java:1300)
	at org.h2.engine.DatabaseCloser.run(DatabaseCloser.java:63)
Caused by: java.lang.ClassNotFoundException: org.h2.mvstore.MVMap$2
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 5 more
```

**Comment by mkristian** [comment]
that is strange as I did see your problem and I looked at the classloader-hierarchy and this setup just worked for me.

then I see only your way to hard load these three classes

**Comment by Taywee** [comment]
Maybe it's a JVM difference, I'm using:

```
$ java -version
openjdk version "1.8.0_171"
OpenJDK Runtime Environment (IcedTea 3.8.0) (Gentoo icedtea-3.8.0)
OpenJDK 64-Bit Server VM (build 25.171-b11, mixed mode)
```

Honestly, having to explicitly specify classes I need is an acceptable workaround for me here.  It would be good to get to the root of what's causing the issue (whether in Warbler or H2), but despite needing some ugly-looking hacks to get it working, it's not holding me back.

**Comment by chadlwilson** [comment]
We've deprecated jbundler, so an appropriate approach will be needed with jar-dependencies or similar.
