### ISSUE TITLE
Ruby On rails  app jruby after war deployed: Error org.jruby.exceptions.RaiseException: (SystemExit) 

### ISSUE THREAD

**Issue by joshianand** [jruby/warbler#449]
Created simple Ruby on Rails app and converted it to War file use warbler, the war created via warbler canoot be directly moved to tomcat8.5 as it says there is error with web-INF\..\ file which cannot be expanded to tomcat webapps URL , removed that WEB-INF entry using 

zip -d RubyOnRails.war WEB-INF/../

After this tomcat is able to unwrap the application but when I try to access it via url 

Request Method: | GET
-- | --
http://localhost:8080/RubyOnRails/

exit from org/jruby/RubyKernel.java:742:in `exit' from org/jruby/RubyKernel.java:705:in `exit' from D:/tomcat/apache-tomcat-8.5.38/webapps/RubyOnRails/WEB-INF/gems/gems/bundler-2.0.1/lib/bundler/setup.rb:17:in `<main>' from org/jruby/RubyKernel.java:984:in `require' from uri:classloader:/META-INF/jruby.home/lib/ruby/stdlib/rubygems/core_ext/kernel_require.rb:1:in `(root)' from uri:classloader:/META-INF/jruby.home/lib/ruby/stdlib/rubygems/core_ext/kernel_require.rb:59:in `<main>' from org/jruby/RubyKernel.java:984:in `require' from D:/tomcat/apache-tomcat-8.5.38/webapps/RubyOnRails/WEB-INF/config/boot.rb:3:in `<main>' from uri:classloader:/META-INF/jruby.home/lib/ruby/stdlib/rubygems/core_ext/kernel_require.rb:1:in `(root)' from uri:classloader:/META-INF/jruby.home/lib/ruby/stdlib/rubygems/core_ext/kernel_require.rb:59:in `require' from uri:classloader:/jruby/rack/rails/environment3.rb:23:in `<main>'

This is the error that I get , If I check line 3 of boot.rb it requires bundler which some how is not complied to war file 

@kares this is similar to ticket number #172, #173

**Comment by plrthink** [comment]
Also ran into this issue, even tried the code on the master branch but still failed with this error. 

One thing I noticed it complains `You must use Bundler 2 or greater with this lockfile.`, seems like warbled app doesn't find the right version of bundler to start up it.

**Comment by joshianand** [comment]
Only waay I could amke it work was to remove teh WEB-INf inside the war file
