### ISSUE TITLE
Rails 2.3.14, warbler 1.3.2: undefined method `gems' for #<Rails::VendorGemSourceIndex>

### ISSUE THREAD

**Issue by heisee** [jruby/warbler#46]
Hi all,

when I use warbler with a Rails 2.3.14 application I get:

```ruby
hk@hk:~/ws/nwd/demo$ jruby -J-Xmx1500m -S warble war --trace
** Erubis 2.7.0
warble aborted!
undefined method `gems' for #<Rails::VendorGemSourceIndex:0x73b8dc93>
/home/hk/.rvm/gems/jruby-1.6.3@demo/gems/bundler-1.0.18/lib/bundler/rubygems_integration.rb:270:in `all_specs'
/home/hk/.rvm/gems/jruby-1.6.3@demo/gems/bundler-1.0.18/lib/bundler/source.rb:178:in `installed_specs'
/home/hk/.rvm/gems/jruby-1.6.3@demo/gems/bundler-1.0.18/lib/bundler/source.rb:170:in `fetch_specs'
/home/hk/.rvm/gems/jruby-1.6.3@demo/gems/bundler-1.0.18/lib/bundler/source.rb:70:in `specs'
/home/hk/.rvm/gems/jruby-1.6.3@demo/gems/bundler-1.0.18/lib/bundler/definition.rb:159:in `index'
org/jruby/RubyArray.java:1603:in `each'
/home/hk/.rvm/gems/jruby-1.6.3@demo/gems/bundler-1.0.18/lib/bundler/definition.rb:158:in `index'
/home/hk/.rvm/gems/jruby-1.6.3@demo/gems/bundler-1.0.18/lib/bundler/index.rb:7:in `build'
/home/hk/.rvm/gems/jruby-1.6.3@demo/gems/bundler-1.0.18/lib/bundler/definition.rb:157:in `index'
/home/hk/.rvm/gems/jruby-1.6.3@demo/gems/bundler-1.0.18/lib/bundler/definition.rb:151:in `resolve'
/home/hk/.rvm/gems/jruby-1.6.3@demo/gems/bundler-1.0.18/lib/bundler/definition.rb:90:in `specs'
/home/hk/.rvm/gems/jruby-1.6.3@demo/gems/bundler-1.0.18/lib/bundler/definition.rb:135:in `specs_for'
/home/hk/.rvm/gems/jruby-1.6.3@demo/gems/bundler-1.0.18/lib/bundler/definition.rb:124:in `requested_specs'
/home/hk/.rvm/gems/jruby-1.6.3@demo/gems/warbler-1.3.2/lib/warbler/traits/bundler.rb:102:in `bundler_specs'
/home/hk/.rvm/gems/jruby-1.6.3@demo/gems/warbler-1.3.2/lib/warbler/traits/bundler.rb:38:in `add_bundler_gems'
/home/hk/.rvm/gems/jruby-1.6.3@demo/gems/warbler-1.3.2/lib/warbler/traits/bundler.rb:29:in `after_configure'
/home/hk/.rvm/gems/jruby-1.6.3@demo/gems/warbler-1.3.2/lib/warbler/traits.rb:32:in `after_configure'
org/jruby/RubyArray.java:1603:in `each'
/home/hk/.rvm/gems/jruby-1.6.3@demo/gems/warbler-1.3.2/lib/warbler/traits.rb:32:in `after_configure'
/home/hk/.rvm/gems/jruby-1.6.3@demo/gems/warbler-1.3.2/lib/warbler/config.rb:172:in `initialize'
(eval):5:in `initialize'
org/jruby/RubyKernel.java:1088:in `eval'
/home/hk/.rvm/gems/jruby-1.6.3@demo/gems/warbler-1.3.2/lib/warbler/task.rb:46:in `initialize'
/home/hk/.rvm/gems/jruby-1.6.3@demo/gems/warbler-1.3.2/lib/warbler/application.rb:27:in `load_rakefile'
/home/hk/.rvm/gems/jruby-1.6.3@global/gems/rake-0.9.2/lib/rake/application.rb:61:in `run'
/home/hk/.rvm/gems/jruby-1.6.3@global/gems/rake-0.9.2/lib/rake/application.rb:129:in `standard_exception_handling'
/home/hk/.rvm/gems/jruby-1.6.3@global/gems/rake-0.9.2/lib/rake/application.rb:59:in `run'
/home/hk/.rvm/gems/jruby-1.6.3@demo/gems/warbler-1.3.2/lib/warbler/application.rb:70:in `run'
/home/hk/.rvm/gems/jruby-1.6.3@demo/gems/warbler-1.3.2/bin/warble:11:in `(root)'
org/jruby/RubyKernel.java:1063:in `load'
/home/hk/.rvm/gems/jruby-1.6.3@demo/bin/warble:19:in `(root)'
hk@hk:~/ws/nwd/demo$ 
```
gem env:
```ruby
hk@hk:~/ws/nwd$ gem env
RubyGems Environment:
  - RUBYGEMS VERSION: 1.5.1
  - RUBY VERSION: 1.8.7 (2011-07-07 patchlevel 330) [java]
  - INSTALLATION DIRECTORY: /home/hk/.rvm/gems/jruby-1.6.3@demo
  - RUBY EXECUTABLE: /home/hk/.rvm/rubies/jruby-1.6.3/bin/jruby
  - EXECUTABLE DIRECTORY: /home/hk/.rvm/gems/jruby-1.6.3@demo/bin
  - RUBYGEMS PLATFORMS:
    - ruby
    - universal-java-1.6
  - GEM PATHS:
     - /home/hk/.rvm/gems/jruby-1.6.3@demo
     - /home/hk/.rvm/gems/jruby-1.6.3@global
  - GEM CONFIGURATION:
     - :update_sources => true
     - :verbose => true
     - :benchmark => false
     - :backtrace => false
     - :bulk_threshold => 1000
     - "install" => "--no-rdoc --no-ri"
     - "update" => "--no-rdoc --no-ri"
  - REMOTE SOURCES:
     - http://rubygems.org/
hk@hk:~/ws/nwd$ 
```

With warbler 1.3.0 it still worked.
Hmm, any ideas? 
Is anybody able to build a Rails 2.3.x application successfully with Warbler 1.3.2?

Thanks for your help,  Heiko

**Comment by kares** [comment]
old one. bundler's vendored gems are known to be working these days. not sure about Rails 2.3 anymore :)
