### ISSUE TITLE
nested gems in Gemfile from git repository are not warbled correctly

### ISSUE THREAD

**Issue by samuelkadolph** [jruby/warbler#47]
I have

``` ruby
gem "activerecord-jdbcmysql-adapter", :git => "https://github.com/nicksieger/activerecord-jdbc-adapter"
```

in my `Gemfile` and when I warble my application it does not work because bundler throws an error.

```
https://github.com/nicksieger/activerecord-jdbc-adapter (at master) is not checked out. Please run `bundle install`
[webapp 2011/08/24 21:51:57] - Warning: no min runtimes specified.
[webapp 2011/08/24 21:51:57] - Warning: no max runtimes specified.
[webapp 2011/08/24 21:51:57] - An exception happened during JRuby-Rack startup
exit
--- System
jruby 1.6.4 (ruby-1.9.2-p136) (2011-08-23 17ea768) (Java HotSpot(TM) 64-Bit Server VM 1.6.0_26) [darwin-x86_64-java]
Time: 2011-08-24 21:51:57 -0400
Server: Winstone Servlet Engine v0.9.10
jruby.home: file:/Users/samuelkadolph/foo/WEB-INF/lib/jruby-stdlib-1.6.4.jar!/META-INF/jruby.home

--- Context Init Parameters:
jruby.compat.version = 1.9
public.root = /
rails.env = production

--- Backtrace
SystemExit: exit
              exit at org/jruby/RubyKernel.java:867
              exit at org/jruby/RubyKernel.java:836
            (root) at /Users/samuelkadolph/foo/WEB-INF/gems/gems/bundler-1.0.18/lib/bundler/setup.rb:14
           require at org/jruby/RubyKernel.java:1047
           require at /Users/samuelkadolph/foo/WEB-INF/gems/gems/bundler-1.0.18/lib/bundler/setup.rb:32
            (root) at /Users/samuelkadolph/foo/WEB-INF/config/boot.rb:6
           require at org/jruby/RubyKernel.java:1047
           require at /Users/samuelkadolph/foo/WEB-INF/config/boot.rb:29
  load_environment at file:/Users/samuelkadolph/foo/WEB-INF/lib/jruby-rack-1.0.9.jar!/jruby/rack/rails.rb:165
            to_app at file:/Users/samuelkadolph/foo/WEB-INF/lib/jruby-rack-1.0.9.jar!/jruby/rack/rails.rb:173
               new at file:/Users/samuelkadolph/foo/WEB-INF/lib/jruby-rack-1.0.9.jar!/jruby/rack/rails.rb:193
            (root) at <web.xml>:1
     instance_eval at org/jruby/RubyBasicObject.java:1717
        initialize at file:/Users/samuelkadolph/foo/WEB-INF/lib/jruby-rack-1.0.9.jar!/vendor/rack-1.2.2/rack/builder.rb:46
            (root) at <web.xml>:1

--- RubyGems
Gem.dir: /Users/samuelkadolph/.rvm/gems/ruby-1.9.2-p290
Gem.path:
/Users/samuelkadolph/foo/WEB-INF/gems
/Users/samuelkadolph/.rvm/gems/ruby-1.9.2-p290
/Users/samuelkadolph/.rvm/gems/ruby-1.9.2-p290@global
Activated gems:
  bundler-1.0.18

--- Bundler
Bundler.bundle_path: /Users/samuelkadolph/.rvm/gems/ruby-1.9.2-p290
Bundler.root: /Users/samuelkadolph/foo/WEB-INF
Gemfile: Gemfile
Settings:
  without = development:test:assets
  gemfile = Gemfile

--- JRuby-Rack Config
background_spooling = false
compat_version = RUBY1_9
filter_adds_html = true
filter_verifies_resource = false
ignore_environment = false
initial_runtimes = 
jms_connection_factory = 
jms_jndi_properties = 
logger = org.jruby.rack.logging.ServletContextLogger@230cc23b
logger_class_name = servlet_context
logger_name = jruby.rack
maximum_runtimes = 
memory_buffer_size = 65536
num_initializer_threads = 
rackup = 
rackup_path = 
rewindable = true
runtime_timeout_seconds = 
serial_initialization = false
servlet_context = winstone.WebAppConfiguration@3162a60a

[webapp 2011/08/24 21:51:57] - Application Error
org.jruby.rack.RackInitializationException: exit
    from org/jruby/RubyKernel.java:836:in `exit'
    from /Users/samuelkadolph/foo/WEB-INF/gems/gems/bundler-1.0.18/lib/bundler/setup.rb:14:in `(root)'
    from org/jruby/RubyKernel.java:1047:in `require'
    from /Users/samuelkadolph/foo/WEB-INF/gems/gems/bundler-1.0.18/lib/bundler/setup.rb:32:in `require'
    from /Users/samuelkadolph/foo/WEB-INF/config/boot.rb:6:in `(root)'
    from org/jruby/RubyKernel.java:1047:in `require'
    from /Users/samuelkadolph/foo/WEB-INF/config/boot.rb:29:in `require'
    from file:/Users/samuelkadolph/foo/WEB-INF/lib/jruby-rack-1.0.9.jar!/jruby/rack/rails.rb:165:in `load_environment'
    from file:/Users/samuelkadolph/foo/WEB-INF/lib/jruby-rack-1.0.9.jar!/jruby/rack/rails.rb:173:in `to_app'
    from file:/Users/samuelkadolph/foo/WEB-INF/lib/jruby-rack-1.0.9.jar!/jruby/rack/rails.rb:193:in `new'
    from <web.xml>:1:in `(root)'
    from org/jruby/RubyBasicObject.java:1717:in `instance_eval'
    from file:/Users/samuelkadolph/foo/WEB-INF/lib/jruby-rack-1.0.9.jar!/vendor/rack-1.2.2/rack/builder.rb:46:in `initialize'
    from <web.xml>:1:in `(root)'

    at org.jruby.rack.DefaultRackApplicationFactory$4.init(DefaultRackApplicationFactory.java:204)
    at org.jruby.rack.DefaultRackApplicationFactory.getApplication(DefaultRackApplicationFactory.java:54)
    at org.jruby.rack.PoolingRackApplicationFactory.getApplication(PoolingRackApplicationFactory.java:95)
    at org.jruby.rack.DefaultRackDispatcher.process(DefaultRackDispatcher.java:28)
    at org.jruby.rack.RackFilter.doFilter(RackFilter.java:58)
    at winstone.FilterConfiguration.execute(FilterConfiguration.java:195)
    at winstone.RequestDispatcher.doFilter(RequestDispatcher.java:368)
    at winstone.RequestDispatcher.forward(RequestDispatcher.java:333)
    at winstone.RequestHandlerThread.processRequest(RequestHandlerThread.java:244)
    at winstone.RequestHandlerThread.run(RequestHandlerThread.java:150)
    at java.lang.Thread.run(Thread.java:680)
Caused by: org.jruby.exceptions.RaiseException: (SystemExit) exit
```

Output of `ls WEB-INF/gems/bundler/gems/`

```
activerecord-jdbc-adapter-84bee952aa80  activerecord-jdbcmysql-adapter      jdbc-mysql
```
##

**Comment by chadlwilson** [comment]
Closing this ancient issue. There is possibly still an issue with gemjars specifically, but will need a more modern example/reproducer.
