### ISSUE TITLE
"can't find executable bundle for bundler-1.0.20" error when running preinitializer.rb

### ISSUE THREAD

**Issue by javiervegas** [jruby/warbler#52]
Hi, I am using warbler 1.3.2 to package a rails 2.3.11 app that uses jruby 1.5.6 and bundler 1.0.20. When I deploy to Tomcat 6.0.29 on RedHat 5 I get a "can't find executable bundle for bundler-1.0.20" exception when tomcat is running the preinitializer.rb file that bundler needs http://gembundler.com/rails23.html for rails 2.3 apps.

Seems that the gems are packaged correctly and Tomcat can find the bundler gem, but it can not find the bundle executable that lives in the bin folder of the gem.  I have tried both packing my gems in a jar file and using the config.gem_path configuration in warble.rb but in both cases I get the same error. 

Is there any warble setting that I need to use so Tomcat can find the executables for the gems I have packed with warbler?
 
Here is my stack trace with a bunch of debugging info

<pre><code>
INFO: An exception happened during JRuby-Rack startup
can't find executable bundle for bundler-1.0.20
--- System
jruby 1.5.6 (ruby 1.8.7 patchlevel 249) (2010-12-03 6586) (Java HotSpot(TM) 64-Bit Server VM 1.6.0_03) [amd64-java]
Time: Thu Sep 29 06:18:50 +0000 2011
Server: Apache Tomcat/6.0.29
jruby.home: file:/opt/tomcat/webapps/bundle_manager/1.0.24/WEB-INF/lib/jruby-stdlib-1.5.6.jar!/META-INF/jruby.home

--- Context Init Parameters:
gem.path = /WEB-INF/vendor/bundler_gems
jruby.max.runtimes = 1
jruby.min.runtimes = 1
public.root = /
rails.env = production

--- Backtrace
file:/opt/tomcat/webapps/bundle_manager/1.0.24/WEB-INF/lib/jruby-stdlib-1.5.6.jar!/META-INF/jruby.home/lib/ruby/site_ruby/1.8/rubygems.rb:334:in `bin_path'
/opt/tomcat/tomcat-app/webapps/bundle_manager/WEB-INF/vendor/bundler_gems/gems/bundler-1.0.20/lib/bundler/rubygems_integration.rb:73:in `bin_path'
/opt/tomcat/tomcat-app/webapps/bundle_manager/WEB-INF/vendor/bundler_gems/gems/bundler-1.0.20/lib/bundler/runtime.rb:130:in `setup_environment'
/opt/tomcat/tomcat-app/webapps/bundle_manager/WEB-INF/vendor/bundler_gems/gems/bundler-1.0.20/lib/bundler/runtime.rb:13:in `setup'
/opt/tomcat/tomcat-app/webapps/bundle_manager/WEB-INF/vendor/bundler_gems/gems/bundler-1.0.20/lib/bundler.rb:111:in `setup'
/opt/tomcat/webapps/bundle_manager/1.0.24/WEB-INF/config/preinitializer.rb:16
/opt/tomcat/webapps/bundle_manager/1.0.24/WEB-INF/config/preinitializer.rb:28:in `load'
/opt/tomcat/webapps/bundle_manager/1.0.24/WEB-INF/config/boot.rb:28:in `preinitialize'
/opt/tomcat/webapps/bundle_manager/1.0.24/WEB-INF/config/boot.rb:10:in `boot!'
/opt/tomcat/webapps/bundle_manager/1.0.24/WEB-INF/config/boot.rb:123
/opt/tomcat/webapps/bundle_manager/1.0.24/WEB-INF/config/boot.rb:7:in `require'
/opt/tomcat/webapps/bundle_manager/1.0.24/WEB-INF/config/environment.rb:7
/opt/tomcat/webapps/bundle_manager/1.0.24/WEB-INF/config/environment.rb:54:in `load'
file:/opt/tomcat/webapps/bundle_manager/1.0.24/WEB-INF/lib/jruby-rack-1.0.10.jar!/jruby/rack/rails.rb:54:in `load_environment'
file:/opt/tomcat/webapps/bundle_manager/1.0.24/WEB-INF/lib/jruby-rack-1.0.10.jar!/jruby/rack/rails.rb:47:in `to_app'
file:/opt/tomcat/webapps/bundle_manager/1.0.24/WEB-INF/lib/jruby-rack-1.0.10.jar!/jruby/rack/rails.rb:193:in `new'
<web.xml>:1
file:/opt/tomcat/webapps/bundle_manager/1.0.24/WEB-INF/lib/jruby-rack-1.0.10.jar!/vendor/rack-1.3.2/rack/builder.rb:51:in `instance_eval'
file:/opt/tomcat/webapps/bundle_manager/1.0.24/WEB-INF/lib/jruby-rack-1.0.10.jar!/vendor/rack-1.3.2/rack/builder.rb:51:in `initialize'
<web.xml>:1:in `new'
<web.xml>:1

--- RubyGems
Gem.dir: file:/opt/tomcat/webapps/bundle_manager/1.0.24/WEB-INF/lib/jruby-stdlib-1.5.6.jar!/META-INF/jruby.home/lib/ruby/gems/1.8
Gem.path:
/opt/tomcat/tomcat-app/webapps/bundle_manager/WEB-INF/vendor/bundler_gems
file:/opt/tomcat/webapps/bundle_manager/1.0.24/WEB-INF/lib/jruby-stdlib-1.5.6.jar!/META-INF/jruby.home/lib/ruby/gems/1.8
Activated gems:
  bundler-1.0.20
  jruby-openssl-0.7.4
  bouncy-castle-java-1.5.0146.1

--- Bundler
Bundler.bundle_path: file:/opt/tomcat/webapps/bundle_manager/1.0.24/WEB-INF/lib/jruby-stdlib-1.5.6.jar!/META-INF/jruby.home/lib/ruby/gems/1.8
Bundler.root: /opt/tomcat/webapps/bundle_manager/1.0.24/WEB-INF
Gemfile: /opt/tomcat/webapps/bundle_manager/1.0.24/WEB-INF/Gemfile
Settings:
  without = development:test
  gemfile = /opt/tomcat/webapps/bundle_manager/1.0.24/WEB-INF/Gemfile

--- JRuby-Rack Config
background_spooling = false
compat_version = 
filter_adds_html = true
filter_verifies_resource = false
ignore_environment = false
initial_runtimes = 1
jms_connection_factory = 
jms_jndi_properties = 
logger = org.jruby.rack.logging.ServletContextLogger@17ab5d6d
logger_class_name = servlet_context
logger_name = jruby.rack
maximum_runtimes = 1
memory_buffer_size = 65536
num_initializer_threads = 
rackup = 
rackup_path = 
rewindable = true
runtime_timeout_seconds = 
serial_initialization = false
servlet_context = org.apache.catalina.core.ApplicationContextFacade@3aa9f827

Sep 29, 2011 6:18:50 AM org.apache.catalina.core.ApplicationContext log
SEVERE: unable to create shared application instance
org.jruby.rack.RackInitializationException: can't find executable bundle for bundler-1.0.20
	from /opt/tomcat/tomcat-app/webapps/bundle_manager/WEB-INF/vendor/bundler_gems/gems/bundler-1.0.20/lib/bundler/rubygems_integration.rb:73:in `bin_path'
	from /opt/tomcat/tomcat-app/webapps/bundle_manager/WEB-INF/vendor/bundler_gems/gems/bundler-1.0.20/lib/bundler/runtime.rb:130:in `setup_environment'
	from /opt/tomcat/tomcat-app/webapps/bundle_manager/WEB-INF/vendor/bundler_gems/gems/bundler-1.0.20/lib/bundler/runtime.rb:13:in `setup'
	from /opt/tomcat/tomcat-app/webapps/bundle_manager/WEB-INF/vendor/bundler_gems/gems/bundler-1.0.20/lib/bundler.rb:111:in `setup'
	from /opt/tomcat/webapps/bundle_manager/1.0.24/WEB-INF/config/preinitializer.rb:16
	from /opt/tomcat/webapps/bundle_manager/1.0.24/WEB-INF/config/preinitializer.rb:28:in `load'
	from /opt/tomcat/webapps/bundle_manager/1.0.24/WEB-INF/config/boot.rb:28:in `preinitialize'
	from /opt/tomcat/webapps/bundle_manager/1.0.24/WEB-INF/config/boot.rb:10:in `boot!'
	 ... 9 levels...
	from file:/opt/tomcat/webapps/bundle_manager/1.0.24/WEB-INF/lib/jruby-rack-1.0.10.jar!/vendor/rack-1.3.2/rack/builder.rb:51:in `initialize'
	from <web.xml>:1:in `new'
	from <web.xml>:1

	at org.jruby.rack.DefaultRackApplicationFactory$4.init(DefaultRackApplicationFactory.java:204)
	at org.jruby.rack.DefaultRackApplicationFactory.getApplication(DefaultRackApplicationFactory.java:54)
	at org.jruby.rack.SharedRackApplicationFactory.init(SharedRackApplicationFactory.java:27)
	at org.jruby.rack.RackServletContextListener.contextInitialized(RackServletContextListener.java:44)
	at org.apache.catalina.core.StandardContext.listenerStart(StandardContext.java:4135)
	at org.apache.catalina.core.StandardContext.start(StandardContext.java:4630)
	at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:791)
	at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:771)
	at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:546)
	at org.apache.catalina.startup.HostConfig.deployDescriptor(HostConfig.java:637)
	at org.apache.catalina.startup.HostConfig.deployDescriptors(HostConfig.java:563)
	at org.apache.catalina.startup.HostConfig.deployApps(HostConfig.java:498)
	at org.apache.catalina.startup.HostConfig.start(HostConfig.java:1277)
	at org.apache.catalina.startup.HostConfig.lifecycleEvent(HostConfig.java:321)
	at org.apache.catalina.util.LifecycleSupport.fireLifecycleEvent(LifecycleSupport.java:119)
	at org.apache.catalina.core.ContainerBase.start(ContainerBase.java:1053)
	at org.apache.catalina.core.StandardHost.start(StandardHost.java:785)
	at org.apache.catalina.core.ContainerBase.start(ContainerBase.java:1045)
	at org.apache.catalina.core.StandardEngine.start(StandardEngine.java:445)
	at org.apache.catalina.core.StandardService.start(StandardService.java:519)
	at org.apache.catalina.core.StandardServer.start(StandardServer.java:710)
	at org.apache.catalina.startup.Catalina.start(Catalina.java:581)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:597)
	at org.apache.catalina.startup.Bootstrap.start(Bootstrap.java:289)
	at org.apache.catalina.startup.Bootstrap.main(Bootstrap.java:414)
Caused by: org.jruby.exceptions.RaiseException: can't find executable bundle for bundler-1.0.20
	at Kernel.raise(file:/opt/tomcat/webapps/bundle_manager/1.0.24/WEB-INF/lib/jruby-stdlib-1.5.6.jar!/META-INF/jruby.home/lib/ruby/site_ruby/1.8/rubygems.rb:334)
	at #<Class:01x7664e5b2>.bin_path(/opt/tomcat/tomcat-app/webapps/bundle_manager/WEB-INF/vendor/bundler_gems/gems/bundler-1.0.20/lib/bundler/rubygems_integration.rb:73)
	at Bundler::RubygemsIntegration.bin_path(/opt/tomcat/tomcat-app/webapps/bundle_manager/WEB-INF/vendor/bundler_gems/gems/bundler-1.0.20/lib/bundler/runtime.rb:130)
	at Bundler::Runtime.setup_environment(/opt/tomcat/tomcat-app/webapps/bundle_manager/WEB-INF/vendor/bundler_gems/gems/bundler-1.0.20/lib/bundler/runtime.rb:13)
	at Bundler::Runtime.setup(/opt/tomcat/tomcat-app/webapps/bundle_manager/WEB-INF/vendor/bundler_gems/gems/bundler-1.0.20/lib/bundler.rb:111)
	at #<Class:01x28c13406>.setup(/opt/tomcat/webapps/bundle_manager/1.0.24/WEB-INF/config/preinitializer.rb:16)
	at (unknown).(unknown)(/opt/tomcat/webapps/bundle_manager/1.0.24/WEB-INF/config/preinitializer.rb:28)
	at Kernel.load(/opt/tomcat/webapps/bundle_manager/1.0.24/WEB-INF/config/boot.rb:28)
	at #<Class:01xbc22eb>.preinitialize(/opt/tomcat/webapps/bundle_manager/1.0.24/WEB-INF/config/boot.rb:10)
	at #<Class:01xbc22eb>.boot!(/opt/tomcat/webapps/bundle_manager/1.0.24/WEB-INF/config/boot.rb:123)
	at (unknown).(unknown)(/opt/tomcat/webapps/bundle_manager/1.0.24/WEB-INF/config/boot.rb:7)
	at Kernel.require(/opt/tomcat/webapps/bundle_manager/1.0.24/WEB-INF/config/environment.rb:7)
	at (unknown).(unknown)(/opt/tomcat/webapps/bundle_manager/1.0.24/WEB-INF/config/environment.rb:54)
	at Kernel.load(file:/opt/tomcat/webapps/bundle_manager/1.0.24/WEB-INF/lib/jruby-rack-1.0.10.jar!/jruby/rack/rails.rb:54)
	at JRuby::Rack::RailsBooter::Rails2Environment.load_environment(file:/opt/tomcat/webapps/bundle_manager/1.0.24/WEB-INF/lib/jruby-rack-1.0.10.jar!/jruby/rack/rails.rb:47)
	at JRuby::Rack::RailsBooter::Rails2Environment.to_app(file:/opt/tomcat/webapps/bundle_manager/1.0.24/WEB-INF/lib/jruby-rack-1.0.10.jar!/jruby/rack/rails.rb:193)
	at #<Class:01x2ffecaeb>.new(<web.xml>:1)
	at (unknown).(unknown)(file:/opt/tomcat/webapps/bundle_manager/1.0.24/WEB-INF/lib/jruby-rack-1.0.10.jar!/vendor/rack-1.3.2/rack/builder.rb:51)
	at Kernel.instance_eval(file:/opt/tomcat/webapps/bundle_manager/1.0.24/WEB-INF/lib/jruby-rack-1.0.10.jar!/vendor/rack-1.3.2/rack/builder.rb:51)
	at Kernel.instance_eval(file:/opt/tomcat/webapps/bundle_manager/1.0.24/WEB-INF/lib/jruby-rack-1.0.10.jar!/vendor/rack-1.3.2/rack/builder.rb:51)
	at Rack::Builder.initialize(<web.xml>:1)
	at (unknown).new(<web.xml>:1)
	at (unknown).(unknown)(:1)
Sep 29, 2011 6:18:50 AM org.apache.catalina.core.ApplicationContext log
SEVERE: Error: application initialization failed
org.jruby.rack.RackInitializationException: unable to create shared application instance
	at org.jruby.rack.SharedRackApplicationFactory.init(SharedRackApplicationFactory.java:39)
	at org.jruby.rack.RackServletContextListener.contextInitialized(RackServletContextListener.java:44)
	at org.apache.catalina.core.StandardContext.listenerStart(StandardContext.java:4135)
	at org.apache.catalina.core.StandardContext.start(StandardContext.java:4630)
	at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:791)
	at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:771)
	at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:546)
	at org.apache.catalina.startup.HostConfig.deployDescriptor(HostConfig.java:637)
	at org.apache.catalina.startup.HostConfig.deployDescriptors(HostConfig.java:563)
	at org.apache.catalina.startup.HostConfig.deployApps(HostConfig.java:498)
	at org.apache.catalina.startup.HostConfig.start(HostConfig.java:1277)
	at org.apache.catalina.startup.HostConfig.lifecycleEvent(HostConfig.java:321)
	at org.apache.catalina.util.LifecycleSupport.fireLifecycleEvent(LifecycleSupport.java:119)
	at org.apache.catalina.core.ContainerBase.start(ContainerBase.java:1053)
	at org.apache.catalina.core.StandardHost.start(StandardHost.java:785)
	at org.apache.catalina.core.ContainerBase.start(ContainerBase.java:1045)
	at org.apache.catalina.core.StandardEngine.start(StandardEngine.java:445)
	at org.apache.catalina.core.StandardService.start(StandardService.java:519)
	at org.apache.catalina.core.StandardServer.start(StandardServer.java:710)
	at org.apache.catalina.startup.Catalina.start(Catalina.java:581)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:597)
	at org.apache.catalina.startup.Bootstrap.start(Bootstrap.java:289)
	at org.apache.catalina.startup.Bootstrap.main(Bootstrap.java:414)
Caused by: org.jruby.rack.RackInitializationException: can't find executable bundle for bundler-1.0.20
	from /opt/tomcat/tomcat-app/webapps/bundle_manager/WEB-INF/vendor/bundler_gems/gems/bundler-1.0.20/lib/bundler/rubygems_integration.rb:73:in `bin_path'
	from /opt/tomcat/tomcat-app/webapps/bundle_manager/WEB-INF/vendor/bundler_gems/gems/bundler-1.0.20/lib/bundler/runtime.rb:130:in `setup_environment'
	from /opt/tomcat/tomcat-app/webapps/bundle_manager/WEB-INF/vendor/bundler_gems/gems/bundler-1.0.20/lib/bundler/runtime.rb:13:in `setup'
	from /opt/tomcat/tomcat-app/webapps/bundle_manager/WEB-INF/vendor/bundler_gems/gems/bundler-1.0.20/lib/bundler.rb:111:in `setup'
	from /opt/tomcat/webapps/bundle_manager/1.0.24/WEB-INF/config/preinitializer.rb:16
	from /opt/tomcat/webapps/bundle_manager/1.0.24/WEB-INF/config/preinitializer.rb:28:in `load'
	from /opt/tomcat/webapps/bundle_manager/1.0.24/WEB-INF/config/boot.rb:28:in `preinitialize'
	from /opt/tomcat/webapps/bundle_manager/1.0.24/WEB-INF/config/boot.rb:10:in `boot!'
	 ... 9 levels...
	from file:/opt/tomcat/webapps/bundle_manager/1.0.24/WEB-INF/lib/jruby-rack-1.0.10.jar!/vendor/rack-1.3.2/rack/builder.rb:51:in `initialize'
	from <web.xml>:1:in `new'
	from <web.xml>:1

	at org.jruby.rack.DefaultRackApplicationFactory$4.init(DefaultRackApplicationFactory.java:204)
	at org.jruby.rack.DefaultRackApplicationFactory.getApplication(DefaultRackApplicationFactory.java:54)
	at org.jruby.rack.SharedRackApplicationFactory.init(SharedRackApplicationFactory.java:27)
	... 25 more
Caused by: org.jruby.exceptions.RaiseException: can't find executable bundle for bundler-1.0.20
	at Kernel.raise(file:/opt/tomcat/webapps/bundle_manager/1.0.24/WEB-INF/lib/jruby-stdlib-1.5.6.jar!/META-INF/jruby.home/lib/ruby/site_ruby/1.8/rubygems.rb:334)
	at #<Class:01x7664e5b2>.bin_path(/opt/tomcat/tomcat-app/webapps/bundle_manager/WEB-INF/vendor/bundler_gems/gems/bundler-1.0.20/lib/bundler/rubygems_integration.rb:73)
	at Bundler::RubygemsIntegration.bin_path(/opt/tomcat/tomcat-app/webapps/bundle_manager/WEB-INF/vendor/bundler_gems/gems/bundler-1.0.20/lib/bundler/runtime.rb:130)
	at Bundler::Runtime.setup_environment(/opt/tomcat/tomcat-app/webapps/bundle_manager/WEB-INF/vendor/bundler_gems/gems/bundler-1.0.20/lib/bundler/runtime.rb:13)
	at Bundler::Runtime.setup(/opt/tomcat/tomcat-app/webapps/bundle_manager/WEB-INF/vendor/bundler_gems/gems/bundler-1.0.20/lib/bundler.rb:111)
	at #<Class:01x28c13406>.setup(/opt/tomcat/webapps/bundle_manager/1.0.24/WEB-INF/config/preinitializer.rb:16)
	at (unknown).(unknown)(/opt/tomcat/webapps/bundle_manager/1.0.24/WEB-INF/config/preinitializer.rb:28)
	at Kernel.load(/opt/tomcat/webapps/bundle_manager/1.0.24/WEB-INF/config/boot.rb:28)
	at #<Class:01xbc22eb>.preinitialize(/opt/tomcat/webapps/bundle_manager/1.0.24/WEB-INF/config/boot.rb:10)
	at #<Class:01xbc22eb>.boot!(/opt/tomcat/webapps/bundle_manager/1.0.24/WEB-INF/config/boot.rb:123)
	at (unknown).(unknown)(/opt/tomcat/webapps/bundle_manager/1.0.24/WEB-INF/config/boot.rb:7)
	at Kernel.require(/opt/tomcat/webapps/bundle_manager/1.0.24/WEB-INF/config/environment.rb:7)
	at (unknown).(unknown)(/opt/tomcat/webapps/bundle_manager/1.0.24/WEB-INF/config/environment.rb:54)
	at Kernel.load(file:/opt/tomcat/webapps/bundle_manager/1.0.24/WEB-INF/lib/jruby-rack-1.0.10.jar!/jruby/rack/rails.rb:54)
	at JRuby::Rack::RailsBooter::Rails2Environment.load_environment(file:/opt/tomcat/webapps/bundle_manager/1.0.24/WEB-INF/lib/jruby-rack-1.0.10.jar!/jruby/rack/rails.rb:47)
	at JRuby::Rack::RailsBooter::Rails2Environment.to_app(file:/opt/tomcat/webapps/bundle_manager/1.0.24/WEB-INF/lib/jruby-rack-1.0.10.jar!/jruby/rack/rails.rb:193)
	at #<Class:01x2ffecaeb>.new(<web.xml>:1)
	at (unknown).(unknown)(file:/opt/tomcat/webapps/bundle_manager/1.0.24/WEB-INF/lib/jruby-rack-1.0.10.jar!/vendor/rack-1.3.2/rack/builder.rb:51)
	at Kernel.instance_eval(file:/opt/tomcat/webapps/bundle_manager/1.0.24/WEB-INF/lib/jruby-rack-1.0.10.jar!/vendor/rack-1.3.2/rack/builder.rb:51)
	at Kernel.instance_eval(file:/opt/tomcat/webapps/bundle_manager/1.0.24/WEB-INF/lib/jruby-rack-1.0.10.jar!/vendor/rack-1.3.2/rack/builder.rb:51)
	at Rack::Builder.initialize(<web.xml>:1)
	at (unknown).new(<web.xml>:1)
	at (unknown).(unknown)(:1)
</code></pre>

**Comment by jkutner** [comment]
This should be fixed in the latest warbler. please let me know if we need to reopen
