### ISSUE TITLE
"<URL> is not yet checked out. Run `bundle install` first." for Gems referenced at Github

### ISSUE THREAD

**Issue by rammpeter** [jruby/warbler#537]
Starting with 2023 jar files created with warbler run into 
  "<URL> is not yet checked out. Run `bundle install` first."
if they contain references to Gems at Github in Gemfile.

I used warbler in the current state directly from Github, not the outdated Gem 2.0.5.

```
>java -jar Panorama.war
2023-02-23 11:37:12.083:INFO::main: Logging initialized @367ms
2023-02-23 11:37:12.098:INFO:oejr.Runner:main: Runner
2023-02-23 11:37:12.270:INFO:oejs.Server:main: jetty-9.2.9.v20150224
2023-02-23 11:37:30.029:WARN:oeja.AnnotationConfiguration:main: ServletContainerInitializers: detected. Class hierarchy: empty
2023-02-23 11:37:35.092:INFO:/:main: INFO: jruby 9.4.0.0 (3.1.0) 2022-11-23 95c0ec159f OpenJDK 64-Bit Server VM 25.71-b10 on 1.8.0-262-b10 +jit [x86_64-mswin32]
2023-02-23 11:37:35.107:INFO:/:main: INFO: using a shared (threadsafe!) runtime
Exception `Bundler::GitError' at uri:classloader:/META-INF/jruby.home/lib/ruby/stdlib/bundler/source/git/git_proxy.rb:224 - The git source http://github.com/rammpeter/Panorama_Gem is not yet checked out. Please run `bundle install` before trying to start your application
Exception `Bundler::GitError' at uri:classloader:/META-INF/jruby.home/lib/ruby/stdlib/bundler/source/git/git_proxy.rb:224 - The git source http://github.com/rammpeter/Panorama_Gem is not yet checked out. Please run `bundle install` before trying to start your application
Exception `Bundler::GitError' at uri:classloader:/META-INF/jruby.home/lib/ruby/stdlib/bundler/source/git/git_proxy.rb:224 - The git source http://github.com/rammpeter/Panorama_Gem is not yet checked out. Please run `bundle install` before trying to start your application
Exception `Bundler::PathError' at uri:classloader:/META-INF/jruby.home/lib/ruby/stdlib/bundler/source/path.rb:209 - The path `uri:classloader:/META-INF/jruby.home/lib/ruby/gems/shared/bundler/gems/Panorama_Gem-428fcfcbfbf1` does not exist.
Exception `Bundler::GitError' at uri:classloader:/META-INF/jruby.home/lib/ruby/stdlib/bundler/source/git/git_proxy.rb:224 - The git source http://github.com/rammpeter/Panorama_Gem is not yet checked out. Please run `bundle install` before trying to start your application
Exception `Bundler::GitError' at uri:classloader:/META-INF/jruby.home/lib/ruby/stdlib/bundler/source/git.rb:214 - http://github.com/rammpeter/Panorama_Gem is not yet checked out. Run `bundle install` first.
http://github.com/rammpeter/Panorama_Gem is not yet checked out. Run `bundle install` first.
uri:classloader:/META-INF/jruby.home/lib/ruby/stdlib/bundler/source/git.rb:214:in `load_spec_files'
uri:classloader:/META-INF/jruby.home/lib/ruby/stdlib/bundler/source/path.rb:107:in `local_specs'
uri:classloader:/META-INF/jruby.home/lib/ruby/stdlib/bundler/source/git.rb:178:in `specs'
uri:classloader:/META-INF/jruby.home/lib/ruby/stdlib/bundler/source/rubygems_aggregate.rb:35:in `block in build_index'
org/jruby/RubyArray.java:1988:in `each'
uri:classloader:/META-INF/jruby.home/lib/ruby/stdlib/bundler/source/rubygems_aggregate.rb:33:in `block in build_index'
uri:classloader:/META-INF/jruby.home/lib/ruby/stdlib/bundler/index.rb:9:in `build'
uri:classloader:/META-INF/jruby.home/lib/ruby/stdlib/bundler/source/rubygems_aggregate.rb:30:in `build_index'
uri:classloader:/META-INF/jruby.home/lib/ruby/stdlib/bundler/source/rubygems_aggregate.rb:12:in `initialize'
org/jruby/RubyClass.java:917:in `new'
uri:classloader:/META-INF/jruby.home/lib/ruby/stdlib/bundler/definition.rb:803:in `source_requirements'
uri:classloader:/META-INF/jruby.home/lib/ruby/stdlib/bundler/definition.rb:477:in `resolver'
uri:classloader:/META-INF/jruby.home/lib/ruby/stdlib/bundler/definition.rb:279:in `resolve'
uri:classloader:/META-INF/jruby.home/lib/ruby/stdlib/bundler/definition.rb:490:in `materialize'
uri:classloader:/META-INF/jruby.home/lib/ruby/stdlib/bundler/definition.rb:187:in `specs'
uri:classloader:/META-INF/jruby.home/lib/ruby/stdlib/bundler/definition.rb:244:in `specs_for'
uri:classloader:/META-INF/jruby.home/lib/ruby/stdlib/bundler/runtime.rb:18:in `setup'
uri:classloader:/META-INF/jruby.home/lib/ruby/stdlib/bundler.rb:161:in `setup'
uri:classloader:/META-INF/jruby.home/lib/ruby/stdlib/bundler/setup.rb:10:in `block in <main>'
uri:classloader:/META-INF/jruby.home/lib/ruby/stdlib/bundler/ui/shell.rb:136:in `with_level'
uri:classloader:/META-INF/jruby.home/lib/ruby/stdlib/bundler/ui/shell.rb:88:in `silence'
uri:classloader:/META-INF/jruby.home/lib/ruby/stdlib/bundler/setup.rb:10:in `<main>'
org/jruby/RubyKernel.java:1057:in `require'
uri:classloader:/META-INF/jruby.home/lib/ruby/stdlib/rubygems/core_ext/kernel_require.rb:85:in `require'
C:/Users/pramm/AppData/Local/Temp/jetty-0.0.0.0-8080-Panorama.war-_-any-3724136400543591912.dir/webapp/WEB-INF/config/boot.rb:3:in `<main>'
org/jruby/RubyKernel.java:1057:in `require'
uri:classloader:/META-INF/jruby.home/lib/ruby/stdlib/rubygems/core_ext/kernel_require.rb:85:in `require'
uri:classloader:/jruby/rack/rails/environment3.rb:23:in `load_environment'
uri:classloader:/jruby/rack/rails_booter.rb:83:in `load_environment'
<script>:1:in `<main>'
Exception `SystemExit' at org/jruby/RubyKernel.java:795 - exit
Exception `SystemExit' at org/jruby/RubyKernel.java:795 - exit

```

Before 2023 warbler worked properly with Github references as described in the documentation.

**Comment by tillsc** [comment]
Using `gem 'jruby-jars', '< 9.4'` solved this for me with warbler 2.0.5

**Comment by joerixaop** [comment]
#539 is a duplicate of this, but it has a workaround (adding the line `Gem.paths = ENV` to META-INF/init.rb).
It's a bit unclear why JRuby 9.4 there is a need to reset the Gem.paths after modifying the ENV variables and JRuby 9.3 there is no need, I would assume that it is because in JRuby 9.4 the Gem.paths is initialized earlier in the startup process.
