### ISSUE TITLE
facing issue while creating war file Jruby based rails application

### ISSUE THREAD

**Issue by shahrutul1993** [jruby/warbler#543]
I am trying to create war file using warble gem and I am using Juby based rails application with version 6.0.
when I try to run then its gives me below error.

Does anyone have any idea?
your help would be apricated.
Thanks!

"Caused by:
IOError: Cannot run program "C:\Program Files (x86)\Common Files\Oracle\Java\javapath\java.exe" (in directory "project directory"): CreateProcess error=206, The filename or extension is too long
org/jruby/RubyKernel.java:1712:in `system'
C:/jruby-9.2.16.0/lib/ruby/gems/shared/gems/rake-13.0.3/lib/rake/file_utils.rb:54:in `sh'
C:/jruby-9.2.16.0/lib/ruby/gems/shared/gems/warbler-2.0.5/lib/warbler/jar.rb:77:in `sh_jrubyc'
C:/jruby-9.2.16.0/lib/ruby/gems/shared/gems/warbler-2.0.5/lib/warbler/jar.rb:68:in `block in run_jrubyc'
org/jruby/RubyArray.java:1851:in `each_slice'
C:/jruby-9.2.16.0/lib/ruby/gems/shared/gems/rake-13.0.3/lib/rake/file_list.rb:79:in `each_slice'
C:/jruby-9.2.16.0/lib/ruby/gems/shared/gems/warbler-2.0.5/lib/warbler/jar.rb:60:in `run_jrubyc'
C:/jruby-9.2.16.0/lib/ruby/gems/shared/gems/warbler-2.0.5/lib/warbler/jar.rb:50:in `compile'
C:/jruby-9.2.16.0/lib/ruby/gems/shared/gems/warbler-2.0.5/lib/warbler/task.rb:109:in `block in define_compiled_task'
C:/jruby-9.2.16.0/lib/ruby/gems/shared/gems/rake-13.0.3/lib/rake/task.rb:281:in `block in execute'
org/jruby/RubyArray.java:1809:in `each'
C:/jruby-9.2.16.0/lib/ruby/gems/shared/gems/rake-13.0.3/lib/rake/task.rb:281:in `execute'
C:/jruby-9.2.16.0/lib/ruby/gems/shared/gems/rake-13.0.3/lib/rake/task.rb:219:in `block in invoke_with_call_chain'
C:/jruby-9.2.16.0/lib/ruby/stdlib/monitor.rb:237:in `block in mon_synchronize'
org/jruby/RubyThread.java:759:in `handle_interrupt'
C:/jruby-9.2.16.0/lib/ruby/stdlib/monitor.rb:236:in `block in mon_synchronize'
org/jruby/RubyThread.java:759:in `handle_interrupt'
C:/jruby-9.2.16.0/lib/ruby/stdlib/monitor.rb:233:in `mon_synchronize'
C:/jruby-9.2.16.0/lib/ruby/gems/shared/gems/rake-13.0.3/lib/rake/task.rb:199:in `invoke_with_call_chain'
C:/jruby-9.2.16.0/lib/ruby/gems/shared/gems/rake-13.0.3/lib/rake/task.rb:188:in `invoke'
C:/jruby-9.2.16.0/lib/ruby/gems/shared/gems/warbler-2.0.5/lib/warbler/task.rb:88:in `block in define_main_task'
org/jruby/RubyArray.java:1809:in `each'
C:/jruby-9.2.16.0/lib/ruby/gems/shared/gems/warbler-2.0.5/lib/warbler/task.rb:82:in `block in define_main_task'
C:/jruby-9.2.16.0/lib/ruby/gems/shared/gems/rake-13.0.3/lib/rake/task.rb:281:in `block in execute'
org/jruby/RubyArray.java:1809:in `each'
C:/jruby-9.2.16.0/lib/ruby/gems/shared/gems/rake-13.0.3/lib/rake/task.rb:281:in `execute'
C:/jruby-9.2.16.0/lib/ruby/gems/shared/gems/rake-13.0.3/lib/rake/task.rb:219:in `block in invoke_with_call_chain'
C:/jruby-9.2.16.0/lib/ruby/stdlib/monitor.rb:237:in `block in mon_synchronize'
org/jruby/RubyThread.java:759:in `handle_interrupt'
C:/jruby-9.2.16.0/lib/ruby/stdlib/monitor.rb:236:in `block in mon_synchronize'
org/jruby/RubyThread.java:759:in `handle_interrupt'
C:/jruby-9.2.16.0/lib/ruby/stdlib/monitor.rb:233:in `mon_synchronize'
C:/jruby-9.2.16.0/lib/ruby/gems/shared/gems/rake-13.0.3/lib/rake/task.rb:199:in `invoke_with_call_chain'
C:/jruby-9.2.16.0/lib/ruby/gems/shared/gems/rake-13.0.3/lib/rake/task.rb:243:in `block in invoke_prerequisites'
org/jruby/RubyArray.java:1809:in `each'
C:/jruby-9.2.16.0/lib/ruby/gems/shared/gems/rake-13.0.3/lib/rake/task.rb:241:in `invoke_prerequisites'
C:/jruby-9.2.16.0/lib/ruby/gems/shared/gems/rake-13.0.3/lib/rake/task.rb:218:in `block in invoke_with_call_chain'
C:/jruby-9.2.16.0/lib/ruby/stdlib/monitor.rb:237:in `block in mon_synchronize'
org/jruby/RubyThread.java:759:in `handle_interrupt'
C:/jruby-9.2.16.0/lib/ruby/stdlib/monitor.rb:236:in `block in mon_synchronize'
org/jruby/RubyThread.java:759:in `handle_interrupt'
C:/jruby-9.2.16.0/lib/ruby/stdlib/monitor.rb:233:in `mon_synchronize'
C:/jruby-9.2.16.0/lib/ruby/gems/shared/gems/rake-13.0.3/lib/rake/task.rb:199:in `invoke_with_call_chain'
C:/jruby-9.2.16.0/lib/ruby/gems/shared/gems/rake-13.0.3/lib/rake/task.rb:188:in `invoke'
C:/jruby-9.2.16.0/lib/ruby/gems/shared/gems/rake-13.0.3/lib/rake/application.rb:160:in `invoke_task'
C:/jruby-9.2.16.0/lib/ruby/gems/shared/gems/rake-13.0.3/lib/rake/application.rb:116:in `block in top_level'
org/jruby/RubyArray.java:1809:in `each'
C:/jruby-9.2.16.0/lib/ruby/gems/shared/gems/rake-13.0.3/lib/rake/application.rb:116:in `block in top_level'
C:/jruby-9.2.16.0/lib/ruby/gems/shared/gems/rake-13.0.3/lib/rake/application.rb:125:in `run_with_threads'
C:/jruby-9.2.16.0/lib/ruby/gems/shared/gems/rake-13.0.3/lib/rake/application.rb:110:in `top_level'
C:/jruby-9.2.16.0/lib/ruby/gems/shared/gems/rake-13.0.3/lib/rake/application.rb:83:in `block in run'
C:/jruby-9.2.16.0/lib/ruby/gems/shared/gems/rake-13.0.3/lib/rake/application.rb:186:in `standard_exception_handling'
C:/jruby-9.2.16.0/lib/ruby/gems/shared/gems/rake-13.0.3/lib/rake/application.rb:80:in `run'
C:/jruby-9.2.16.0/lib/ruby/gems/shared/gems/warbler-2.0.5/lib/warbler/application.rb:79:in `run'
C:/jruby-9.2.16.0/lib/ruby/gems/shared/gems/warbler-2.0.5/lib/warbler/application.rb:74:in `run'
C:/jruby-9.2.16.0/lib/ruby/gems/shared/gems/warbler-2.0.5/bin/warble:11:in `<main>'
org/jruby/RubyKernel.java:1009:in `load'
C:\jruby-9.2.16.0\bin\warble:23:in `<main>'
Tasks: TOP => war:compiled"

**Comment by thimios** [comment]
any updates on this? We are also facing the same issue. Adding 

```
config.webxml.org.eclipse.jetty.servlet.default.dirAllowed = false
```

does not have an effect on the generated web.xml file

**Comment by chadlwilson** [comment]
@kares if this is indeed the case and is valid for non-jetty, do you want to move this issue to the other project when you have a minute?
